### ISSUE TITLE
Site title should be linked on the paged blog

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#109]
**Describe the bug**

When navigating the pages on the list of latest posts, (/page/2 etc). the site title should be a link back to the front page.

**Comment by metodiew** [comment]
I have added a `href` using `home_url()` function. I guess this is simple enough as a fist patch here, but let me know if there is anything I'm missing?

**Comment by aristath** [comment]
Reopening this one, we'll need to come up with a better solution.

**Comment by metodiew** [comment]
hey @aristath happy to work on an update, but could you please clarify what do you think for a better solution here?

The logo site title should return to the homepage in any case, IMO, hence I've added the link, but happy to explore more options

Edit, I just saw the update here https://github.com/WordPress/twentytwentyone/pull/139

**Comment by metodiew** [comment]
I've applied an update, based on @carolinan's feedback in https://github.com/WordPress/twentytwentyone/pull/139

You can find the commit here https://github.com/WordPress/twentytwentyone/compare/trunk...metodiew:bugfix/109, but I didn't want to open a new pull request before I get an approval :)

Let me know if there is a way to optimize the communication on my end ^_^
