### ISSUE TITLE
Single post: Tags are not correctly aligned

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#111]
**Describe the bug**
In single post view, the tags are shown in different positions depending on the browser.
In Chrome, the tags are on the right hand side.
In Firefox and Edge, the tags are shown closer to the center, below the 
publishing date.

**To Reproduce**
1. Go to a single post view for a post that has tags.
2. View this page in different browsers to see the inconsistency.

**Expected behavior**
The tags should be positioned below the the categories on the right hand side.

**Screenshots**
![tags in Chrome are aligned to the right.](https://user-images.githubusercontent.com/7422055/93856626-93f9ea80-fcb9-11ea-9eb2-85f438071f3d.png)
![tags in Firefox are aligned more to the center](https://user-images.githubusercontent.com/7422055/93856628-93f9ea80-fcb9-11ea-941a-bc7d817c1895.png)
![tags in Edge are aligned more to the center](https://user-images.githubusercontent.com/7422055/93856629-94928100-fcb9-11ea-9613-4613fbd0d731.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, PC

**Comment by kellylawrence** [comment]
Hello @carolinan. I submitted a potential fix for this issue in https://github.com/WordPress/twentytwentyone/pull/146.
