### ISSUE TITLE
Explore adding an additional block area below the header

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#112]
**Is your feature request related to a problem? Please describe.**

In 5.6, widget areas can be used as block areas with the help of the new widget screen.
The theme relies on blocks and block patterns, and by adding an additional but optional block area below the header,
or at the bottom of the header, creators are given more flexibility.

This block area can be used to add:
Secondary menus (widget or navigation block) -The theme only has one menu.
Search form (widget or search block)
Social links (block) (The theme does not include a social menu)
An image or a cover block as a header image. (The theme does not include an option for a header image)
A call to action (Buttons block or widget)
Advertisements (block or widget)

**Comment by melchoyce** [comment]
Some mockups:

![header-sidebar (1)](https://user-images.githubusercontent.com/2846578/94590114-31be5e00-0254-11eb-8939-8e8cefc8ca6b.jpg)

I think it'd be fun to explore this in the FSE version of the theme. I'm not sure we should include it in the traditional version, though — hoping we can keep the traditional version as lean as possible.
