### ISSUE TITLE
Add theme screenshot

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#113]
**Describe the bug**
The theme is missing a screenshot.

**Comment by luminuu** [comment]
Waiting on #1 and will be added shortly before Beta 1.

**Comment by melchoyce** [comment]
Screenshot uploaded! Closing this issue.

**Comment by joyously** [comment]
Ha! I just downloaded and saw that it wasn't there. But it does match the description of a "blank canvas"!
![Manage Themes ‹ Local Current WP — WordPress-00](https://user-images.githubusercontent.com/7957680/96279208-fafa7e80-0f9b-11eb-8a10-b40b61c49680.jpg)
