### ISSUE TITLE
Custom block styles

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#116]
Block styles are style variations that can be selected in the block sidebar.
Block styles are different from patterns, but can be used with and inside patterns.

[A file has been created](https://github.com/WordPress/twentytwentyone/blob/trunk/inc/block-styles.php) in preparation for adding block styles.

Design elements that might be useful as block styles:
The border that is used in several of the block patterns

**Comment by LittleBigThing** [comment]
Block styles would be very cool!

Do you mean for the border as well as for the overlapping patterns, @carolinan? It would be cool if borders could be added a different way. Aren't there plans on adding border controls to the editor in the future?

**Comment by carolinan** [comment]
@LittleBigThing There already is a pull request for this border, it is part of #140 

I think that for other block styles, the _block pattern ideas_ issue template would work.

**Comment by luminuu** [comment]
Closing this, please suggest specific block styles in a separate issue.
