### ISSUE TITLE
Add a theme description

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#119]
**Describe the bug**
The theme is missing a description, this needs to be added to 
https://github.com/WordPress/twentytwentyone/blob/trunk/assets/sass/01-settings/file-header.scss#L6
and the readme.txt file.

**Comment by melchoyce** [comment]
First draft:

> Twenty Twenty-One is a new default theme for WordPress, designed to be a blank canvas for the block editor. It features unique block patterns to give your site a head start, soft colors, and a fresh — but timeless — design. Use it for your next portfolio, business website, or personal blog.

**Comment by marybaum** [comment]
How about:

> The latest default theme for WordPress, Twenty Twenty-One is a blank canvas for your best ideas. And it makes the block editor your most capable brush. 

>With a fresh take on highly usable block patterns to give your site a head start, this theme's soft colors and sparkling – yet timeless – design will put your work front and center. 

>Take it for a spin! And see how Twenty Twenty-One elevates the newest version of your portfolio, business website or personal blog.

**Comment by francescamarano** [comment]
> The <del>latest</del> default theme for WordPress, Twenty Twenty-One is a blank canvas for your best ideas. And it makes the block editor your most capable brush.
> 
> With a fresh take on highly <del>usable</del> block patterns to give your site a head start, this theme's soft colors and <del>sparkling</del> – yet timeless – design will put your work front and center.
> 
> Take it for a spin! And see how Twenty Twenty-One elevates the newest version of your portfolio, business website or personal blog.

- Usable is a very specific word in web development and design, so I wouldn't use it in this context.
- Not sure sparkling is an accurate adjective to describe this design, which is actually linear, elegant, rigorous and minimalistic. 
- _elevates the newest version_ - this sentences assumed that you already have said websites and you are updating the design, but for some people, this might be their first website. So I would phrase it a bit differently: "Take it for a spin! Use the Twenty Twenty-One theme for your next portfolio, business website, or personal blog."

So proposed version from me:

> The new default theme for WordPress, Twenty Twenty-One, is a blank canvas for your best ideas. And it makes the block editor your most capable brush.
> 
> With a fresh take on easy to use block patterns, the theme gives your site a head start, with its soft colors and its modern – yet timeless – design that will put your work front and center.
> 
> Take it for a spin! AUse the Twenty Twenty-One theme for your next portfolio, business website, or personal blog.

**Comment by melchoyce** [comment]
Ran this by an editor, here's her take:

> The latest default theme for WordPress, Twenty Twenty-One is a blank canvas for your ideas, and it makes the block editor your best brush. With new block patterns, which allow you to create a beautiful layout in a matter of seconds, this theme’s soft colors and eye-catching—yet timeless—design will let your work shine. Take it for a spin! See how Twenty Twenty-One elevates your portfolio, business website, or personal blog.

**Comment by pattonwebz** [comment]
The text `The latest default theme for WordPress, ` seems to me to be a little redundant. There will come a time when `latest` is inaccurate and it would need changes. I would hope that people know they are using `WordPress` :stuck_out_tongue: 

Could we just drop that initial entry text completely? It would remove the need for some punctuation as well in the first sentence and give it a little more _punch_ (for want of a better word lol).

> Twenty Twenty-One is a blank canvas for your ideas and it makes the block editor your best brush.

Or else:

> Twenty Twenty-One is a blank canvas for your ideas - it makes the block editor your best brush.
