### ISSUE TITLE
Any theme image assets should be optimized before a release

### ISSUE THREAD

**Issue by lukecav** [WordPress/twentytwentyone#122]
The image folder is 2.95 MB in size at the moment.
https://github.com/WordPress/twentytwentyone/tree/trunk/assets/images

The existing images can be optimized and reduced 2 MB in size. ImageOptimizer would be worth taking a look at.
https://github.com/spatie/image-optimizer
https://github.com/TypistTech/image-optimize-command

**Comment by carolinan** [comment]
Yes these are only place holder images for testing the starter content and they will be replaced :)

**Comment by dingo-d** [comment]
I usually use https://imageoptim.com/mac before adding any asset. Not sure I'd bundle anything in the theme just for image optimizing (sounds like plugin territory to me).

**Comment by lukecav** [comment]
@dingo-d 
The recommendation was more for offline optimization of images assets before they are pushed up to the GitHub repo or before a release, not for building in image optimization into the theme. ImageOptim does work very well for offline local image optimization.

**Comment by LittleBigThing** [comment]
I would also suggest to include as little images as possible if ‘real‘ images are included (see size and license). About 3 different formats might be sufficient and we could re-use the same image for patterns with more images? We might also use ‘empty‘ placeholder images when shipping?
