### ISSUE TITLE
Adding `@wordpress/env` for local development into the project

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/twentytwentyone#123]
**Is your feature request related to a problem? Please describe.**
When working with themes locally it is always a hurdle to setup a separate dev environment for it. With the [`@wordpress/env`](https://npmjs.com/package/@wordpress/env) package that was build by the Gutenberg theme this is very easy to just have one npm command: `npm run wp-env start` to start a local environment server. 

I can happily create a PR for this. But I would love your thoughts about having this as a part of the repository.

**Comment by jffng** [comment]
Adding `wp-env` as a development dependency seems reasonable to me and nice a way to increase the inclusivity of who can contribute, since we're already requiring node + npm to compile the styles.

**Comment by carolinan** [comment]
+1 As long as the documentation to use it is added to the contributing file for the repo.
It is actually not as straight forward to set up for the first time, especially not on Windows, so it is important that contributors know that they are not required to use it.

**Comment by fabiankaegy** [comment]
@carolinan I have updated my PR (#124) to include some basic documentation about how to get started. 

Can you elaborate how granular you would like the doc's in the theme to get? / at which point should we link to the docs of the `wp-env` project?

**Comment by carolinan** [comment]
You can combine what you wrote with the commands added here:
https://github.com/WordPress/twentytwentyone/pull/127/files#diff-6a3371457528722a734f3c51d9238c13R87
