### ISSUE TITLE
Submenu background color doesn't update in Customizer preview when background color is changed

### ISSUE THREAD

**Issue by ZebulanStanphill** [WordPress/twentytwentyone#128]
## Description
The background color used by submenus in the navigation doesn't update in the Customizer preview when the background color setting is modified. For example, if the background color was pastel green and you try setting it to black, submenus will look like this while you're in the Customizer:

![image](https://user-images.githubusercontent.com/19592990/94065342-a4d95780-fdb0-11ea-93e9-6a49f94cbbc9.png)

Once you save and refresh, it updates, and of course the final output on the front-end works as expected. But the appearance in the Customizer should automatically update as you change the background color option.

## Reproduction steps
1. If you haven't already, set the Primary Navigation to a menu that includes a submenu.
2. Open the Customizer.
3. Go to the Colors section.
3. Set a new background color.
4. Hover over the submenu while in the Customizer.

**Comment by carolinan** [comment]
A fix for this is included as part of #142 because I needed it for the button colors, but since that PR needs more testing, I'll create a new PR with just this update.

**Comment by kishanjasani** [comment]
@carolinan Please check the above PR will resolve this submenu background color issue.

**Comment by acosmin** [comment]
@kishanjasani that would work ok if the menu is on one line. If the menu's length is bigger, it will go on two lines... sub-menus will cause some overlapping issues. Also, if the sub-menu is big enough it can overlap with the page title... causing the same issues.

**Comment by kishanjasani** [comment]
@acosmin It's not for the only a one-line menu. It will also work for a nested multiple menus length. I am attaching one tested screenshot which will show you It's also working for submenus too.
![Uploading screenshot-rtpanel.local-2020.09.26-14_45_22.png…]()
