### ISSUE TITLE
Add option to use excerpts on posts page

### ISSUE THREAD

**Issue by ZebulanStanphill** [WordPress/twentytwentyone#129]
This is basically the Twenty Twenty One version of https://github.com/WordPress/twentytwenty/issues/2.

Twenty Twenty has an option to use excerpts on the default posts page. This option is currently absent from Twenty Twenty One. I think it would be a good idea to bring back this option. In fact, I'd prefer if excerpts were used by default. The inability to change this has been a major missing feature in previous default themes, in my opinion. The default behavior of showing the entire content of every post on the home page has never made sense to me.

**Comment by LittleBigThing** [comment]
I prefer to use the ‘Read more‘ block for this. This provides a link to the full post and it is more flexible in placement. It has now also the option to hide the text before it on the single post page.

Note: the theme should provide some styling to the Read more block.

<img width="1188" alt="Screenshot 2020-09-25 at 15 28 56" src="https://user-images.githubusercontent.com/5901923/94272825-e9492c80-ff43-11ea-93b3-665c6b25c738.png">

**Comment by melchoyce** [comment]
We talked [a little bit about this on Figma](https://www.figma.com/file/OEtsCj8oD8JPVx4OvsS0U2?node-id=363:0#40271801) and landed on "show full posts on the blog page, but only show excerpts on archive pages." I also think it makes sense to show excerpts on the blog if one is manually written in the excerpt field, but if no custom excerpt is entered, show the full post. Does that make sense?

**Comment by ZebulanStanphill** [comment]
That's assuming everyone uses the excerpt field. I know a lot of people don't. I think there should at least be an option to use auto-excerpts on the blog page for posts with no dedicated excerpt. Maybe other people's expectations are different, but I don't expect to see the entirety of posts listed on a blog page. I guess I expect a blog page to act more like a "latest posts" archive that gives a quick look at all the latest posts without making you scroll past the entirety of them to see the next one.

**Comment by melchoyce** [comment]
Where would you look to find this setting?

**Comment by ZebulanStanphill** [comment]
@melchoyce I guess under a Customizer section titled "Blog", or at least a "Theme Options" section like what Twenty Twenty has:

![image](https://user-images.githubusercontent.com/19592990/94849834-a2e44980-03eb-11eb-9667-eb0a0082b18f.png)

**Comment by jdevalk** [comment]
I fully agree that this is needed. From an SEO perspective, showing full posts is a problem, so I'd even go for summary as the default setting.

**Comment by aristath** [comment]
>  I'd even go for summary as the default setting.

+1. Showing full posts in the posts page always annoyed me... When posts are long the page goes on for miles, and if they contain images it takes forever to load. It's not rare visiting a website and having to wait half a minute while it loads 10 posts each one with a few multi-MB images and each one being a full essay. If I want to read something I'll visit the post itself.

**Comment by metodiew** [comment]
+1 from me for having the summary/excerpt as the default option

**Comment by carolinan** [comment]
For this, I think the customizer option is easier to implement than starting to check for different formats of excerpts.

**Comment by carolinan** [comment]
Moved this to the beta 1 Milestone
