### ISSUE TITLE
Gutenberg feature watch list

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#14]
In this issue we can keep track of possible changes to Gutenberg that can affect the theme.

- [x] [Theme Support: Enable custom units by default](https://github.com/WordPress/gutenberg/pull/24873)
The theme currently includes `add_theme_support( 'custom-units' );`
If this will be enabled by default, the above will no longer be needed.
- [x] [Updates to the search block](https://github.com/WordPress/gutenberg/labels/%5BBlock%5D%20Search) (#103)

- [x] Updates to the separator https://github.com/WordPress/gutenberg/pull/25147

- [x] Updates to the column block https://github.com/WordPress/gutenberg/pull/24711

- [x]  Alignments added to headings block https://github.com/WordPress/gutenberg/pull/25917

**Comment by melchoyce** [comment]
As new featured to watch come in, let's add to the checklist in the first post.

**Comment by carolinan** [comment]
I forgot that the search block was here and created this issue: https://github.com/WordPress/twentytwentyone/issues/324

**Comment by carolinan** [comment]
Changes are also found in the 9.2 milestone  https://github.com/WordPress/gutenberg/milestone/132?closed=1

**Comment by carolinan** [comment]
Separator alignments tested without issues

**Comment by carolinan** [comment]
Heading block: **untestable** because of bugs already reported https://github.com/WordPress/gutenberg/issues/26335

**Comment by carolinan** [comment]
The columns block works well, with the exception of the **overlapping** block patterns. I'd like to ask @kjellr to test this:

When I change the width of the columns after adding the overlapping images pattern, the view does not change on the front.
The front and the editor should match.
Sample code:
https://gist.github.com/carolinan/34aa7d2d1d715ee8226afd0b15a8d189

**Comment by kjellr** [comment]
> When I change the width of the columns after adding the overlapping images pattern, the view does not change on the front. 
> The front and the editor should match.

Thanks! I opened #653 to take care of that.

**Comment by carolinan** [comment]
From https://github.com/WordPress/gutenberg/releases/tag/v9.3.0-rc.1

These changes may need additional testing:

- [x] _Cover block: Restore default overlay background._

- [x] _Heading Block: Fix double alignment controls in toolbar._ 

- [x] _Latest Posts: Add missing classname._ 

- [x] _Fix left and right alignments for video embeds._
