### ISSUE TITLE
Rename theme to hyphenated "Twenty Twenty-One"

### ISSUE THREAD

**Issue by justintadlock** [WordPress/twentytwentyone#141]
Compound numbers should be hyphenated.  "Twenty-One" instead of "Twenty One".

See: https://www.grammarly.com/blog/hyphen-in-compound-numbers/

**Comment by pattonwebz** [comment]
This is a good call. Now you mention it reading the initial name without the hyphen sounds to me almost like it is Twenty Twenty _version One_.

**Comment by melchoyce** [comment]
Yeah, let's update this. I can update the repo settings, but what impact does this have on the theme folder name and text domain?

**Comment by metodiew** [comment]
I have tested with one public test repository for the sake of the test, as I haven't done this in a while.

When you rename the repository, GitHub redirects you to the new URL - tested with:
- the repository itself
- a test issue
- a test pull request

According to the [Docs](https://docs.github.com/en/github/administering-a-repository/renaming-a-repository):
> When you rename a repository, all existing information, with the exception of project site URLs, is automatically redirected to the new name, including: Issues, Wikis, Stars, Followers

I would love someone to test on their end to confirm, you know, just in case :upside_down_face: 

P.S. you might need to update the URL in the [announcement post](https://make.wordpress.org/core/2020/09/23/introducing-twenty-twenty-one/)

**Comment by justintadlock** [comment]
@metodiew - Not renaming the repo.  Just the theme name in `style.css` and related files.

@melchoyce  - It shouldn't have any impact on the textdomain or folder name, which are customized to `twentytwentyone`.

**Comment by acosmin** [comment]
This is a great proposal https://make.wordpress.org/core/2020/09/23/introducing-twenty-twenty-one/#comment-39888

**Comment by kjellr** [comment]
I think this is all set now that https://github.com/WordPress/twentytwentyone/pull/143 has been merged. Is that correct?

**Comment by carolinan** [comment]
Found a few more, lets close this and try to remember it for any new file headers etc 👍
