### ISSUE TITLE
Stylelint passes locally but fails on github

### ISSUE THREAD

**Issue by jffng** [WordPress/twentytwentyone#144]
The stylelint configuration isn't respected on github actions at the moment.

To replicate:
- Check out a PR that has the stylelint check failing e.g. #140 
- `npm run lint:scss` 
- Verify that no errors are thrown

**Comment by kjellr** [comment]
Is this still an issue? I haven't seen it in any recent PRs.

**Comment by jffng** [comment]
Yeah. Upon closer inspection, it's not that github actions is ignoring our stylelint config. Rather, the `lint:scss` script isn't checking all the sass files the way github actions does, and thus doesn't report any errors.
