### ISSUE TITLE
Add navigation menu to the footer

### ISSUE THREAD

**Issue by LittleBigThing** [WordPress/twentytwentyone#148]
Add a navigation menu to the footer of the theme. This could replace the `.site-name` div.

The menu could serve for general links, as well as to add a link to the privacy policy page (perhaps automatically?).

<img width="1340" alt="Screenshot 2020-09-25 at 15 14 09" src="https://user-images.githubusercontent.com/5901923/94271353-cf0e4f00-ff41-11ea-87ec-b95204695959.png">

**Comment by naunha** [comment]
I think it's a good idea, a menu at the footer. Another option would be a social menu

**Comment by melchoyce** [comment]
Worried about too many conditionals re: replacing the logo — what if someone wants both? — so I've tried adding it to the top half of the footer:

![image](https://user-images.githubusercontent.com/2846578/95374176-02d76600-08ac-11eb-8ea5-74701520122f.png)

**Comment by francescamarano** [comment]
Question: why this can't be done with a widget?

**Comment by melchoyce** [comment]
That was the original plan, but the it came up through discussions ([one](https://wordpress.slack.com/archives/C02RP4VMP/p1601656298186700), [two](https://make.wordpress.org/core/2020/10/05/twenty-twenty-one-chat-agenda-5-october-2020/#comment-39971)) that an explicit menu location would be more flexible and easier to style.
