### ISSUE TITLE
The dividers does not change color when the site background color is changed.

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#149]
**Describe the bug**
When the background color is changed with the option in the customizer, the dividers do not change color.

**To Reproduce**
1. Go to the customizer
2. Click on the color option
3. Select a black background
4. See error, the dividers are #000 like the background.

**Expected behavior**
I expect the dividers colors to be adjusted.

The easiest solution would be to change the dividers from #000 to the primary or the secondary color, that is already 
used in the code that adjust the contrast.
See 
https://github.com/WordPress/twentytwentyone/blob/trunk/assets/sass/01-settings/global.scss#L86

Border with the current black color to the left, compared to the primary color on the right:
![color-comparison](https://user-images.githubusercontent.com/7422055/94286310-20740980-ff55-11ea-8316-cba00029eba1.png)

Examples where the color has been changed to white:

![color-example](https://user-images.githubusercontent.com/7422055/94285808-7ac09a80-ff54-11ea-958e-5feff1fe8abe.png)
![color-example2](https://user-images.githubusercontent.com/7422055/94285904-9e83e080-ff54-11ea-9483-19331d85a4c8.png)

Considerations: 
During testing I found a white divider on an all black background very _sharp_, and perhaps a different opacity can be tested here.

**Comment by melchoyce** [comment]
Yeah, it would be great if we could figure out a way to reduce the opacity for dark color schemes!
