### ISSUE TITLE
Post Format - Gallary: Remove border-bottom for all images in gallary item

### ISSUE THREAD

**Issue by kishanjasani** [WordPress/twentytwentyone#157]
**Describe the bug**
All gallery images have border-bottom. It's not supposed to have a border-bottom on each element of the gallery image.

**To Reproduce**
1. Take the post format: Gallary
2. Add gallery in the classic editor
3. You will get underlined in each image.

**Expected behavior**
There should not be a border-bottom.

**Screenshots**
![gallery_issue](https://user-images.githubusercontent.com/25550562/94335793-8c10b200-fffb-11ea-93b5-100ea705163a.png)

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.5.1]

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - Browser [e.g. chrome]

**Comment by imnavanath** [comment]
@carolinan Can you please check the above PR, will resolve the bottom border issue for Galley item.

**Comment by melchoyce** [comment]
We'll definitely want to update the link styling, but I'm not sure we can remove it entirely if we want to meet AAA criteria — would love some a11y input on whether or not linked gallery images need explicit link styles. If so, we might want to explore something like the "framed" image block style for linked images.

**Comment by pattonwebz** [comment]
For clarity sake I am no _expert_ on these matters but I've done a little reading and it sounded to me like it would be sufficient to have clear _:focus_ styles for images that are linked to themselves but no need to have any kind of framing or border on hover.

**Comment by carolinan** [comment]
I have confirmed that this problem has been solved, there is no visible underline anymore.
The focus style is clear, even if it is not so pretty, and the mouse icon changes when the user hovers over the image.
