### ISSUE TITLE
When the background color is changed, editor text is white on white

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#159]
**Describe the bug**
When the the sites body background color is changed to dark, and the text color is automatically changed to white,
there is text in the editor that is white over a white background.

This is likely because the theme does not yet have support for **editor dark mode**, but testing needs to be done to confirm this.

See the image below, where part of the error message is invisible:

![white](https://user-images.githubusercontent.com/7422055/94399615-02cabe00-0168-11eb-9467-d7af233f9a07.png)

**Comment by jffng** [comment]
It looks like this bug affects block warnings / errors, specifically. The steps for reproducing are:

1. Change the background color of the theme to something dark (so the text color changes to white) via the customizer.
2. Add something that will result in a block validation error, e.g. paste this into the editor `<!-- wp:fake -->`
3. Verify that white text appears on a white background.

**Comment by kjellr** [comment]
Looks like Gutenberg does not provide a color rule for that text. Since it's UI, we wouldn't want to touch it here within the theme. I've opened a PR in the Gutenberg repo to fix it there: https://github.com/WordPress/gutenberg/pull/25713.

**Comment by carolinan** [comment]
But it is not going to help users on older versions of WP.

**Comment by aristath** [comment]
> But it is not going to help users on older versions of WP.

True... but it's not a theme issue. It should be in the editor itself, so I think it's OK if we don't worry about older versions here.

**Comment by kjellr** [comment]
Agreed — an if we style that property here in our theme, we'd risk breaking things for future versions of the Gutenberg UI. I think it makes sense to leave this alone.

**Comment by kjellr** [comment]
I'm going to close for now, but if folks disagree we can always reopen.
