### ISSUE TITLE
Classic: Images are not correctly aligned

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#160]
**Describe the bug**
This bug was sent to me via direct message on slack.
Images in the classic block or created with the classic editor are not centered.

**To Reproduce**
1. Import the **[theme unit test](https://github.com/WPTT/theme-unit-test)**
2. On the front, open the post called **Markup: Image Alignment**
3. See error
![unit-test-image](https://user-images.githubusercontent.com/7422055/94400578-a8326180-0169-11eb-8bbc-04eb6e2930fe.png)

**Comment by nielslange** [comment]
@carolinan I'll look into this issue now. 😀
