### ISSUE TITLE
Remove obsolete block CSS

### ISSUE THREAD

**Issue by scruffian** [WordPress/twentytwentyone#168]
There is a blocks directory inside scss. A lot of this code is from when Gutenberg block appearance in core was much less stable. However much of this code is now obsolete, and should be removed. Some of it could also be submitted to core if it's not there.

For example: https://github.com/Automattic/themes/pull/2503

**Comment by carolinan** [comment]
I also believe most of it can be removed but it was unclear why it was in Seedlet.

We have not started testing or working with individual blocks yet.
This would be updated if any changes need to be made compared to the default block code. 

"Some of it could be submitted to core" I did not understand. Did you mean that we need to create issues for changing blocks in Gutenberg?

**Comment by scruffian** [comment]
> Did you mean that we need to create issues for changing blocks in Gutenberg?

There are some cases where this CSS does actually fix an issue in Gutenberg blocks. In those cases we should keep the CSS temporarily, but also submit it to Gutenberg as a PR so that the fix can live in the block itself. e.g.:

https://github.com/WordPress/gutenberg/pull/25291

**Comment by carolinan** [comment]
Yes, it was the core part that I wanted clarification on.
There is a label for trac, but non for Gutenberg. We should create one when we run in to this, but it is even more likely for the full site editing project.

**Comment by carolinan** [comment]
The action needed here is to go through the block styles here
https://github.com/WordPress/twentytwentyone/tree/trunk/assets/sass/05-blocks

Check if there are any unnecessary duplicate styles _-styles that are already in WordPress core_ where the theme styles are overriding it even though it is not needed.

Optionally check if there any styles here that fixes a problem where an issue should be opened in Gutenberg.

@scruffian Did you have any specific block code in mind that needs to be removed?

**Comment by rolf-yoast** [comment]
As far as I can see the scss included is all theme specific. If @carolinan agrees I would like to close this issue.

**Comment by scruffian** [comment]
An example is the [Pullquote](https://github.com/WordPress/twentytwentyone/blob/trunk/assets/sass/05-blocks/pullquote/_style.scss) block. We have been able to remove a lot of this CSS in other themes, as the base styles from Gutenberg are already doing most of the work.

**Comment by aristath** [comment]
Since the theme needs to be compatible with WP5.3 I don't think there's lots of things we can clean-up here.
When checked against the Gutenberg master branch there are indeed lots of things that can be simplified. However, when checked against Gutenberg v7.0.0, a lot of things are different.
I'd say it's safer to leave them as-is to be sure things will work on older WP versions as well...

**Comment by scruffian** [comment]
I hadn't thought of that. Good point. I think we can close this.
