### ISSUE TITLE
Comment navigation is missing styles 

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#177]
**Describe the bug**
A decision is needed regarding the pagination/ navigation for comments that are split into multiple pages. 

Either a paged pagination that shows the number of pages, or, only links to the next and previous comments pages.

What width would this navigation have, and should it be placed above or below comments, or both?

**Comment by melchoyce** [comment]
Two ideas:

## Navigation and Pagination
<img src="https://user-images.githubusercontent.com/2846578/94846212-c361d300-03ee-11eb-8529-5cb18701c942.png" width="350">
<img src="https://user-images.githubusercontent.com/2846578/94846272-dd9bb100-03ee-11eb-8bab-b116ea6d4fc1.png" width="350">
(Overflow)

## Just Pagination
<img src="https://user-images.githubusercontent.com/2846578/94846336-f86e2580-03ee-11eb-9bf6-4ad59ad780f1.png" width="350">

[Figma](https://www.figma.com/file/OEtsCj8oD8JPVx4OvsS0U2/Twenty-Twenty-One?node-id=7%3A33)

Either way, I'm thinking we'll only show at the bottom of the comment list.
