### ISSUE TITLE
Implement the design for the Pullquote block

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#183]
@melchoyce is this design correct? 
There is one design for a quote, but I can't tell if it is for the quote block or pull quote block?

**This is the style inherited from Seedlet.**

### Front:

![pullquote_front](https://user-images.githubusercontent.com/7422055/94669057-0f3e4a80-0311-11eb-9d3e-65b83f14981a.png)

### Editor spacing problem:

![pq_editor1](https://user-images.githubusercontent.com/7422055/94669252-4876ba80-0311-11eb-9ed2-e6058e63dff4.png)

### Editor left and right aligned for comparison:
![pq_editor2](https://user-images.githubusercontent.com/7422055/94669741-e9657580-0311-11eb-8151-5619faee239f.png)

Sample content:
https://gist.github.com/carolinan/f6528e0839ccd7a2a45fc935722591f5

Code: 
https://github.com/WordPress/twentytwentyone/tree/trunk/assets/sass/05-blocks/pullquote

**Comment by carolinan** [comment]
Pullquotes in footer widgets:

With the current design, the wide pull quote is actually wider than the full width pull quote.
![pq_widget](https://user-images.githubusercontent.com/7422055/94677176-c68c8e80-031c-11eb-95c1-d1f3187f9371.png)

**Comment by melchoyce** [comment]
How would these designs work for quote and pullquote blocks?

![image](https://user-images.githubusercontent.com/2846578/94748377-2865ec00-034f-11eb-823e-d63502c6eb35.png)
[Figma](https://www.figma.com/file/OEtsCj8oD8JPVx4OvsS0U2/Twenty-Twenty-One?node-id=1254%3A0)

-----

![image](https://user-images.githubusercontent.com/2846578/94748466-65ca7980-034f-11eb-9b6e-37ede4059f1f.png)
[Figma](https://www.figma.com/file/OEtsCj8oD8JPVx4OvsS0U2/Twenty-Twenty-One?node-id=1254%3A64)

**Comment by luminuu** [comment]
@melchoyce Do we get the quote icon as SVG? Using the system font, I get this (sneaked the code from Twenty Twenty):

![grafik](https://user-images.githubusercontent.com/7585600/94859945-a56b9100-0435-11eb-8c84-4ca01c88139e.png)

**Comment by melchoyce** [comment]
Let's go with the text quotation for now — we can switch it out later if it ends up looking weird in content. Let's just make sure we use [smart quotes](https://smartquotesforsmartpeople.com/) when adding the character. (There's no visual difference in SF, I think, but there is a visual difference in some of the other fonts in the stack.)

**Comment by melchoyce** [comment]
@luminuu Does this need anything more, or is it good to close?
