### ISSUE TITLE
Implement the design of the quote block

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#184]
Current design: 
![quote_](https://user-images.githubusercontent.com/7422055/94671989-e750e600-0314-11eb-8055-cb744631e61e.png)

In comparison to the pull quote these blocks only have one width and no color settings.
Related files:
https://github.com/WordPress/twentytwentyone/tree/trunk/assets/sass/05-blocks/quote

**Comment by carolinan** [comment]
New design:
Figma:
https://www.figma.com/file/OEtsCj8oD8JPVx4OvsS0U2/Twenty-Twenty-One?node-id=1254%3A0

![94748377-2865ec00-034f-11eb-823e-d63502c6eb35](https://user-images.githubusercontent.com/7422055/94779717-b1b90500-03c7-11eb-9d3c-c778422c1718.png)

**Comment by paaljoachim** [comment]
I am thinking an issue in the Gutenberg github repo would be fitting, so that we can add alignment and the additional color option located in the Pullquote block into the Quote block.

Using Twenty Twenty theme.
Chrome.
Localhost dev site.

Quote Block.
![Quote-Block](https://user-images.githubusercontent.com/5323259/95395159-39d66780-08fe-11eb-9bd4-ed0be04d7abe.png)

Pullquote block.
![Pullquote-Block](https://user-images.githubusercontent.com/5323259/95395394-c84ae900-08fe-11eb-9e6e-be076db78d83.png)

**Comment by carolinan** [comment]
A quote block does not have anything to add the "main" color to. Pull quote has borders by default.

I don't think it is something the editor team should prioritize because of this theme.

**Comment by carolinan** [comment]
The quote symbol itself should use the same symbol as used in the pull quote:

For refrence:
```
&::before {
	color: currentColor;
	content: "\201C";
	display: block;
	font-size: 3rem;
	font-weight: 500;
	line-height: 1;
}
```
https://github.com/WordPress/twentytwentyone/blob/trunk/assets/sass/05-blocks/pullquote/_style.scss#L14

**Comment by paaljoachim** [comment]
Btw
A PR is being worked on:
**Quote: convert to nested blocks**
https://github.com/WordPress/gutenberg/pull/25892

Related to this issue: https://github.com/WordPress/gutenberg/issues/15486

**Comment by JustinyAhin** [comment]
Thanks Carolina. 
Saw it this morning.

I'll send a pr from this branch this afternoon https://github.com/JustinyAhin/twentytwentyone/tree/fix/implement-block-quote-design

**Comment by carolinan** [comment]
> Btw
> A PR is being worked on:
> **Quote: convert to nested blocks**
> [WordPress/gutenberg#25892](https://github.com/WordPress/gutenberg/pull/25892)
> 
> Related to this issue: [WordPress/gutenberg#15486](https://github.com/WordPress/gutenberg/issues/15486)

It is not milestoned for 9.2 and we can't add features after beta 1.

**Comment by paaljoachim** [comment]
Hey Poena. Check this link:
https://github.com/WordPress/gutenberg/projects/48#column-10737345

It is on the Project board WordPress 5.6 Must Haves.

**Comment by carolinan** [comment]
> Hey Poena. Check this link:
> https://github.com/WordPress/gutenberg/projects/48#column-10737345
> 
> It is on the Project board WordPress 5.6 Must Haves.

It is not possible for us to work around issues that are not complete before beta 1, our time line is the same, not "after Gutenberg".
