### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by nielslange** [WordPress/twentytwentyone#188]
**Describe the bug**

⚠️ Not really a bug, but not a _Block pattern ideas_ or _Feature request_ either. Therefore reported as bug.

---

While running linting on SCSS filed, I noticed the following warning:

> Deprecation Warning: 'declaration-property-unit-whitelist' has been deprecated. Instead use 'declaration-property-unit-allowed-list'. See: https://github.com/stylelint/stylelint/blob/13.7.0/lib/rules/declaration-property-unit-whitelist/README.md

This seems to have been addressed already in https://github.com/WordPress-Coding-Standards/stylelint-config-wordpress/commit/0a7c161e48726b892d5c614f1a520b8fe2e3546c. Thanks for @fabiankaegy for pointing this out. We should update that dependency, once there's a new version of `stylelint-config-wordpress` available.

**To Reproduce**

1. Check out the trunk
2. Open the terminal and head over to the forked repo
3. Run `npm run lint:scss`
4. See ~error~ warning

**Expected behavior**

No warning appears.

**Current behavior**

That following warning appears:

> Deprecation Warning: 'declaration-property-unit-whitelist' has been deprecated. Instead use 'declaration-property-unit-allowed-list'. See: https://github.com/stylelint/stylelint/blob/13.7.0/lib/rules/declaration-property-unit-whitelist/README.md

**Comment by luminuu** [comment]
The Stylelint Config WordPress package is set to `"stylelint-config-wordpress": "^17.0.0"` in the `package.json`, which is the most current available release. The commits have been done, but no further release was created.

From my understanding the package needs to be updated with a new release first before we can upgrade it in our package.json file.

**Comment by fabiankaegy** [comment]
@luminuu Yes that is correct. This ticket was only created to keep a record so people who see the warning in their consoles know that it is something the team is aware of and to keep track of updating the dependency once a new release with the fix that nils linked to has been released. :)

**Comment by nielslange** [comment]
@luminuu You are correct and thanks @fabiankaegy for the additional context here. This issue is indeed to have it logged already, but no actions are possible yet.

**Comment by luminuu** [comment]
I have created a ticket at the `stylelint-config-wordpress` repository to raise this issue there: https://github.com/WordPress-Coding-Standards/stylelint-config-wordpress/issues/268

**Comment by aristath** [comment]
Closing this one since it's not directly related to this repository and it will have to be fixed in stylelint-config as mentioned above.
