### ISSUE TITLE
Decrease the line height of h1 titles

### ISSUE THREAD

**Issue by LittleBigThing** [WordPress/twentytwentyone#193]
The line height of the entry- and page-title seems much larger than in the prototype. I think the prototype suggests 105%, which is about 1.09375. Now, it's the default line height for headings (`--global--line-height-heading: 1.3`).

**Comment by pattonwebz** [comment]
Well spotted :) 

As an aside here, and as a matter of personal preference, I think using `1.1` would be a better call than being so hyper specific with long point values like `1.09375`

**Comment by LittleBigThing** [comment]
Yes, 1.1 was looking good. That is about 106%.

![Screenshot 2020-09-30 at 21 30 01](https://user-images.githubusercontent.com/5901923/94734909-3412dc00-036a-11eb-9402-6025886e8a13.png)

I am not sure if that makes a difference code-wise. I was wondering, however, how to implement it. For me, this value looks good over smaller screen sizes (title sizes, only 2 for now), although the font-size might be a bit too large on small screens (see mobile below).

![Screenshot 2020-09-30 at 22 21 24](https://user-images.githubusercontent.com/5901923/94735621-535e3900-036b-11eb-8466-2012b1727d51.png)

(Both images with `line-height: 1.1`)

**Comment by nielslange** [comment]
@LittleBigThing Will you create a PR for this issue or shall I create one?

**Comment by LittleBigThing** [comment]
Ok, I will later today!

**Comment by carolinan** [comment]
Closing this, as the pull request has been merged. Thank you!
