### ISSUE TITLE
Update styles for the RSS block

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#200]
**Describe the bug**

When an RSS widget block is added in the post editor,
the bullet points in the list view are in the wrong position when the block is right aligned or centered aligned.
-Consider removing the bullets all together.

The list view does not look the same in the editor and the front.

**Front, centered:**
![RSS-listview-center-front](https://user-images.githubusercontent.com/7422055/94791688-4e839e80-03d8-11eb-89a1-4cb8fb60f5d3.png)

**Front, right aligned:**
![RSS-listview-right-front](https://user-images.githubusercontent.com/7422055/94791959-a28e8300-03d8-11eb-8389-10323fbc602f.png)

When the grid view is used, the alignments work correctly but there needs to be more spacing between the title,
meta, and content.

![RSS-grid](https://user-images.githubusercontent.com/7422055/94791466-f5b40600-03d7-11eb-94b0-f87b76fdc986.png)

The meta text color, #555555, has a contrast ratio of 5.62:1 against the mint background and does not pass WCAG level AAA for small text.

**Comment by nielslange** [comment]
I'll look into this issue now. 👀
