### ISSUE TITLE
File block: Add an underline to the download link in the editor.

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#201]
**Describe the bug**
At some point, the underline for the download link, `wp-block-file__textlink`, (not the button) was removed from the _editor_.
This needs to be added back so that the editor and front matches.

**Comment by shamikakumar** [comment]
Can I work on this?

**Comment by carolinan** [comment]
@shamikakumar yes :)

**Comment by shamikakumar** [comment]
@carolinan I've added this in  ie-editor.css, is anything else required?

.wp-block-file .wp-block-file__textlink {
	text-decoration: underline;
}

**Comment by carolinan** [comment]
We are updating the documentation for contributing, but you need to make the change to the scss file and compile it to create the updated css files.
https://github.com/WordPress/twentytwentyone/blob/trunk/CONTRIBUTING.md

Each block that needs styling has its own scss file.
The file you need to change is in this directory:
https://github.com/WordPress/twentytwentyone/tree/trunk/assets/sass/05-blocks/file

https://github.com/WordPress/twentytwentyone/blob/trunk/assets/sass/05-blocks/file/_editor.scss

The link needs both a default underline, and a dotted underline on :hover.

**Comment by shamikakumar** [comment]
![](https://user-images.githubusercontent.com/26432407/94837087-6cc9b880-0431-11eb-897b-9812669cd644.png)

@carolinan, the `text-decoration` for the link seems to match with the front, however I noticed the underline seems to be missing for the download button in the editor.

**Comment by shamikakumar** [comment]
I've added this rule to the `_editor.scss` file and compiled it.

```
.wp-block-file__textlink {
	border-bottom: 1px solid var(--global--color-secondary);
	color: var(--global--color-primary);
	text-decoration: none;
}
```

No errors were found on testing.
