### ISSUE TITLE
Calendar widget and calendar block does not mach

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#202]
**Describe the bug**
The calendar widget and the calendar widget block does not match visually.
Some design guidance is needed here. I don't think that the grey background color for the table header fits. 

**Widget**
(The width here is a non issue, it is placed inside the 3 column footer widget area)
![cal-widget](https://user-images.githubusercontent.com/7422055/94796298-dec4e200-03de-11eb-8b4c-2bfe1bfe454b.png)

**Block:**
![cal-block](https://user-images.githubusercontent.com/7422055/94796409-0c119000-03df-11eb-90f3-913c023df9c4.png)

**Comment by melchoyce** [comment]
I'll design a view for both.

**Comment by melchoyce** [comment]
<img src="https://user-images.githubusercontent.com/2846578/95130084-0511b700-072a-11eb-9530-31ab4add49e9.png" width="420" />

[Figma mockup](https://www.figma.com/file/OEtsCj8oD8JPVx4OvsS0U2/Twenty-Twenty-One?node-id=1394%3A202)
