### ISSUE TITLE
Social icons: The first icon is misaligned in the editor.

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#203]
**Describe the bug**
When adding a social icon block in the editor, the first icon is displayed higher up compared to the rest:
_On the front, the icons are positioned correctly._

**Expected behavior**
I expect them to be aligned.

**Screenshots**
![icon-position](https://user-images.githubusercontent.com/7422055/94799835-0cf8f080-03e4-11eb-8d92-9379f28df07b.png)

**Comment by nielslange** [comment]
Happy to grab this one as well, @carolinan. 👨‍💻
