### ISSUE TITLE
The read more block is not contained inside the content area

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#206]
**Describe the bug**
When adding a read more block (.more-link), it is not aligned together with the rest of the content,
instead it is positioned all the way to the left.

Also reported by @LittleBigThing in https://github.com/WordPress/twentytwentyone/issues/129

**To Reproduce**
1. Add a read more block to a post 
2. View a post archive

**Expected behavior**
I expect it the text to be positioned after the content.

**Screenshots**

![readmore](https://user-images.githubusercontent.com/7422055/94803652-e8077c00-03e9-11eb-8652-fb50a3d1d657.png)

**Comment by nielslange** [comment]
Happy to take care of this one. 👨‍💻
