### ISSUE TITLE
Default button style on frontend is broken

### ISSUE THREAD

**Issue by nielslange** [WordPress/twentytwentyone#209]
**Describe the bug**

The default button style on frontend is currently broken.

**To Reproduce**
1. Import the [Theme Unit Test](https://github.com/WPTT/theme-unit-test)
2. Go to the homepage
3. Scroll down to post **Block category: Layout Elements**

**Expected behavior**

The button should look like this as seen in https://github.com/WordPress/twentytwentyone/issues/36#issuecomment-694324773:

<img width="183" alt="Screenshot 2020-10-01 at 19 17 47" src="https://user-images.githubusercontent.com/3323310/94808107-cbd00300-041a-11eb-8dde-b07fc7d8c79f.png">

**Current behavior**

The button looks like this:

<img width="188" alt="Screenshot 2020-10-01 at 19 18 15" src="https://user-images.githubusercontent.com/3323310/94808155-dc807900-041a-11eb-8c45-1ce128db2f6d.png">

**Note**

This bug only affects the frontend styles, not the editor styles. It also does not affect the `:focus` and `:hover` state.

**Comment by carolinan** [comment]
I think it is most likely that the button is inheriting the text color of the group block?
If you create a new button outside the group, it should work correctly?

Update: Yes, I changed the text color the group block and the text color of the button that is placed inside it changed too.

It's because of:
```
.has-background:not(.has-background-background-color) a, .has-background p, .has-background h1, .has-background h2, .has-background h3, .has-background h4, .has-background h5, .has-background h6 {
    color: currentColor;
}

```

**Comment by nielslange** [comment]
Yes, seems to be a caching glitch. When not changing anything other that saving the post again, the button looks fine.
