### ISSUE TITLE
A Cover Template for TT1?

### ISSUE THREAD

**Issue by zakoops** [WordPress/twentytwentyone#218]
Shouldn’t we provide also for a **cover template** (looking quite good in _Twenty Twenty_)?

Mockups from _figma_ file are enclosed for some ideas.

### Take One
![tt1-light-header](https://user-images.githubusercontent.com/36708697/94846293-e55b5580-03ee-11eb-8714-a856e07a2f99.jpg)

### Take Two
![tt1-dark-header](https://user-images.githubusercontent.com/36708697/94846289-e42a2880-03ee-11eb-8345-866d24b9ce39.jpg)

**Comment by melchoyce** [comment]
Hey @zakoops, thanks for the suggestion. This is a fun idea, but it might be better suited for a child theme. Going to close this since we're trying to keep our scope very tight.
