### ISSUE TITLE
Tag Cloud Widget: Update Design

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentytwentyone#221]
Current | Updated Design
------------ | -------------
![image](https://user-images.githubusercontent.com/2846578/94852978-a8945c00-03f8-11eb-97e6-22ad1c1945dc.png) | ![image](https://user-images.githubusercontent.com/2846578/94852927-97e3e600-03f8-11eb-9151-ba5f7b2b91b7.png)

[Figma mockups](https://www.figma.com/file/OEtsCj8oD8JPVx4OvsS0U2/Twenty-Twenty-One?node-id=1272%3A386)

**Comment by kishanjasani** [comment]
@melchoyce It's great but what if I have 100 tags? It will break the design because we do not have options in the tag cloud widget like how many tags we want to display so it may cause design issues. Please put your thoughts here. So I can go further with it.

**Comment by melchoyce** [comment]
Good point, let's leave it as-is. Going to close this issue.
