### ISSUE TITLE
Categories Widget: Update List Design

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentytwentyone#224]
Current | Updated Design
------------ | -------------
![image](https://user-images.githubusercontent.com/2846578/94854864-9667ed00-03fb-11eb-8971-502d138a1963.png) | ![image](https://user-images.githubusercontent.com/2846578/94854885-9ec02800-03fb-11eb-83d2-0a58f9f3f15a.png)

[Figma mockups](https://www.figma.com/file/OEtsCj8oD8JPVx4OvsS0U2/Twenty-Twenty-One?node-id=1272%3A386)

**Comment by carolinan** [comment]
I believe all the widget lists can be addressed at the same time.

**Comment by nielslange** [comment]
Related issues: https://github.com/WordPress/twentytwentyone/issues/222 & https://github.com/WordPress/twentytwentyone/issues/223

**Comment by kishanjasani** [comment]
Yes, all the widget lists can be addressed at the same time. I have created a PR for this one which covers most of the widget style that you have described in Figma.  
The category widget issue will also cover by this PR.

PR Reference: #235

**Comment by Rainbow-Ninja** [comment]
Is this a HacktoberFest issue? If so can I complete this?
