### ISSUE TITLE
Search Widget: Update Design

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentytwentyone#225]
Current | Updated Design
------------ | -------------
![image](https://user-images.githubusercontent.com/2846578/94855143-0f674480-03fc-11eb-8bf6-ddccb075cf08.png) | ![image](https://user-images.githubusercontent.com/2846578/94855277-42113d00-03fc-11eb-8259-138c31d5951b.png)

[Figma mockup](https://www.figma.com/file/OEtsCj8oD8JPVx4OvsS0U2/Twenty-Twenty-One?node-id=1272%3A386)

**Comment by carolinan** [comment]
Does this style change also apply to the other search forms?

**Comment by melchoyce** [comment]
It depends. On the 404 page, for example, I think it makes sense for the search button to be primary, because that's the only action on the page. A search widget that appears in every footer is secondary, or even tertiary, so it doesn't need as much attention. 

Because the space is much smaller in the footer, I tried removing the spacing between the input and button. If that's a pain, though, we can nix that idea and retain the existing spacing between the two elements. Maybe that's better for consistency anyway? 

We should probably have the search block design match the widget design.
