### ISSUE TITLE
Consider adding an inner container inside the header

### ISSUE THREAD

**Issue by briceduclos** [WordPress/twentytwentyone#231]
A possible improvement to the theme would be to add an inner container inside the site header. Adding it would make the markup more consistent with the future FSE version. With FSE, we’ll use a group block (which has an inner container) to create the header.

https://github.com/Automattic/themes/blob/9a6d0378ad15f304fb720d5eb441cc33610d6256/seedlet-blocks/block-templates/index.html#L1-L3

The inner container can help to create a full-width header with background color while keeping the content contained.

**Comment by carolinan** [comment]
After discussing this issue, it has been decided that the issue should be closed.

With the page title removed from the homepage, something resembling a site header can be created with the blocks in the page content: At least on the homepage.
