### ISSUE TITLE
Option to hide the author’s biography

### ISSUE THREAD

**Issue by briceduclos** [WordPress/twentytwentyone#232]
With Twenty Twenty One, the author's biography with its avatar always appears on single posts. Some users might want to hide it.
Twenty Twenty has an option inside the Customizer to hide the biography while Seedlet & Twenty Twenty Nineteen only displays it if the user has entered a description:
`if ( (bool) get_the_author_meta( 'description' ) ) :`

**Comment by melchoyce** [comment]
> Seedlet & Twenty Twenty Nineteen only displays it if the user has entered a description

This approach makes the most sense to me — let's add this in.

**Comment by pattonwebz** [comment]
I can take on the change needed for this then unless @briceduclos wants to take care of it in a PR before me :)

**Comment by carolinan** [comment]
With the profile removed, the post has no other author name, I don't think that is ideal for example when there is more than one author.

Design guidance is needed if we want to place the name else where, in the footer meta information for example.

**Comment by melchoyce** [comment]
I'll mock something up tomorrow 👍

**Comment by melchoyce** [comment]
Two ideas:

![image](https://user-images.githubusercontent.com/2846578/95123808-86644c00-0720-11eb-954d-4d7a58ccc693.png)

**Comment by carolinan** [comment]
👋 @briceduclos what is your WordPress.org username, for the contributors list?

**Comment by briceduclos** [comment]
@carolinan My WordPress.org username is bduclos.
