### ISSUE TITLE
Reconsider bundled images

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentytwentyone#243]
This ticket is to extend the discussion that began in #1. From @melchoyce:

> I’d love to explore including some female impressionists or abstract artists into whatever start content we end up packaging with the theme. In addition to @paaljoachim's above suggestion, we could explore:
> 
> Lee Krasner
> Ethel Sands
> Mary Cassatt
> Berthe Morisot
> Lilla Cabot Perry
> Any work we include will need to be in the public domain, or cc0.
> 
> @carolinan has also mentioned using work from community members, if that’s something any of our community artists would be interested in. If any community artists would be willing to make their work cc0 to be included in the theme, please let us know.

The imagery used today in the theme is of Van Gogh paintings. Images that are bundled with the theme appear in starter content, block patterns, and theme screenshots.

**Comment by melchoyce** [comment]
Having good luck finding Public Domain images of Berthe Morisot's art: https://www.wikiart.org/en/berthe-morisot

Same with Eva Gonzales: https://www.wikiart.org/en/eva-gonzales

Some additional artists that fit the aesthetic but have fewer options:
- Georgina de Albuquerque: https://www.wikiart.org/en/georgina-de-albuquerque
- Nina Arbore: https://www.wikiart.org/en/nina-arbore
- Lilla Cabot Perry: https://www.wikiart.org/en/lilla-cabot-perry (lots of art, but only some fit the aesthetic)

**Comment by kjellr** [comment]
Of these options, I think Berthe Morisot's is the strongest for this theme. Her brushstrokes are wider & softer, which helps the support the calming mood of the theme's palette.

**Comment by melchoyce** [comment]
Great 👍 

Some favorites:
- https://www.wikiart.org/en/berthe-morisot/hanging-the-laundry-out-to-dry
- https://www.wikiart.org/en/berthe-morisot/rosbras-brittany-1867
- https://www.wikiart.org/en/berthe-morisot/portrait-of-marguerite-carre-also-known-as-young-girl-in-a-ball-gown
- https://www.wikiart.org/en/berthe-morisot/in-the-dining-room
- https://www.wikiart.org/en/berthe-morisot/in-the-wheatfield-at-gennevilliers-1875
- https://www.wikiart.org/en/berthe-morisot/eugene-manet-on-the-isle-of-wight
- https://www.wikiart.org/en/berthe-morisot/the-isle-of-wight-1875
- https://www.wikiart.org/en/berthe-morisot/landscape-at-gennevilliers
- https://www.wikiart.org/en/berthe-morisot/the-little-windmill-at-gennevilliers
- https://www.wikiart.org/en/berthe-morisot/dahlias
- https://www.wikiart.org/en/berthe-morisot/tureen-and-apple
- https://www.wikiart.org/en/berthe-morisot/portrait-of-a-young-lady
- https://www.wikiart.org/en/berthe-morisot/summer-s-day-1879
- https://www.wikiart.org/en/berthe-morisot/boats-on-the-seine
- https://www.wikiart.org/en/berthe-morisot/after-luncheon
- https://www.wikiart.org/en/berthe-morisot/child-in-the-rose-garden
- https://www.wikiart.org/en/berthe-morisot/in-the-bois-de-boulogne
- https://www.wikiart.org/en/berthe-morisot/julie-with-pasie-in-the-garden-at-bougival
- https://www.wikiart.org/en/berthe-morisot/playing-in-the-sand
- https://www.wikiart.org/en/berthe-morisot/woman-hanging-out-the-wash
- https://www.wikiart.org/en/berthe-morisot/the-port-of-nice-1882
- https://www.wikiart.org/en/berthe-morisot/the-port-of-nice
- https://www.wikiart.org/en/berthe-morisot/villa-with-orange-trees-nice
- https://www.wikiart.org/en/berthe-morisot/haystacks-at-bougival-1883
- https://www.wikiart.org/en/berthe-morisot/julie-and-eugene-manet-1883

**Comment by carolinan** [comment]
I vaguely remember there being postcards at WCEU with art transformed into or that used Wapuus? 

I did a google search, this is what came up: 
https://dribbble.com/shots/3561019-Wapuu-WordCamp-Europe-2017?utm_source=Clipboard_Shot&utm_campaign=jancavan&utm_content=Wapuu%20WordCamp%20Europe%202017&utm_medium=Social_Share

I think if any of the cards are compatible with GPL and the year was removed, that would be really cool to use...

There it is, the mona lisa ;)
https://a8cdesignvoice.wordpress.com/2017/06/29/swag-pour-wordcamp-europe-reussite-dun-travail-dequipe-a-distance/

**Comment by melchoyce** [comment]
I've taken a stab at replacing all the images with paintings from Morisot:

![Screenshot_2020-10-15 Block Patterns – Twenty Twenty One](https://user-images.githubusercontent.com/2846578/96185173-86760000-0f07-11eb-8ccb-5d8a095bdeb7.jpg)
https://2021.wordpress.net/block-patterns/

I've uploaded all the images (compressed) here: https://cloudup.com/c_MycV-gMCT

Image sources:
- https://www.wikiart.org/en/berthe-morisot/playing-in-the-sand
- https://www.wikiart.org/en/berthe-morisot/roses-tremieres-hollyhocks-1884
- https://www.wikiart.org/en/berthe-morisot/young-woman-in-mauve
- https://www.wikiart.org/en/berthe-morisot/in-the-bois-de-boulogne
- https://www.wikiart.org/en/berthe-morisot/daffodils
- https://www.wikiart.org/en/berthe-morisot/self-portrait-1885
- https://www.wikiart.org/en/berthe-morisot/the-garden-at-bougival-1884
- https://www.wikiart.org/en/berthe-morisot/villa-with-orange-trees-nice
- https://www.wikiart.org/en/berthe-morisot/roses-tremieres-hollyhocks-1884
- https://www.wikiart.org/en/berthe-morisot/in-the-bois-de-boulogne
- https://www.wikiart.org/en/berthe-morisot/reading
