### ISSUE TITLE
Site title and tagline are removed completely when display option unchecked

### ISSUE THREAD

**Issue by LittleBigThing** [WordPress/twentytwentyone#251]
When the option to display the site title and tagline is unchecked in the Customizer, the site branding is removed completely. The template part is [not included](https://github.com/WordPress/twentytwentyone/blob/691ae72442f425beceec347088ea4c2c3d6f5474/template-parts/header/site-branding.php#L10) anymore, even when there is no custom logo added.

Shouldn't we rather make them visually hidden for accessibility (and search engines), similar to how we do it for screen reader texts?

**Comment by carolinan** [comment]
The site title is already used as the document title, but yes there should be an H1 heading on the archive pages even if the site title is hidden.

Scratch that, the archive and search heading is already an H1, so it would only be for the front page.
