### ISSUE TITLE
Numbers break in Calendar widget

### ISSUE THREAD

**Issue by TeBenachi** [WordPress/twentytwentyone#253]
In the calendar footer widget, the numbers seem to break on the mid size screen. 
I’ve tested on Firefox with the screen size somewhere between 822px to 1160px. 

<img width="839" alt="Screen Shot 2020-10-03 at 6 16 27 AM" src="https://user-images.githubusercontent.com/30734209/94989451-ea311e00-0542-11eb-9a98-6d41b1e4d11f.png">

**Comment by omnisite** [comment]
Seems to be because of "word-break: break-all;" on the table td. You could change that for the calender widget class. But also mind that the .widget-area in the footer goes out of the container (in Chrome) from 822px up to 910px. So between those resolutions, the grid of 3 should also be addressed.

**Comment by carolinan** [comment]
Hi, we are waiting for the final design of the calendars, this can be addressed with the updated design.

**Comment by melchoyce** [comment]
I think the numbers might have to break, given the space constraints. A lower line-height could help here.

**Comment by melchoyce** [comment]
Took another look at this, since the calendar design was merged. There's enough space to remove the `word-break: break-all;` for the widget & block, IMO, instead of letting the numbers wrap.
