### ISSUE TITLE
Add clearing after the last block in the widget area

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#271]
**Describe the bug**
If the last item in the widget area has a left or right alignment, it overlaps the next element.
Admittedly, I only tested with image and the social icon block. The quick and easy solution would be to add clear: both to the site info.

![widget-clear](https://user-images.githubusercontent.com/7422055/95077504-e6082a80-0713-11eb-94db-ee6c5909254f.png)

**To Reproduce**
1. Enable Gutenberg 9.1. Add a block in the widget screen and set the alignment to left or right.
2. View the front.
3. You may need to reduce the window width to see the problem.

**Expected behavior**
I expect the items to not overlap.

**Comment by JustinyAhin** [comment]
Applying `clear: both` to the last children of the widget area doesn't fix the issue.

Instead, doing so on the widget area itself solve this. However, it added bottom spacing between the children and the separator that is larger than the normal. This would need broader exploration.

PR coming in a couple of minutes.
