### ISSUE TITLE
Moving the Post/page title to the top mid bar area.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/twentytwentyone#280]
**Is your feature request related to a problem? Please describe.**
In Full Site Editing there are explorations going on in relation to moving the post/page title to the top bar mid area.

It would be nice to get the post/page title to the top bar for Gutenberg plugin version 9.2. Have the new Post/Page Title block in place. Making it possible to add a Cover Block and the Post/Page title block into it. 

As the user would then finally be able to not have the page title in the content but can add it back if they choose to.

There are a few different FSE issues in relation to the above.

**Comment by melchoyce** [comment]
Thanks @paaljoachim, can you make a new issue for this after beta 1, when we open up a new repo for the FSE-supported version of Twenty Twenty-One?

**Comment by paaljoachim** [comment]
Hey Mel @melchoyce 

The more I think about this the more I also realize that we can not move the page/post title to the top mid bar (for the Post Editor) before this has landed in Full Site Editing (Site Editor). So yes, I will bring it up again after beta 1 is in place and FSE has also made the change.

Btw
It would be nice to add somekind of message to p2 saying that there will be two versions of Twenty Twenty-One. One that does not include Full Site Editing and another version that does. Off the bat so to speak it seems a bit confusing having two default themes. Kinda like Twenty Twenty-One and Twenty Twenty-one with FSE.

**Comment by melchoyce** [comment]
We included the information in the kick-off post: https://make.wordpress.org/core/2020/09/23/introducing-twenty-twenty-one/
