### ISSUE TITLE
Update design of floated pullquotes

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentytwentyone#282]
Moving this over from #229:

> Do we want to limit the width of the left and right aligned pullquote to 50%? When the content is long enough, the quotes are no longer aligned but looks like they are normal width without alignments.
>
> In the editor, left and right aligned pull quotes needs spacing to the right and left of the block respectively.
>
> It is less visible on the right:

![image](https://user-images.githubusercontent.com/2846578/95134058-3a210800-0730-11eb-905d-2a59ce7e741f.png)

**Comment by melchoyce** [comment]
If we wanted to get fancy and do outdented pullquotes, using alignleft/right:

![image](https://user-images.githubusercontent.com/2846578/95265055-6b680980-07fe-11eb-819c-2e1a8c930df8.png)

**Comment by carolinan** [comment]
This is one of the designs that look great but caused a lot of CSS problems and delays for Twenty Twenty.

I would rather not add more alignmet additions because adding more :not styles to the base widths causes problems for other blocks including third party.

**Comment by melchoyce** [comment]
Yikes, nevermind — we can close this when #295 merges, then.
