### ISSUE TITLE
Including developer documentation

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#3]
One of the recurring comments about Twenty Twenty is that it is difficult for theme developers to make changes to,
and that it can be difficult to use it as a starter theme.

Can we make it easier for theme developers to work with the theme by creating more detailed documentation
about any custom functionality (filters, classes, functions etc)?
-More than the inline code comments and the _contributing_.md file.

The main questions that I see is:

- Is there enough time

- Is it something we will be able to maintain in the future

- Where would the documentation live

- How could we best work together with the docs team (without causing them extra work)

**Comment by melchoyce** [comment]
I think it makes sense to have as much documentation inline as we can. It would be great for this to be a learning tool for anyone new to WordPress development, so as much we can do to add in context and help within files, the better, IMO.
