### ISSUE TITLE
Navigation Menu: Remove extra right margin on dropdown items

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentytwentyone#302]
When a navigation menu item has a dropdown, there's extra space added for the + sign, in addition to the `margin-right` on the list item:

![image](https://user-images.githubusercontent.com/2846578/95268203-d6b4da00-0804-11eb-8e45-a10842fe27d0.png)

Could we remove that margin for all navigation items with dropdowns (`.menu-item-has-children`), so the spacing feels a little more even?

![image](https://user-images.githubusercontent.com/2846578/95268349-2a272800-0805-11eb-83dc-b2480630fa3f.png)

**Comment by aristath** [comment]
Assigning this one to myself, there are quite a few things that need to be fixed here.
