### ISSUE TITLE
Mobile/responsive site title spans half the width when there is no menu

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#307]
**Describe the bug**
The primary navigation is optional. When there is no menu, and the browser window is reduced to the size where the button would show, the site title and tagline is still spanning about half the page, instead of the full width.

**To Reproduce**
1. View a page with no menu but with a site title
2. Reduce the window width

**Expected behavior**
I expected the text to span the full width

**Screenshots**

![responsive](https://user-images.githubusercontent.com/7422055/95285955-558c3000-0862-11eb-84b9-2ba3b0f9d7f9.png)

**Comment by glauberm** [comment]
#340
