### ISSUE TITLE
Align the arrow icons

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#308]
**Describe the bug**
The arrow icons in the navigation are not vertically aligned.

This issue was taken out of #303:
`Can you pull the left arrow up 1px and push the right arrow down 1px?`

![95272077-74aca280-080d-11eb-8e20-4ab63ce41f25](https://user-images.githubusercontent.com/7422055/95287800-288e4c00-0867-11eb-8371-bfd47dd47062.png)

**Comment by glauberm** [comment]
#339
