### ISSUE TITLE
Hide the page title on the front page

### ISSUE THREAD

**Issue by LittleBigThing** [WordPress/twentytwentyone#314]
In general, default themes are designed to be as little opinionated as possible. Creating more unique websites is becoming easier now having several blocks and more extensive possibilities to style them. But this freedom is still more or less limited to the ‘post content‘. We have not yet a lot of styling possibilities for the page title.

Therefore, could we consider add an option to the Customizer to hide the `.entry-header` **for the front page only**? We should consider whether

1. we hide it visually to have an `h1` or
2. don‘t display it and make the `.site-title` an `h1` on the front page as well (it is now on the home page only).

This would give the user more freedom for designing a unique front page with blocks. See some quick examples below.

![Screenshot 2020-10-07 at 09 55 02](https://user-images.githubusercontent.com/5901923/95304476-fab80000-0884-11eb-91ba-7745a3d99528.jpg)

![Screenshot 2020-10-07 at 09 41 52](https://user-images.githubusercontent.com/5901923/95304505-03103b00-0885-11eb-8da9-f925461d222e.jpg)

![Screenshot 2020-10-07 at 09 48 40](https://user-images.githubusercontent.com/5901923/95304518-086d8580-0885-11eb-9445-32040f611ab4.jpg)

I realise that it is rather easy to add custom CSS to hide it (which I end up doing for several websites I create), but that can ‘break’ the page structure if done incorrectly or it is simply not ‘just something everyone is able to do’.

**Comment by carolinan** [comment]
Is this the same as https://github.com/WordPress/twentytwentyone/issues/247 ?
I mean I thought this was decided on already, but it seems a PR was closed instead of implemented.
Seems to be some confusion between front page and home.

**Comment by LittleBigThing** [comment]
It's not completely the same (I suggest it optionally here) and I probably missed the decision as well, sorry.

**Comment by carolinan** [comment]
I agree that it is easier to make different designs without the title, for example, there is no header image option and it would be possible to replicate that without the title being there.

**Comment by LittleBigThing** [comment]
Yes, and a header image would still be less flexible.

**Comment by carolinan** [comment]
@melchoyce Do we understand correctly that you prefer that the page title is not visible when a static page is set as the homepage? 

Adding a customizer option is an easy solution. Removing the title and changing the site title back to H1 is easier.

**Comment by LittleBigThing** [comment]
I have noticed that if we remove the whole `header.entry-header` element from the HTML, the featured image (if set) is ‘gone‘ as well since it is in that same container. IMHO, it makes sense to hide the featured image as well if the goal is to create a more unique front page with blocks, but it is confusing if a featured image is set.

If we would only remove the `h1.entry-title`, we need some additional CSS to remove the bottom border of the `header`.

**Comment by melchoyce** [comment]
> Do we understand correctly that you prefer that the page title is not visible when a static page is set as the homepage?

Correct! I'd rather we do this by default, than add a new setting for it.

**Comment by carolinan** [comment]
Yeah the featured image will no longer be as wide if we place it inside the content section for example.

**Comment by carolinan** [comment]
There is no way to exclude the featured image without a page template or customizer option.
The best way is for the user to not add one to that page.

**Comment by carolinan** [comment]
So the steps would be something like

CSS: Remove the entry headers bottom border if a static page is used on the front page

In template-parts\content\content-page.php:
An if statement that checks if the page is the current front page, 
to make sure that _template-parts/header/entry-header_ is not included on the front page.

Test with and without featured image

**Comment by LittleBigThing** [comment]
> Correct! I'd rather we do this by default, than add a new setting for it.

@melchoyce I was just thinking that it can be confusing having the page title in the editor and then not on the frontend. If it is an option, it has to be chosen explicitly.

@carolinan ~~I am happy to create a PR.~~ Ah ok, assigned already. :-)

**Comment by melchoyce** [comment]
FWIW, I don't think it's any more confusing than an aside post format, which can take a post title but doesn't display it. I still think we should hide the homepage title by default.
