### ISSUE TITLE
Add search icon

### ISSUE THREAD

**Issue by nielslange** [WordPress/twentytwentyone#315]
**Is your feature request related to a problem? Please describe.**

Not necessarily related to a problem, but it would be nice to have a search icon in the primary menu, similar to seen at the Twenty Twenty theme.

**Describe the solution you'd like**

Being able to toggle on/off a search icon in the primary menu.

**Describe alternatives you've considered**

n/a

**Additional context**

Make searching contact as easy and accessible as possible.

**Comment by melchoyce** [comment]
[We chatted about this in today's bug scrub](https://wordpress.slack.com/archives/C02RP4VMP/p1602260048327500), and decided not to include this feature. We're trying to avoid adding more customizer settings, and folks can add a search to the footer using widgets. The search block also allows for more places to include a search feature.

**Comment by nielslange** [comment]
> [We chatted about this in today's bug scrub](https://wordpress.slack.com/archives/C02RP4VMP/p1602260048327500), and decided not to include this feature. We're trying to avoid adding more customizer settings, and folks can add a search to the footer using widgets. The search block also allows for more places to include a search feature.

Thanks for your explanation, @melchoyce. Given the fact that the Twenty Twenty-One theme should fulfill the WCAG AAA standards, I thought the theme should be accessible as possible and having a search option in a prominent place improves accessibility in my opinion. That said, I'm fine with closing this issue and going with the widget-based approach.
