### ISSUE TITLE
Remove the `twenty_twenty_one_posted_by` function

### ISSUE THREAD

**Issue by aristath** [WordPress/twentytwentyone#318]
Spawned from #312 

The `twenty_twenty_one_posted_by` is not used anywhere and can be removed

**Comment by carolinan** [comment]
It is used in https://github.com/WordPress/twentytwentyone/pull/294 which is still waiting review

**Comment by aristath** [comment]
LOL ok, I wasn't expecting the function to be in one branch and used in another.

Closing this one, thank you for your vigilance!
