### ISSUE TITLE
Remove the `twenty_twenty_one_get_user_avatar_markup` function

### ISSUE THREAD

**Issue by aristath** [WordPress/twentytwentyone#319]
Spawned from #312

The `twenty_twenty_one_get_user_avatar_markup` function is not used anywhere and can be removed.

**Comment by hareesh-pillai** [comment]
Hi @aristath,
 
Looks like there's a typo there. 
We check for the existense of `twenty_twenty_one_comment_avatar` function, while a different function (`twenty_twenty_one_get_user_avatar_markup`) is defined below that.  

I don't see both these functions used anywhere and can be removed.
