### ISSUE TITLE
Consider adding a hook inside the header

### ISSUE THREAD

**Issue by briceduclos** [WordPress/twentytwentyone#320]
It would be nice to have a hook just before the end of the site header so developers can add additional elements (for example, the [Seedlet theme](https://github.com/Automattic/themes/blob/master/seedlet/header.php#L68) adds a WooCommerce cart and a socials menu inside the header):
```
<?php do_action( 'twentytwentyone_header' );
</header><!-- #masthead -->.
```

**Comment by carolinan** [comment]
During Friday's bug scrub it was decided that the theme would not have extra hooks.
