### ISSUE TITLE
Adjust footer logo size

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#322]
**Describe the bug**
The footer logo is too large and needs some CSS to constrain the size as in the header area.

This bug was picked from https://github.com/WordPress/twentytwentyone/issues/57

**Comment by ryelle** [comment]
I believe this was also fixed in https://github.com/WordPress/twentytwentyone/pull/244, are you still seeing the issue on trunk?

**Comment by carolinan** [comment]
No you are right, it looks much better now.
