### ISSUE TITLE
Test the updated search block

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#324]
This test requires Gutenberg 9.1 or newer to be installed.

Several new options were added to the search block in Gutenberg 9.0, https://github.com/WordPress/gutenberg/pull/24666

The current styles have only been tested with and adapted to WordPress 5.5, without the plugin.

What we are testing is:
Does the button look correct in the different positions and styles (icon)
Does the editor and front match?

If problems are found during testing, new bug issues need to be opened.

**Comment by GuidoOffermans** [comment]
tested.
made new issue: https://github.com/WordPress/twentytwentyone/issues/368.
But this needs to be fixed in gutenberg.
