### ISSUE TITLE
Create a separate file for editor font sizes

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#328]
**Describe the bug**
Updated issue description:

The editor font sizes, the named font sizes like large and gigantic, added by the theme support here:
https://github.com/WordPress/twentytwentyone/blob/trunk/functions.php#L123
are theme specific features, and placing them in their own file makes it easier to locate them and 
work with them if the theme support is updated to remove or add font sizes.

If possible, use one file to be built into both front end styles _and_ the editor styles.
The reason for this is to reduce the number of files with duplicate content.

Remove unused or incorrectly named font sizes:
```
.is-tiny-text,
.has-tiny-font-size 
```

Related files:
https://github.com/WordPress/twentytwentyone/blob/trunk/assets/sass/05-blocks/utilities/_editor.scss

https://github.com/WordPress/twentytwentyone/blob/trunk/assets/sass/05-blocks/utilities/_style.scss

List of the font sizes:
https://github.com/WordPress/twentytwentyone/blob/trunk/functions.php#L123

**Comment by kjellr** [comment]
> Remove unused or incorrectly named font sizes:

I'm not sure, but I _think_ the reason those are in there is so that if someone switches to this theme from one that used a slightly different font sizing name structure, their font sizes will be use the theme's rough equivalents.

**Comment by carolinan** [comment]
Is tiny one of the default font sizes? Hmm.
