### ISSUE TITLE
Avatar overlaps user name

### ISSUE THREAD

**Issue by TeBenachi** [WordPress/twentytwentyone#330]
In the comment section, the avatar seems to overlap the username on smaller screens. 

<img width="350" alt="Screen Shot 2020-10-07 at 9 14 45 AM" src="https://user-images.githubusercontent.com/30734209/95336472-b9bced00-087e-11eb-887b-11f879ea19b0.png">

**Comment by glauberm** [comment]
Is this issue up for grabs? :)

**Comment by melchoyce** [comment]
Yup!
