### ISSUE TITLE
I18N: Read more link might be hard to translate correctly

### ISSUE THREAD

**Issue by ryelle** [WordPress/twentytwentyone#332]
The "read more" link is built up out of parts to visibly show "Read more", with screen reader text identifying the post, "about [post name]". The way this string is built, each part is translated, but 'read more' and 'about' are translated separately. I think this would create an issue when translating the strings, if the word order is different than English — but I'm not sure, so I wanted to flag this as a possible issue.

https://github.com/WordPress/twentytwentyone/blob/dfd6b2bad2c3f87fd11a47a0482c0ecfd85c1a70/inc/template-functions.php#L141-L145

```
<a class="more-link" href="#">Read more <span class="screen-reader-text">about [Post Name]</span></a>
```

**Comment by carolinan** [comment]
What you bring up makes sense, and why I prefer _continue reading_.

Sorry for all the edits, I am more tired than I'd like =D

**Comment by ryelle** [comment]
This was discussed in [today's bug scrub](https://wordpress.slack.com/archives/C02RP4VMP/p1602261216351500) and it sounds like the best way forward will be to update this string so that it becomes:

```html
<a class="more-link" href="#">Continue reading <span class="screen-reader-text">[Post Name]</span></a>
```

**Comment by sabernhardt** [comment]
Both [Twenty Seventeen](https://themes.trac.wordpress.org/browser/twentyseventeen/2.4/template-parts/post/content.php#L54) and [Twenty Nineteen](https://themes.trac.wordpress.org/browser/twentynineteen/1.7/template-parts/content/content.php#L32) have
`Continue reading<span class="screen-reader-text"> "%s"</span>`

(space inside the span tag)

**Comment by ryelle** [comment]
>Both Twenty Seventeen and Twenty Nineteen have
> `Continue reading<span class="screen-reader-text"> "%s"</span>`
>
> (space inside the span tag)

Apparently the only reason that works is because the post title is wrapped in quotes — NVDA is still trying to read `Continue Reading"Post Name"`. The space before the `span` doesn't seem to be adding any visual awkwardness, so I think it's fine to keep it (and I have, in #433).
