### ISSUE TITLE
A heading level is skipped if comments are allowed but no comments are added yet

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#333]
**Describe the bug**
If a page or post allows comments, but no comments have been added yet, the H2 heading level is skipped.

Headings:
H1 -post/page title
H3  -Leave a reply

(H2, widget title)

**To Reproduce**
1. Create a new page or post 
2. Make sure that comments are enabled.
3. View the front, inspect and and check the heading levels.

**Expected behavior**
Heading levels must not be skipped.

**Comment by glauberm** [comment]
Would #335 work to fix this bug?
