### ISSUE TITLE
CSS filters applied to .custom-background are transferred to the page content instead of being retained by the background itself

### ISSUE THREAD

**Issue by giorgioriccardi** [WordPress/twentytwentyone#338]
**Describe the bug**
When trying to apply css filters to the site image background `.custom-background` the changes are transferred to the page content elements.

**To Reproduce**
1. Set Homepage to show all posts
2. In Customizer -> Background Image select an image
3. Set the Prest -> Fill Screen
4. Add custom css
```
.custom-background {
	filter: blur(2px);
}
```
5. See outcome

**Expected behaviour**
The image background should blur a little bit, leaving the content on top of it sharp and neat, not the other way around.

**Screenshots**
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/3901192/95382907-3790f080-089f-11eb-9fc4-92ff98b54226.png">

**Editor version:**
- WordPress version: WordPress 5.6-alpha-49096 running Twenty Twenty-One theme.
- Gutenberg plugin is installed
- Gutenberg version is: [9.1.1]

**Desktop:**
 - OS: Catalina 10.15.7
 - Browser FireFox
 - Version 81.0.1 (64-bit)

**Comment by carolinan** [comment]
Is this an issue for this particular theme or any theme (untested)? 

Do you have any examples of themes that already solves this?

Either way adding custom styles is very much an edge case and there are many other issues with default settings that need testing and solutions first.

**Comment by giorgioriccardi** [comment]
@carolinan no, it is not only this theme, the same problem occurs with TwentyTwenty.

The only theme that does not have the issue is TwentySeventeen but just because the `.custom-header-media` actually has its own html container `<div><span><img />` therefore the css filter can be easily applied to the image without being transferred to the content elements.

Both 2020 and 2021 themes are just setting the `.custom-background` as CSS `background-image` and doing so we can not intercept via css the image that has been already parsed/rendered by the css itself.

Before closing this issue (very low priority) I'm attaching the 2017 theme outcome just as a reference.

Thank you!

<img width="1341" alt="image" src="https://user-images.githubusercontent.com/3901192/95487922-ca866500-0949-11eb-85af-76ea56678f63.png">
