### ISSUE TITLE
Test the updated list block

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#342]
**Describe the bug**
In comparison to WordPress 5.5, the list block in Gutenberg now has background and text color options.

The block needs to be tested with Gutenberg installed and with the themes color options.
We also need to check if any extra padding is needed when there is a background color.

**Comment by SResok** [comment]
Acceptance
![image](https://user-images.githubusercontent.com/20287474/95463146-b86feb00-0978-11eb-9e55-07ad0b13aaa3.png)
Tested with Gutenberg `9.1.1`

Done, no problems found!
