### ISSUE TITLE
Update .gitignore file  with some files

### ISSUE THREAD

**Issue by kishanjasani** [WordPress/twentytwentyone#343]
Please add the phpcs.xml.dist file to it. So all users can modify it's setting like they can change the executable path of phpcs.

Also add code editor files that are auto-generated by the Visual Studio Code, idea, and more.

**Comment by aristath** [comment]
We can't ignore the phpcs.xml.dist file, it needs to be in the repo because that's what we use to run tests. It's the standard phpcs config that all themes use.

As for code editor files, I don't know what each code editor adds.
If you submit a PR with some of these files we can add them :+1:

**Comment by kishanjasani** [comment]
Sure I will remove the phpcs.xml.dist file from gitignore file. And some of the code editor file which should be ignored.
