### ISSUE TITLE
The site title on the blog page is not a link when a static homepage is set

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#358]
**Describe the bug**
When a static page is set as the homepage, and a page is selected as the blog, the site title is not a link on the blog page

**To Reproduce**
1. Go to the customizer or the homepage setting and set pages to the homepage and blog.
2. Open the blog page, and see that the site title is not a link.

**Expected behavior**
The blog page is not the homepage so there needs to be a link.

**Comment by LittleBigThing** [comment]
@carolinan: Can I fix this by correcting this as well? After fixing #314, we now don't have an `h1` title on the front page. I would add that here, make the site title an unlinked `h1` tag on the front page.

A smaller issue is that now we have an empty header on the front page if there is no featured image.
