### ISSUE TITLE
Left aligned pull quote has a left aligned citation

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#359]
**Describe the bug**

The pull quote has a centered citation for all widths and alignments, except the left alignment.
For the left alignment, the citation is centered in the editor, but left aligned on the front.

**To Reproduce**
1. Add a pull quote to a post or page
2. Add a text quote and citation to the block. 
3. See the position of the citation.
4. Save and view the citation on the front.

**Expected behavior**
For consistency and for the editor to match the front,
the citation needs to be centered also on the front.

**Comment by carolinan** [comment]
Admittedly, I think the left aligned citation looks better for the left aligned block. 
But it is inconsistent with all the other citations and with the editor. Changing one text to center is a smaller and faster change.

**Comment by melchoyce** [comment]
Screenshot:

![image](https://user-images.githubusercontent.com/2846578/95478307-5fdc2600-0957-11eb-8c29-bec46d4e2f6e.png)

The quote icon and quotation should also be centered, not just the citation. The only difference when something is `alignleft` or `alignright` should be the positioning of the block.

**Comment by melchoyce** [comment]
The "after" should look like this:

![image](https://user-images.githubusercontent.com/2846578/95478450-88642000-0957-11eb-9797-5eaa3cf9d5ba.png)
