### ISSUE TITLE
Implement the design for forms, inputs and buttons

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#36]
Implement the designs for forms/inputs/buttons.

- [x] Buttons block -filled
- [x] Buttons block -outlined

- [x] HTML buttons  (including disabled state)
- [x] Input elements
- [x]  Select lists (including blocks)

- [x] Tested standard form elements as well as widgets and blocks.
- [x] Tested focus and hover states.

**Comment by carolinan** [comment]
Currently testing the color changes/contrasts when the body background is changed, could use some more eyes.

Should the border that is used on the default button block be used when the user changes the button color?

**Comment by nielslange** [comment]
@carolinan & @melchoyce I'm diving into the `:hover` and `:focus` states now.

**Comment by carolinan** [comment]
Button blocks with custom styles (radius, colors,) still needs to be tested more, but lets close this and open individual issues for any new problems that we run into.
