### ISSUE TITLE
Plus and minus icon color does not change when the body background color is changed.

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#360]
**Describe the bug**

When the body background color is changed, the plus and minus icons in the menu does not change color.
The becomes a problem when the icon is dark over dark backgrounds.

**To Reproduce**
1. Set up a menu with sub menu items.
2. Change the body background color.
3. See that the text color changes, but that the icons do not.

**Expected behavior**
I expect them to change color so that the color contrast remains high enough.
(The color should be white when the text color is set to white by the color option.)

**Screenshots**
![The icon for the sub menu toggle does not have enough contrast against the background](https://user-images.githubusercontent.com/7422055/95458482-822f6d00-0972-11eb-97bf-96e709c30a07.png)

**Comment by aristath** [comment]
Assigning this one to myself, I suspect it's gonna get a little messy.
