### ISSUE TITLE
Search-block errors when selecting use with Icon. 

### ISSUE THREAD

**Issue by GuidoOffermans** [WordPress/twentytwentyone#364]
**Describe the bug**
When using the `Use button with icon` setting of the search-block it throws an error.
See images below.

**To Reproduce**
1. Go to 'edit a post'.
2. Add the search-block.
3. Select the `use button with icon`.
4. Click update.
5. go to the front end.
6. there you'll see the error.

**Expected behavior**

**Screenshots**
![Screenshot 2020-10-08 at 15 05 13](https://user-images.githubusercontent.com/49080649/95462463-d4bf5800-0977-11eb-93d7-c8418881e47a.png)
![Screenshot 2020-10-08 at 15 00 53](https://user-images.githubusercontent.com/49080649/95462470-d7ba4880-0977-11eb-8148-d71bcfbfe643.png)

**Editor version (please complete the following information):**
- WordPress version: [ 5.6]
-  Gutenberg plugin  [ 9.9.1 ]

**Desktop (please complete the following information):**
 - OS: [ iOS]
 - Browser [ chrome ]
 - Version [85.0.4183.121 ]

**Additional context**

**Comment by carolinan** [comment]
Interesting. I am not able to reproduce this PHP notice with the latest master from the Gutenberg repository
but I can reproduce it with the released plugin version 9.1.1.

I did not check all the recently merged pull requests in the Gutenberg repo but I think we can consider the notice fixed, or do we need to confirm with more testing?

In my test, the search icon in the editor is too small, but looks OK on the front.

**Comment by ryelle** [comment]
Looks like this was an issue in Gutenberg, and was fixed 3 days ago — so it hasn't been released into the plugin yet. https://github.com/WordPress/gutenberg/issues/25812

**Comment by GuidoOffermans** [comment]
Then I'll close this issue and write a new one for the wrong styling. Thanks for your help :D
