### ISSUE TITLE
Gallery caption is not centered

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#369]
**Describe the bug**
When a caption is added to a gallery block  (not to individual images but the block),
it is centered in the editor but left aligned on the front.

(Changing the alignment of the block does not change the alignment of the caption)

This is a known Gutenberg issue but does not have a pull request:
https://github.com/WordPress/gutenberg/issues/22188

**To Reproduce**
1. Add a gallery block to a post or page
2. Add a caption
3. Save and view the front
4. Note that the position of the caption in the gallery and the editor do not match

**Expected behavior**
I expect the position to be the same in the editor and the front.

**Editor version (please complete the following information):**
Tested with Gutenberg 9.1.1 and without Gutenberg on WordPress 5.5.2 alpha

**Comment by kishanjasani** [comment]
This PR will resolve this issue: https://github.com/WordPress/gutenberg/pull/25962

**Comment by kishanjasani** [comment]
Can we close this issue? The above PR is merged in Gutenberg and will resolve this issue.

**Comment by aristath** [comment]
Fixed in Gutenberg, closing 👍
