### ISSUE TITLE
Desktop Menu: It's not always possible to access the submenus on hover. 

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentytwentyone#375]
When hovering over top-level parent menu items, it's sometimes difficult to access the children: 

![hover](https://user-images.githubusercontent.com/1202812/95505109-d12dd000-097b-11eb-8677-577a173f34d7.gif)

Tested in Safari v14.0.
MacOS 10.15.6.

**Comment by carolinan** [comment]
This is probably because we had to move the sub menu down to make the full focus outline of the parent visible.

**Comment by carolinan** [comment]
I am able to reproduce this on Chrome on win10.

**Comment by aristath** [comment]
Assigned this one to myself, it is caused by a 3px offset added in https://github.com/WordPress/twentytwentyone/pull/329
