### ISSUE TITLE
RSS Widget: Icon is misaligned

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentytwentyone#376]
The RSS widget icon is misaligned. This should either be properly aligned, or just hidden. 

<img width="354" alt="Screen Shot 2020-10-08 at 3 38 18 PM" src="https://user-images.githubusercontent.com/1202812/95505766-ea834c00-097c-11eb-8db5-5efe818ac581.png">

(Personally, I'd aim for removing it, since it's not retina-friendly anyway.)

**Comment by melchoyce** [comment]
Yeah it's weird that WordPress includes this icon by default... it's very Web 2.0. Can we remove?

**Comment by rolf-yoast** [comment]
Acceptance 👍
