### ISSUE TITLE
Test the primary navigation menu on iPhone

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#384]
There was a report in one of the previous pull requests that the menu buttons -neither the sub menu toggles or the toggle for the responsive menu, works on iPhone and that the menus do not expand.

**Comment by ingereck** [comment]
I have this issue on an iPhone 6 with the Official AMP plugin installed and set on _standard_. Setting it back to _transition_  and clearing NGINX fastCGI and browser cache, I can expand the menu again. 

Here is the AMP error info. 

Error code: DISALLOWED_TAG
Invalid script: primary-navigation.js
src: .../themes/twentytwentyone/assets/js)
ID: twenty-twenty-one-primary-navigation-script-js
Element name: script
Parent element: body

**Comment by carolinan** [comment]
@ingereck Thank you. AMP is a separate issue, and it will be worked on from the plugin side:
https://github.com/ampproject/amp-wp/issues/5423

**Comment by kjellr** [comment]
I can't reproduce — the menu opens, closes, and selects items just fine in my testing on iOS (iOS 14.0.1). 

I'm going to close for now. We can re-open if we get a non-AMP-related report.
