### ISSUE TITLE
incorrect footer margin-top height fix.

### ISSUE THREAD

**Issue by web-migrates** [WordPress/twentytwentyone#396]
when review footer in all kinds of device desktop and mobile the margin-top is too much that should be similar as per the header. 

| Current | Expected |
| ------ | ------ |
|![Screenshot_1](https://user-images.githubusercontent.com/48351809/95654494-fb1ef800-0b1d-11eb-80c7-321de48f188a.png)| ![Screenshot_2](https://user-images.githubusercontent.com/48351809/95654508-04a86000-0b1e-11eb-9215-07f4fb68e82b.png)|

On the "Expected" screenshot, note the extra margin-top in the footer. These match the margins available on the header.

**Comment by melchoyce** [comment]
Per https://github.com/WordPress/twentytwentyone/pull/397#issuecomment-706580311, closing this.
