### ISSUE TITLE
Site navigation should centre aligned to Site Branding section

### ISSUE THREAD

**Issue by monika-12** [WordPress/twentytwentyone#398]
**Describe the bug**
Site navigation(Primary Navigation) is not horizontally aligned to Site Branding Section.

**To Reproduce**
1. Go to 'Appearance - Menu`
2. Create Primary Navigation
3. Go to Customizer and add Logo
4. Refresh the page
5. See Primary Navigation and Site Branding section you will see the difference

**Expected behavior**
Primary Navigation should centre aligned with the Site Branding section

**Screenshots**
https://a.cl.ly/Qwuk0e4B

**Comment by kishanjasani** [comment]
Thanks, @monika-12 I am able to reproduce. :+1:

**Comment by kishanjasani** [comment]
Need to discuss this issue. It will affect the style of navigation without a logo image. `align-item: center` looks good with a logo image. but without a logo image, it looks weird.

**Comment by carolinan** [comment]
@monika-12 Hi 👋  I'm not sure I understood correctly. The menu is designed to be right aligned, not centered.
Did you mean vertical? Maybe if you can add a before and after image of the result you expected?

**Comment by kishanjasani** [comment]
She has uploaded a screenshot here: https://a.cl.ly/Qwuk0e4B

**Comment by kishanjasani** [comment]
It doesn't look good with the logo. It will be better if we hide the site title and description when we select the logo. Here is the tested screenshot of this PR 

![screenshot-twentyone local-2020 10 12-16_35_31](https://user-images.githubusercontent.com/25550562/95739962-4c0f2780-0ca9-11eb-8e6b-d9ecf3f1bf96.png)

**Comment by ingereck** [comment]
On mobile, with site title, only (no logo), the site title also does not align with the menu - screen shot below: 
https://share.getcloudapp.com/Blu15mGW?collection_id=gKfoD5 
as it does on desktop - screen shot below: 
https://share.getcloudapp.com/8LurPW1z?collection_id=gKfoD5

If the site title is long, it probably makes sense that the site title moves to the next line, but with a short site title it consumes a lot of space and looks a little scattered.

**Comment by ingereck** [comment]
Landscape logo images: 
The logo I tested with, has an aspect ratio of 21 x 9. Uploading the image with max 240px width allowed me to select 'Skip cropping' and set the logo. It's great that this works, however on desktop the logo turned out to be far to small. 
So it would be great having the option to 'Skip cropping' also when the max height is 240 px.
