### ISSUE TITLE
Search widget search input border radius displayed in iOS safari mobile

### ISSUE THREAD

**Issue by web-migrates** [WordPress/twentytwentyone#399]
A search widget search input shows unnecessary border-radius in the safari browser of iOS mobile device, it should be similar to the other devices. 
| Current | Expected |
| ------ | ------ |
|![IMG_9247](https://user-images.githubusercontent.com/48351809/95657622-0e888e00-0b33-11eb-9c69-beafb78a57fd.PNG)|![IMG_9248](https://user-images.githubusercontent.com/48351809/95657634-15af9c00-0b33-11eb-9fb0-4b93ecaf295b.PNG)|

On the "Expected" screenshot, it looks the same as other devices without border-radius.

**Comment by melchoyce** [comment]
Able to replicate on iOS 13.7 in Safari:

<img src="https://user-images.githubusercontent.com/2846578/96202303-de732d80-0f2c-11eb-9bd1-f72611a148aa.jpg" width="400" />

Looks like it's a pretty easy CSS fix: https://stackoverflow.com/questions/2918707/turn-off-iphone-safari-input-element-rounding
