### ISSUE TITLE
Copyright date is incorrect

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#401]
**Describe the bug**
This was sent to me from @pixolin:

The footer displays a copyright information using function date_i18n(), which seems to retrieve the current year. 
This seems legally tricky. 
According to [https://stackoverflow.com/a/2391555/12490449](https://stackoverflow.com/a/2391555/12490449)

The copyright notice on a work establishes a claim to copyright. The date on the notice establishes how far back the claim is made. 
This means if you update the date, you are no longer claiming the copyright for the original date and that means if somebody has copied the work in the meantime and they claim its theirs on the ground that their publishing the copy was before your claim, then it will be difficult to establish who is the originator of the work

**Comment by aristath** [comment]
+1, that thing has been bugging m for years

**Comment by carolinan** [comment]
It has been pointed out that copyright is given automatically when you create something and that the year stated here does not matter.

We can add a function that checks the date of the earliest post or page, and write two years, if the year is different.
Or we can remove the copyright year, or remove the whole copyright statement, and let people add their own copyright, license or terms where they want.

**Comment by aristath** [comment]
Hmmm Does "copyright ©/℗/®/™" even make sense in the web for content?
People don't need to add copyright statements for what they write, the web is governed by slightly different concepts of copyright, and it's not necessary to register for a trademark or legally register the content. AFAIK, original content is automatically copyrighted to the author at the time of publishing. If they publish non-original content and they don't include attribution, then the copyright can potentially cause problems for them.
With that in mind, I think it's safe to remove the copyright & year notices from the footer. It's traditional but not really necessary :thinking: 
If someone wants it and they actually have a copyright, there's nothing stopping them from adding it themselves.

**Comment by pixolin** [comment]
I'm not a lawyer, but I've learned over the years that e.g. German copyright law, is very different from US regulations. A Copyright note won't harm, yet isn't necessariy to gain the right to decide about your work.
For that reason I would appreciate a form field in customizer which allows users to individually change the footer according to their needs.

+1 for "remove the whole copyright statement, and let people add their own copyright, license or terms where they want."

**Comment by carolinan** [comment]
If we keep it, it should make use of wp_date(), since our target minimum version is 5.3.0

https://developer.wordpress.org/reference/functions/wp_date/

**Comment by aristath** [comment]
Pending a decision here I added a new PR on #408. That PR removes the copyright date and adds a new option in the customizer (textarea) where users can add their copyright or change the default footer text if they want to.

**Comment by carolinan** [comment]
It was decided during the meeting today that the customizer option will be used so that the users can change this.
