### ISSUE TITLE
Media & Text Article Title Pattern: Ampersand doesn't render

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentytwentyone#430]
**Describe the bug**
The `&` in the block pattern title is displayed as `&amp;`

**Screenshots**
![image](https://user-images.githubusercontent.com/2846578/95770945-33424a00-0c88-11eb-919e-3b9160cb29aa.png)

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed?: No

**Comment by kjellr** [comment]
Closed via #434.
