### ISSUE TITLE
Post title underline is uneven on hover in post navigation component

### ISSUE THREAD

**Issue by audrasjb** [WordPress/twentytwentyone#438]
**Describe the bug**
Post title underline is off-centered on hover in post navigation component

See animated screenshot below:
![79016d2d8f675321271d9f887a712d0d](https://user-images.githubusercontent.com/1590998/95798558-a2ed1f00-0cf2-11eb-9ea8-4e0c2ef26ecf.gif)

**To Reproduce**
1. Go to the post navigation area in a single post (you'll need several posts to see the issue in action)
2. Hover the post title for previous or next post
3. Post title is off-centered 😛 

**Expected behavior**
I think we don't need any margin. It looks really great when the post title is aligned with the arrow.
…and it fixes the issue 😏 

![a77c78eddf2cf1753ed8eb45031650b5](https://user-images.githubusercontent.com/1590998/95798774-17c05900-0cf3-11eb-9091-d4d5d5986258.gif)

**Comment by carolinan** [comment]
This has been fixed with a series of pull requests, so I will close this.
https://github.com/WordPress/twentytwentyone/pull/504,
https://github.com/WordPress/twentytwentyone/pull/503,
https://github.com/WordPress/twentytwentyone/issues/501
