### ISSUE TITLE
Continue the code clean up

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#44]
**Describe the bug**
There is still code inherited from Seedlet that needs to be removed.

-Block patterns, including any related CSS (Keep the file and functions for when we are ready to add the new patterns!)
-Left over CSS from removing the gradients
-The foreground color that is no longer used.
-Empty CSS selectors.

If you find anything else that you feel needs to be mentioned here, that you do not have time to work on, 
you can add it to the issue.

**Comment by kjellr** [comment]
Once #118 is merged, can we close this issue and open individual issues for anything that's left? It's becoming a little hard to follow.
