### ISSUE TITLE
Improve vertical spacing for post formats

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#443]
**Describe the bug**

_Archive view_
When a (standard) post has a featured image, the image is outside the entry content 
and the vertical spacing between the title and the image is 60px: `margin-top: calc(2 * var(--global--spacing-vertical));`

For post formats that displays a video, image, gallery or pattern with an image, the 
entry content has `margin-top: var(--global--spacing-vertical);`, but the first block has no vertical spacing.

**To Reproduce**
1. Create a post with a featured image
2. Create a post with image content and set the post format to image.
3. Go to the front and view the blog or archive.
4. Compare the two posts and see that the spacing does not match.

**Expected behavior**
The vertical spacing should be the same.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome version  86.0.4240.75

Left: featured image on standard post. Right: Image post format

![images](https://user-images.githubusercontent.com/7422055/95835251-49aadd00-0d3e-11eb-9c63-5582181aba95.png)

**Comment by melchoyce** [comment]
I agree the spacing needs to be consistent here 👍
