### ISSUE TITLE
Reconsider the WordPress version check

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#446]
**Describe the bug**
The theme has a version check where it activates a default theme if the WordPress version is lower than 5.3
https://github.com/WordPress/twentytwentyone/blob/trunk/inc/back-compat.php#L23

The current way of implementing this will not work when the theme is the latest default theme.

One option is to remove the backwards compatibility check.

**Comment by aristath** [comment]
We can just remove this part: https://github.com/WordPress/twentytwentyone/blob/7bde7bb59b816ddcadbe0261a8f4a5922a71af19/inc/back-compat.php#L14-L28

Site-admins will get the notice on their dashboard and they can change themes manually

**Comment by aristath** [comment]
Submitted PR on #450
