### ISSUE TITLE
WP 5.3 Block test: group:

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#448]
### Expected behavior

Does the editor and front match?

_**No**_
In the editor, a group block with a background color is missing the bottom vertical spacing.

### Editor:
![53group](https://user-images.githubusercontent.com/7422055/95853196-51c24700-0d55-11eb-839e-4240ef26492b.png)

![53group-border](https://user-images.githubusercontent.com/7422055/95853398-a5cd2b80-0d55-11eb-92b3-efef488c9852.png)

### Front:
![53group-front](https://user-images.githubusercontent.com/7422055/95853302-79b1aa80-0d55-11eb-9a73-b1e6a92edd2f.png)

Editor version (please complete the following information):
WordPress version: 5.3
Gutenberg version: Not installed

What was used to test (please complete the following information):
OS: Windows 10
Browser: Chrome  86.0.4240.75

**Comment by carolinan** [comment]
Related: https://github.com/WordPress/twentytwentyone/issues/492

**Comment by aristath** [comment]
Both this one and #492 were essentially core-editor bugs that were fixed in later versions.
Is it the theme's responsibility to address core bugs?
Does "compatible with WP 5.3" mean that things in WP 5.3 should be identical to 5.6? Or does it means "we guarantee it won't break your site as far back as WP 5.3"?

**Comment by pattonwebz** [comment]
For me I think chasing full backwards compatibility on older versions of WP and all the version of GB that shipped with it is too much of a challenge without a lot of added value for the time it would take.

Personally I feel it's sufficient to make sure it doesn't break as far back as 5.3 but trying to get exact match or like-for-like display probably isn't going to be possible without a great deal of work (and workarounds).
