### ISSUE TITLE
The password input field is the wrong size

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#449]
**Describe the bug**
When content is password protected, a password form is displayed.
The password input field is not the same height as the button, and the spacing between the field and the button is not 
the same if compared to for example the search form.

**To Reproduce**
1. Password protect a post or page, save.
2. View the front.
3. See that the input field and button does not have the same height.

**Expected behavior**
I think it would look better if the field and button sizes matched.
Perhaps the _Password:_ label should also be on its own line, above the input.

**Screenshots**

![password-1](https://user-images.githubusercontent.com/7422055/95859133-6d7e1b00-0d5e-11eb-802b-faf12cd4c14b.png)

Password form overlapping the search form just to show the difference:
![password](https://user-images.githubusercontent.com/7422055/95859067-550e0080-0d5e-11eb-9056-900c66b39e6e.png)

**Editor version (please complete the following information):**
- WordPress version: 5.5.1, 5.30.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome version 86.0.4240.75

**Comment by kishanjasani** [comment]
Hi @SResok, This is not a case with just password inputs it's also causing issues with all the inputs with the submit button. Ex: Have a look at the search widget in the footer has also same issue.

![screenshot-twentyone local-2020 10 13-22_00_37](https://user-images.githubusercontent.com/25550562/95889068-97a3fd00-0d9f-11eb-8862-e2aafc9401d5.png)

cc: @carolinan

**Comment by carolinan** [comment]
I can not reproduce this with any other input fields. Which browser and WP and possibly Gutenberg version are you using?

The screenshot you have added doesn't show the same sizing problem?

**Comment by kishanjasani** [comment]
Don't know It looks weird on my chrome browser. I am using the latest default WP installation with twentytwentyone theme. my screen resolution is `1360 * 768`. It breaks from `822px` breakpoint to N/A. It shows me broken that field as a displayed screenshot of the last comment

**Comment by carolinan** [comment]
I don't understand. In what way is it broken? Because it is on a new line?

I don't understand how that is related to the problem in the screenshot of the password form?

**Comment by kishanjasani** [comment]
> Because it is on a new line?
No.

See the height of the textbox and button are different on the mentioned resolution.

**Comment by melchoyce** [comment]
It's a little easier to spot in this gif from #437:

![f3caecbdd2befbd38f9d3685470c2621](https://user-images.githubusercontent.com/1590998/95797497-fd38b080-0cef-11eb-89f4-a08fb8715a87.gif)

You can see the height of the input field become shorter when the button drops onto the next line.

I don't think it's as much of a problem, as long as the input field and button are the same height when they're on the same line (which they are in the search widget, and on search result pages).

**Comment by SResok** [comment]
@kishanjasani @carolinan @melchoyce 
I just applied the same spacings from #437 to the password field
