### ISSUE TITLE
WP 5.3: The calendar widget has the wrong design.

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#451]
**Describe the bug**
In WordPress 5.3, the calendar widget has the wrong design.

The colors for the header and border is incorrect.
It has the wrong link color for the month, and the arrow is miss aligned.

**_I did not look further to see what causes this. Missing CSS classes? Light block wrappers?_**

5.3: 
![53-calendar](https://user-images.githubusercontent.com/7422055/95867925-fa7aa180-0d69-11eb-8fe9-f4aa486213b1.png)

5.5.1:
![551-calendar](https://user-images.githubusercontent.com/7422055/95868344-665d0a00-0d6a-11eb-9333-646a0a28c086.png)

As a side note, the calendar style is correct in 5.4.0.

**To Reproduce**
1. Install WordPress 5.3
2. Create a post or page and add a calendar widget, or, install the theme unit test and view the post "Block category: widget"
3. See error

**Expected behavior**
It would look better if the new design was implemented. 

**Editor version (please complete the following information):**
- WordPress version: 5.3.0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome version  86.0.4240.75

**Comment by aristath** [comment]
Just like other similar WP5.3 issues, I'm closing this one.
In WP 5.3 the content is still readable and accessible. Adding styles for all possible changes that WP has done to all widgets or Gutenberg has done to the blocks markup over the years is not a viable or sustainable plan. The theme is compatible with WP as far back as 5.3, but that doesn't mean that if they use an old version of WordPress things will look identical.
