### ISSUE TITLE
Add custom gradients

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#46]
The theme currently has no custom gradients, but a placeholder for editor-gradient-presets has been left in functions.php
to make them easier to include. 
If no custom gradients are added, this code needs to be removed in time for beta 1.

**Comment by melchoyce** [comment]
I have some gradient ideas in progress, but I need to try them out in context before we can decide which ones to include: https://www.figma.com/file/OEtsCj8oD8JPVx4OvsS0U2/Twenty-Twenty-One?node-id=764%3A54

Hoping to work on this more tomorrow.

**Comment by ellenbauer** [comment]
Love the gradients, they look beautiful and I think work well as backgrounds eg in the cover block or group block with images in front (photography or graphic images).

Just as an inspiration, I by accident came across the Carbonmade website today and they use similar colours and background gradients on their front page. It reminded me of it so I just want to through it in here.

**Comment by melchoyce** [comment]
Thanks @ellenbauer! Great inspiration source.

I tried a bunch of combinations of our recommended colors in the editor:

![image](https://user-images.githubusercontent.com/2846578/94971787-d56a7100-04d5-11eb-9094-7a07c2afb60e.png)

Overall, they looked nice. I noticed:
- All of them look great when inside a block with the border style
- The lighter colors don't look as good against the default mint background, without any sort of divider
- The gradients that go from mint to another color, or another color to mint, look good. And, you can do fun things by combining those with a solid color group blocks to get a smooth color transition:

![image](https://user-images.githubusercontent.com/2846578/94971974-32662700-04d6-11eb-85a2-fd3699913b3d.png)

I tried to make some color-stop gradients with the Gutenberg plugin active, but I couldn't figure out how to make one. Anyone know?

**Comment by LittleBigThing** [comment]
> I tried to make some color-stop gradients with the Gutenberg plugin active, but I couldn't figure out how to make one. Anyone know?

I don't think you can. The color-stops can (now) only be presets. There are some cool presets in the Seedlet theme and how [they](https://github.com/Automattic/themes/blob/6ce76efc2685c83cda7a08a582d79fbe6c1722ce/seedlet/functions.php#L204) are [added](https://github.com/Automattic/themes/blob/6ce76efc2685c83cda7a08a582d79fbe6c1722ce/seedlet/assets/sass/blocks/utilities/_style.scss#L309).

I made an example PR with some gradient presets in #258.

**Comment by LittleBigThing** [comment]
I was wondering whether we can change the initial colors of the custom gradient picker to match the theme‘s color palette.

**From:**
![Screenshot 2020-10-03 at 18 18 38](https://user-images.githubusercontent.com/5901923/94996439-0e254b80-05a5-11eb-86b5-7b93edf767a3.png)

**To:**
![Screenshot 2020-10-03 at 18 19 33](https://user-images.githubusercontent.com/5901923/94996445-154c5980-05a5-11eb-85f4-7755379fa054.png)
