### ISSUE TITLE
Avoid using `wp_kses_*` functions

### ISSUE THREAD

**Issue by aristath** [WordPress/twentytwentyone#479]
In many cases we use things like `wp_kses_post( __( 'Something', 'twentytwentyone' ) )`.
For performance reasons it would be a lot more efficient if we used `esc_html__()` or a similar function depending on the string and where it's used.

**Comment by ocean90** [comment]
Actually, default core themes should not escape translations at all. See https://core.trac.wordpress.org/ticket/30724 for background.

**Comment by pattonwebz** [comment]
> Actually, default core themes should not escape translations at all. See https://core.trac.wordpress.org/ticket/30724 for background.

I still believe this is incorrect to say translations shouldn't be escaped. Most people that make themes believe it's incorrect as well. A 6 year old ticket with very little input from theme developers is not a reason to remove escapes on translations ;)

**Comment by aristath** [comment]
The default theme should comply with all requirements and recommendations of any theme hosted in the .org repo.
@ocean90 Are you suggesting we remove the "All untrusted data should be escaped before output." rule for all themes hosted on .org?
Translations can't always be trusted btw, we can't assume that they will only come from w.org. It is not rare for people in other locales to just translate things on their own, share them with a system other than glotpress and skip the .org fuss of waiting for translation approvals etc (for example by emailing the po/mo files to a friend who's also building a website)

**Comment by ocean90** [comment]
I'm not going to repeat myself (it's the same for every default theme, see [2020](https://github.com/WordPress/twentytwenty/pull/734) as another example) and I don't know what rules the theme review has. But since the theme will be bundled with core the rules for core should apply.

**Comment by aristath** [comment]
The default theme is indeed bundled with core. However, it is also hosted in the themes repository, should go through a review process, and it's what theme-developers see & use as an example of a "good" theme.
If anything, the default theme should follow stricter rules and set a good example instead of bypassing every rule in the book because it's core.

**Comment by pattonwebz** [comment]
@ocean90 it's only the same for every default theme because you made it so without any input from the theme review team whatsoever. You done the same thing last year and against my best judgement I did not continue to push back. 

I'm voicing my opinion again this year that the translations should be escaped.

**Comment by dingo-d** [comment]
+1 on the escaping. Default themes are the ones that get used the most by developers as sort of a starting point in theme development. 

It's a good practice to escape on the output, even in translations. This can only be a good thing in the end, not a bad thing IMO.

And citing any kind of 'performance impact' would be nitpicking and would fall in the realm of micro-optimizations.

**Comment by carolinan** [comment]
This has already been solved, closing.
