### ISSUE TITLE
Consistency - van Gogh or Van Gogh

### ISSUE THREAD

**Issue by fxbenard** [WordPress/twentytwentyone#480]
**Describe the bug**
Please make sure Van/van Gogh is spelled the same way all across the strings

**Screenshots**
![Screenshot_2020-10-14 Translations French (France) Twenty Twenty-One GlotPress — WordPress org](https://user-images.githubusercontent.com/802114/96000831-9faf7b80-0e37-11eb-8dde-b5d171f5cc9a.png)

**Comment by fxbenard** [comment]
As well `&quot;` should be replaced with `&#8220; and &#8221;`

**Comment by carolinan** [comment]
This is very very low priority until the final images are in the theme and not just placeholders

**Comment by carolinan** [comment]
Closing, as new images have been selected.
