### ISSUE TITLE
Menu descriptions looks bad in the secondary menu

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#485]
**Describe the bug**
When a menu that has descriptions is added to the secondary menu,
the description is shown to the right of the menu item link text, and there is no spacing between the two texts.

**To Reproduce**
1. Add descriptions to a menu
2. Add the menu to the secondary menu ( footer)
3. View the front, scroll down to the footer.

**Expected behavior**
Either the description should not show at all (This is my personal favorite for this simpler menu)
or, the description should be below the menu item link text.

**Screenshots**
![menu-description](https://user-images.githubusercontent.com/7422055/96079101-37eb4600-0eb4-11eb-984c-aec8e938d552.png)

**Editor version (please complete the following information):**
- WordPress version: 5.5.1

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome version  86.0.4240.75

**Comment by aristath** [comment]
PR in #491
