### ISSUE TITLE
Sub-menu toggle size is larger when a description is used

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#487]
**Describe the bug**
When a menu item has a description, the toggle button height is the same as the combined menu item and description text.
The plus and minus icons is vertically centered, even for items that has no description.

**To Reproduce**
1. Create a menu that has both sub menus and descriptions
2. Assign the menu to the primary menu location
3. View the front

**Expected behavior**
I think the button should be in the same position no matter if there is a description or not.

**Screenshots**

![menu-description-icon](https://user-images.githubusercontent.com/7422055/96081234-31ab9880-0eb9-11eb-960c-e5e6896ec168.png)

Button in focus, here the button size is more obvious:
![menu-description-icon-focus](https://user-images.githubusercontent.com/7422055/96081571-da59f800-0eb9-11eb-8d17-eb7555a8e878.png)

**Editor version (please complete the following information):**

WordPress version: 5.5.1
Desktop (please complete the following information):

OS: Windows 10
Browser Chrome version 86.0.4240.75

**Comment by aristath** [comment]
PR on #490
