### ISSUE TITLE
Table text is wrapping unexpectedly

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#488]
**Describe the bug**
Text inside tables and table headers wrap unexpectedly both for classic tables and table blocks.
This is easiest to see with the screenshots below.

**To Reproduce**
1. Install the theme unit test
2. View the page called "page-markup-and-formatting/"
3. See the text wrap
4. Create a new table block
5. Save and view the front
6. See the text wrap

**Expected behavior**
The text needs to be readable.

**Screenshots**
Twenty Nineteen for comparison:
![table2019](https://user-images.githubusercontent.com/7422055/96082340-5739a180-0ebb-11eb-928c-930a5ad9ffd2.png)

Same table in Twenty Twenty-one:
![table2021](https://user-images.githubusercontent.com/7422055/96082419-7b957e00-0ebb-11eb-947e-5e0477d209cb.png)

And as a table block with table header:

![table-block-2021](https://user-images.githubusercontent.com/7422055/96082508-9ec02d80-0ebb-11eb-975c-f6de20b1d641.png)

Editor version (please complete the following information):

WordPress version: 5.5.1
Desktop (please complete the following information):

OS: Windows 10
Browser Chrome version 86.0.4240.75

**Comment by aristath** [comment]
@JustinyAhin I'm sorry, I missed the fact that this was already assigned to you, and I pushed a PR on #500...

**Comment by JustinyAhin** [comment]
> @JustinyAhin I'm sorry, I missed the fact that this was already assigned to you, and I pushed a PR on #500...

It's fine @aristath. Thanks :+1:
