### ISSUE TITLE
Suggested image size

### ISSUE THREAD

**Issue by naunha** [WordPress/twentytwentyone#498]
I know that perhaps this question is inopportune, but it never hurts to ask. I'm new here on GitHub and I'm really enjoying this new twenty twenty-one theme. I follow the development from the beginning. I will definitely implement it on my personal blog. I'm even adapting all the content for this new theme. My question is: **How big are the images recommended for the theme?** Thanks in advance, I apologize if I rushed and congratulate the developers.

**Comment by aristath** [comment]
There is no specific size requirement anymore, just use whatever size looks best in your posts. :)
