### ISSUE TITLE
Add initial block patterns

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentytwentyone#50]
Twenty Twenty One will come packaged with several block patterns. Here's a couple to get us started.

---

- [x] **Two images showcase**

![image](https://user-images.githubusercontent.com/2846578/93505065-5f1c1b00-f8e8-11ea-8907-6f3754d54697.png)

- Full-width block
- Maybe a media and text block, where instead of text, we show a second, smaller, framed image?

---

- [x] **Overlapping gallery**

![image](https://user-images.githubusercontent.com/2846578/93506538-66442880-f8ea-11ea-8592-61172699cd19.png)

- Wide-width block
- Maybe every third image overlaps every second image? Or horizontal images always overlap vertical images? We'll need to play with this in code to determine the best approach.

---

- [ ] **Image underlapping text box**

![image](https://user-images.githubusercontent.com/2846578/93506554-70febd80-f8ea-11ea-9562-0ce3205904ca.png)

- Wide-width block
- Image block
- Overlapped by a paragraph in a container with a border

---

- [x] **Media & Text article title**

![image](https://user-images.githubusercontent.com/2846578/93506644-8c69c880-f8ea-11ea-8720-3e8358d645c0.png)

- Width-width block
- Media and text block with a border. The text includes an H2, short separator block, and a small paragraph

---

- [x] **Portfolio list**

![image](https://user-images.githubusercontent.com/2846578/93506798-c2a74800-f8ea-11ea-9994-8a44ba402e33.png)

- Width-width block
- Separator, H2, tiny image

---

- [x] **Large text**

![image](https://user-images.githubusercontent.com/2846578/93506885-e8345180-f8ea-11ea-8f98-16e470d9020c.png)

- 144px paragraph block, 300 font weight

---

- [ ] **Two overlapping blocks of text**

![image](https://user-images.githubusercontent.com/2846578/93506927-f5e9d700-f8ea-11ea-925b-066fbc741ec0.png)

- Wide-width block
- Extra large paragraph in the first block, large paragraph in the second

---

- [x] **Link CTA**

![image](https://user-images.githubusercontent.com/2846578/93506975-0732e380-f8eb-11ea-8ae1-e61ebf621b0b.png)

- Width-width block
- Group or cover block with a border
- 96px paragraph block, 300 font weight
- Spacer block?
- Columns block
 - Left column: social media links
 - Right column: email link

-----

You can view all of these block patterns in Figma: https://www.figma.com/file/OEtsCj8oD8JPVx4OvsS0U2/Twenty-Twenty-One?node-id=269%3A68

As more pattern designs come in, we'll likely end up modifying or removing some of these initial patterns, but they should be good to get us started.

**Comment by kjellr** [comment]
> **Large text**
> 144px paragraph block, 300 font weight

Anyone have ideas for how to implement the font-weight setting for this one? Block patterns don't come with their own CSS class, so we can't assign it in the stylesheet. And selecting a light font weight is not possible in the editor currently. 🤔 We could add a custom class ourselves, but I feel like users aren't going to notice that's there and it may cause confusion.

**Comment by melchoyce** [comment]
Yeah, we might be out of luck there 😕

**Comment by carolinan** [comment]
When you say, we can add the custom class ourselves, do you mean using the additional CSS class field? 
Why would that be confusing? In case they want to remove the font weight?

**Comment by kjellr** [comment]
> When you say, we can add the custom class ourselves, do you mean using the additional CSS class field?
Why would that be confusing? In case they want to remove the font weight?

Yeah, it's a hack. Users definitely won't know it's there.

**Comment by LittleBigThing** [comment]
> > **Large text**
> > 144px paragraph block, 300 font weight
> 
> Anyone have ideas for how to implement the font-weight setting for this one? Block patterns don't come with their own CSS class, so we can't assign it in the stylesheet. And selecting a light font weight is not possible in the editor currently. 🤔 We could add a custom class ourselves, but I feel like users aren't going to notice that's there and it may cause confusion.

Couldn't a light font weight be part of a paragraph block style?
I think though that a light font style may not be visibly distinctive in each system font?

**Comment by kjellr** [comment]
> Couldn't a light font weight be part of a paragraph block style?
> I think though that a light font style may not be visibly distinctive in each system font?

Yeah — using a block style of it feels a little weird in general, but you make a great point about how some system fonts in the stack may actually not have a light variant to swap out with. In that case, the user wouldn't notice any difference between the normal + "Light" block styles. 😕

**Comment by melchoyce** [comment]
Yeah, we might just need to go with regular weight here.

**Comment by carolinan** [comment]
Why do users need to know that the additional class is there?  It is not a problem for other block styles, like
"is-style-twentytwentyone-border"

**Comment by carolinan** [comment]
Is adding a class to patterns something that you want to move over to the Gutenberg repo?

**Comment by kjellr** [comment]
> Why do users need to know that the additional class is there? It is not a problem for other block styles, like
"is-style-twentytwentyone-border"

That class is added via a block style though, so while it is invisible to the user, they have standard Gutenberg UI to add and remove it. 

> Is adding a class to patterns something that you want to move over to the Gutenberg repo?

I don't think so. There _is_ a standard practice for doing so (block styles). The problem is mostly that it doesn't quite make sense for us to adopt that for font weight here. There's already a PR for font-weight, and that's all we need to get this implemented in a standardized way: https://github.com/WordPress/gutenberg/pull/24978.

**Comment by carolinan** [comment]
Block patterns can add CSS class names that are visible in the additional CSS class field too.

**Comment by melchoyce** [comment]
Since we're finding that it'll be difficult to do text overlaps, it might be nice to sub in this one instead:

![image](https://user-images.githubusercontent.com/2846578/95502819-6e870500-0978-11eb-86b4-d3a588fdcfdf.png)

```
<!-- wp:columns {"verticalAlignment":null,"align":"wide","className":"is-style-twentytwentyone-columns-overlap"} -->
<div class="wp-block-columns alignwide is-style-twentytwentyone-columns-overlap"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:image {"id":181,"sizeSlug":"large"} -->
<figure class="wp-block-image size-large"><img src="http://twentytwentyone.local/wp-content/uploads/2020/10/vangogh-02-002.jpg" alt="" class="wp-image-181"/></figure>
<!-- /wp:image --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"bottom"} -->
<div class="wp-block-column is-vertically-aligned-bottom"><!-- wp:group {"className":"is-style-twentytwentyone-border","backgroundColor":"green"} -->
<div class="wp-block-group is-style-twentytwentyone-border has-green-background-color has-background"><div class="wp-block-group__inner-container"><!-- wp:paragraph {"fontSize":"extra-large","style":{"typography":{"lineHeight":"1.4"}}} -->
<p class="has-extra-large-font-size" style="line-height:1.4">Beautiful flowers painted by Vincent van Gogh in the late 1800s</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:image {"id":24,"sizeSlug":"large"} -->
<figure class="wp-block-image size-large"><img src="http://twentytwentyone.local/wp-content/uploads/2020/09/DP346475-811x1024.jpg" alt="" class="wp-image-24"/></figure>
<!-- /wp:image --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```

**Comment by melchoyce** [comment]
This should be good now! Closing.
