### ISSUE TITLE
Page title moved to the left and is underlined now

### ISSUE THREAD

**Issue by ingereck** [WordPress/twentytwentyone#511]
**Describe the bug**
Before the page title was is line with the text (paragraph block) and there was only a line under the page title on the Blog's page. 
Now, the Blog page does no longer have a line, but all other pages have one, and the page title moved all the way to the left.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Example page: https://wp19671.vps.webdock.io/vita/
2. Scroll down
Please see screen shot examples below

**Expected behavior**

The cover block should replace the line under the page title, alternatively make it selectable (toggle on/off). The page title should align with the text/paragraph (see example 'before') or make it selectable left/align with paragraph.

**Screenshots**
Now:
https://share.getcloudapp.com/llu259Oy
Before: 
https://share.getcloudapp.com/geuqbbj7

Example page: https://wp19671.vps.webdock.io/vita/

**Editor version (please complete the following information):**
- WordPress version: 5.6-alpha-49152
- default

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Browser Chrome
 - Version 86.0.4240.75 

**Smartphone (please complete the following information):**

Alignment of the page title is ok. 

 - Device: iPhone 6
 - OS: 12.4.8
 - Browser Chrome 
 - Version 86.04.4240.65

**Additional context**
Cover block, full width

**Comment by melchoyce** [comment]
Hey @ingereck, this was an intentional change made in https://github.com/WordPress/twentytwentyone/pull/173. You can read more about the reasoning behind the change in https://github.com/WordPress/twentytwentyone/issues/37. Going to close this but please keep creating issues as you find bugs!
