### ISSUE TITLE
Capital letter - BUG

### ISSUE THREAD

**Issue by naunha** [WordPress/twentytwentyone#516]
I inform the error of positioning of the capital letter, in the paragraph block. See attached figure. Edge Browser.

![Captura de Tela (126)](https://user-images.githubusercontent.com/5017547/96202228-0bc3d980-0f35-11eb-8638-8b296da55ddb.png)

**Comment by carolinan** [comment]
Is the size of the dropcap correct @melchoyce?

**Comment by melchoyce** [comment]
It seems big — ideally it would be roughly the height of three lines of text:

![image](https://user-images.githubusercontent.com/2846578/96213950-30757c80-0f48-11eb-8e30-7e0866ff99d9.png)

(I used 116px in the above screenshot, but hopefully there's a way to keep it all proportional)

**Comment by naunha** [comment]
> Is the size of the dropcap correct @melchoyce?

What would be the correct size? As soon as the lower lines return to the normal position of the paragraph, this overlapping of the initial letter should not happen

**Comment by rolf-yoast** [comment]
@naunha I'm already working on a PR as we speak ;-)
