### ISSUE TITLE
Pullquote text should not change color when placed over a background color.

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#518]
**Describe the bug**
When a pullquote is placed inside a block that has a background color, and the body background color is changed,
the text color of the pullquote changes to have a high contrast against the body background color.

**To Reproduce**
1. Add a group block, media and text or cover block and change its background color.
2. Add a pull quote, save
3. Go to the customizer and change the body background color.
4. See the text color change depending on the body background.

**Expected behavior**
The text needs to be readable.

Note: If the colors of the pull quote are customized, the color works well.

**Screenshots**
![pull](https://user-images.githubusercontent.com/7422055/96212312-ce803b80-0f76-11eb-9249-e8716da3849e.png)

**Editor version (please complete the following information):**
Tested both with and without Gutenberg 9.1.1.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 86.0.4240.75

**Comment by carolinan** [comment]
The theme changes the default text color to keep a high contrast with the _body background_, that does not work then there is an extra background color in between.

**Comment by carolinan** [comment]
We forgot the color of the quote symbol, reopening.

**Comment by SResok** [comment]
> We forgot the color of the quote symbol, reopening.

@carolinan It seems to be working on my end. 

![image](https://user-images.githubusercontent.com/20287474/96426998-4ca24380-11fe-11eb-9e3e-d2389856c790.png)

**Comment by carolinan** [comment]
When you place it inside a group block with a background color too?

**Comment by carolinan** [comment]
Ah, the symbol does not change color with either the main or text color option, but that is a separate issue, has that been brought up earlier?

**Comment by SResok** [comment]
> Ah, the symbol does not change color with either the main or text color option, but that is a separate issue, has that been brought up earlier?

Not that i know of, will push a fix!

**Comment by carolinan** [comment]
This issue is only confusing, I will open a new one with a proper description.
