### ISSUE TITLE
Posts with Aside and Status post formats can not be reached from archives

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#527]
**Describe the bug**
With the removal of the link on the post date, we forgot to add a link where these post formats can be reached.
(The link text needs to be in context and relevant, we can not reuse the post date for this purpose.)

**To Reproduce**
1. Create an aside and or status post
2. View the archive listing
3. See error

**Expected behavior**
All the site content must be reachable.

**Comment by melchoyce** [comment]
Should we add a "read more" link to these?
