### ISSUE TITLE
Sticky post isn’t visually different than the other posts

### ISSUE THREAD

**Issue by briceduclos** [WordPress/twentytwentyone#532]
**Describe the bug**
 Currently, a sticky post looks like a “normal” post. There’s no indication that it’s sticky.

**Expected behavior**
The sticky post should have a text indicating that it’s sticky or a different styling that distinguishes it from the other posts.

**Comment by carolinan** [comment]
It is different from the others because it is placed at the top, out of order.

**Comment by briceduclos** [comment]
All previous default themes (Twenty Twenty, Twenty Nineteen, Twenty Seventeen) and Seedlet add a label indicating to the user that the post is sticky/featured (similar to Twitter). For a website visitor, I think it can be weird not to show anything. Let’s say your sticky post is dated from 2019 and that you’ve written other posts in 2020. When visiting your posts page, the visitor might think that you haven’t published any post since 2019 and leave your blog as he thinks there’s nothing new to read.

**Comment by melchoyce** [comment]
We could stick (hah!) it into the footer meta on archive pages?

What label do you think makes the most sense — Pinned? Sticky post? Featured?

**Comment by aristath** [comment]
<details>
<summary>Edit: Comment hidden 'cause it looked worse after I looked at for a couple of minutes. (click to expand)</summary>

We could add something like this...
```css
.sticky {
  background: rgba(0,0,0,0.05);
  padding-top: 1em;
}
```
The result would look like this:
![Screenshot_2020-10-19 My Blog(2)](https://user-images.githubusercontent.com/588688/96404096-b3b1ff00-11e2-11eb-93a0-90d81762bb8f.png)

</details>

**Comment by briceduclos** [comment]
@melchoyce Facebook uses "Pinned Post" and Twitter uses "Pinned Tweet"

**Comment by carolinan** [comment]
But it is not called pinned in the WordPress editor: "Stick to the top of the blog"

**Comment by melchoyce** [comment]
Could this work?

![image](https://user-images.githubusercontent.com/2846578/96515046-9d339400-1232-11eb-8a36-31ca2602ae64.png)

**Comment by melchoyce** [comment]
If not, we could show this on archive pages, and make no changes on single:

![image](https://user-images.githubusercontent.com/2846578/96515115-c2c09d80-1232-11eb-8cdd-7ffa9dfcc594.png)

**Comment by melchoyce** [comment]
Semi-related: #550
