### ISSUE TITLE
Pagination links: the clickable area is too small

### ISSUE THREAD

**Issue by afercia** [WordPress/twentytwentyone#533]
**Describe the bug**
The clickable area of the various pagination links is a bit too small for a theme that aims to be WCAG level AAA "ready".

The posts pagination links have a target size of approximately 13 by 42 pixels:

![posts pagination](https://user-images.githubusercontent.com/1682452/96251166-5b93b680-0fb0-11eb-951d-c62f7d126e3c.png)

where the width is a bit too small for all users.

Similarly, the links of a paginated post have a clickable area that is too small:

![paginated post](https://user-images.githubusercontent.com/1682452/96251301-87af3780-0fb0-11eb-8158-08249c0e5d76.png)

Worth reminding that the WCAG Target Size (level AAA) success criterium requires a target size of 44 by 44 pixels, with some exceptions: https://www.w3.org/TR/WCAG21/#target-size

**Comment by carolinan** [comment]
With #524, the clickable size of the post pagination is 71x41 which is still not high/tall enough.

**Comment by JustinyAhin** [comment]
I think this has totally been solved by #570. Archives pages and search pages pagination have the text "Page" before the number of the page.

@carolinan @aristath?

**Comment by aristath** [comment]
They will still need to be at least 3px taller :wink: 
I haven't tested it but believe a small vertical padding in the links should fix this :+1:

**Comment by sarahricker** [comment]
@JustinyAhin @carolinan Looks like we need just a bit more. Possible to get this in before Beta 1?

**Comment by JustinyAhin** [comment]
> @JustinyAhin @carolinan Looks like we need just a bit more. Possible to get this in before Beta 1?

Commit coming in a couple of minutes @sarahricker

**Comment by JustinyAhin** [comment]
Let's fix that in Beta 2

**Comment by afercia** [comment]
Question: are there languages where the translation of "Page" would be a shorter word? Not sure about Western languages but it's likely the case for some Asian languages?

In any case, I'm not sure we can rely on the space taken by the word "Page" to make sure these links are at least 44 by 44 pixels. I'd consider to add a min-width and min-height anyways.
