### ISSUE TITLE
Mobile: Spacing issues

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#541]
**Describe the bug**
Testing trunk on Huawei P20 android 5.8inch 2244 × 1080 px.

The space between the pagination and the footer widgets takes up almost all the screen.
(This has been reported before).

The space between the newer posts and older posts link is very small.

**Screenshots**

Here I zoomed out, and you can see that the menu is causing the content to be too wide, because the border
does not stretch the full width, as reported in https://github.com/WordPress/twentytwentyone/issues/539

Chrome:

![thumbnail_Screenshot_20201016_150002_com android chrome](https://user-images.githubusercontent.com/7422055/96261435-bfbe7680-0fc0-11eb-9bc1-186d6911f555.jpg)

**Comment by carolinan** [comment]
I know the spacing has been brought up before and that it was intended.

But in my opinion, the text in the navigation on mobile is too close to each other.
Possible solutions:

- Place the text on separate lines.
- Reduce the text size. -This may not help if there are languages where this text is much longer than the English text.
The click target size still needs to be at least 44x44.
- Remove the part of the text that says "post"
Related: https://github.com/WordPress/twentytwentyone/issues/761 
- Remove the part of the text that says "post", but only on small screens.
(I believe this requires change of markup)

Any text changes must be finalized before November 10.

_Discarded:_
Only showing the arrows is not a good option for accessibility reasons.

**Comment by sarahricker** [comment]
@carolinan / @JustinyAhin Discussed this in a11y + Design Office Hours today. 

Ultimately landed on a preference to remove "post" from the link text on both sides, but keep it for the link title / screenreader text. 
This should help keep the context for visual users, while reducing cognitive load. It will also preserve design + click target without having to deep dive into last minute css changes.

**Comment by melchoyce** [comment]
If we can remove "post," I'm for that 👍 

We probably could reduce the vertical spacing here by one increment, it feels taller in this screenshot.
