### ISSUE TITLE
Mobile/ small screens: Let the comment text input fields be wider.

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#542]
**Describe the bug**
Testing trunk on Huawei P20 android 5.8inch 2244 × 1080 px.

**To Reproduce**
1. Reduce the browser window width
2. When logged out, view a post or page with a comments area
3. See that the name and email fields are narrow

**Expected behavior**
The fields should be easy to use.

**Screenshots**
![thumbnail_Screenshot_20201016_150555_com android chrome (1)](https://user-images.githubusercontent.com/7422055/96262924-b0402d00-0fc2-11eb-80a0-28de8bf74e86.jpg)

**Comment by melchoyce** [comment]
Ideally these should split onto two lines on small screens. 👍
