### ISSUE TITLE
blockquote styling

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwentyone#548]
The styles for a blockquote affect `blockquote p`, and change only the font size. There is no other indication that it is a quote. There appear to be styles for quote blocks, however. 
Just know that there are 15 years worth of legacy content out there, so not all sites will have the block markup.

**Expected behavior**
The theme should style HTML elements, not just WP blocks.

**Screenshots**
Theme Unit test page with legacy blockquote.
![Page Markup And Formatting – Local Current WP-55](https://user-images.githubusercontent.com/7957680/96280741-fafb7e00-0f9d-11eb-8fe5-c7094b9b8207.jpg)

Theme Unit test page with quote blocks.
![Block Quote – Local Current WP-46](https://user-images.githubusercontent.com/7957680/96280785-09e23080-0f9e-11eb-9055-3a45b868145d.jpg)

- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Firefox
 - Version 81.0

**Comment by melchoyce** [comment]
Thanks Joy!

We'll want to retest this once #513 lands.

**Comment by carolinan** [comment]
I can confirm that with #513 merged this is still a problem.
The "classic" blockquote element can be tested with the theme unit test page "Post Format: Quote"

**Comment by carolinan** [comment]
This has been solved, closing.
