### ISSUE TITLE
quote blocks with aligned text

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwentyone#549]
A quote block that has right aligned text is showing the border on the right also. This looks wrong to me, and probably gets by testing because the test data is short.
But switching to RTL mode, it looks even more wrong, because the text remains right and border is on the left.

**Expected behavior**
The border that denotes a blockquote should be on the leading side (left for LTR and right for RTL). The alignment of the text should not influence the border.

**Screenshots**
right aligned text in quote block, in LTR mode
![Block Quote – Local Current WP-46](https://user-images.githubusercontent.com/7957680/96282051-cab4df00-0f9f-11eb-855c-c51f8fe97f85.jpg)

right aligned text in quote block, in RTL mode
![Block Quote – Local Current WP-59](https://user-images.githubusercontent.com/7957680/96282033-c7215800-0f9f-11eb-8e01-c46bed2aa2b8.jpg)

**Comment by carolinan** [comment]
The design for the block quote has not been merged yet, this will be replaced.

**Comment by melchoyce** [comment]
We'll also want to make sure to test this one once #513 lands. We don't have a border, but we'll want to make sure the quotation icon flips, I think?

**Comment by ryelle** [comment]
Here's what this looks like now that #513's merged — do the quote marks need to flip? Note: RTL is using Tahoma as the default font, not the system font, so the quote icons look different.

| LTR | RTL |
|-----|-----|
| ![Screen Shot 2020-10-19 at 1 25 00 PM](https://user-images.githubusercontent.com/541093/96490199-7fecce80-120e-11eb-8fbe-8d30a5ba322a.png) | ![Screen Shot 2020-10-19 at 1 21 10 PM](https://user-images.githubusercontent.com/541093/96490175-76636680-120e-11eb-9f9d-13f648b20ad0.png) |

**Comment by melchoyce** [comment]
Would love some input from folks who natively use RTL languages!

**Comment by joyously** [comment]
The bottom one in the screenshot has right aligned text, and is still wrong. The quote should be on the left for LTR, and on the right for RTL.

**Comment by aristath** [comment]
> The bottom one in the screenshot has right aligned text, and is still wrong. The quote should be on the left for LTR, and on the right for RTL.

Not if the user explicitly right-aligns the quote. It's their choice.

**Comment by joyously** [comment]
Well, the block is not right aligned, just the text is right aligned. The reading direction didn't change.

**Comment by sarahricker** [comment]
Discussed this in [a11y + Design Office Hours today](https://wordpress.slack.com/archives/C02S78ZAL/p1605021770384600).

There are some obvious concerns with aligning the blocks / content for english users simply wishing to left/right align their blockquotes, such as: 

- the text aligns right, but the leading quote now looks like an ending quote
- the text aligns right, but the leading quote is aligned to the block, not the text, creating a gap

However, there is still some debate about how everything should apply in RTL languages, as we may be missing something seeing it in "English-like" text. 

@naokomc could you help us review this feature in a RTL language and get some feedback from #polyglots team? Thank you!

**Comment by carolinan** [comment]
The editor and front does not match:

Editor:
![quote-editor](https://user-images.githubusercontent.com/7422055/98805370-c0a7c400-2417-11eb-91f0-d7b4770afa29.png)

Front:
![quote-front](https://user-images.githubusercontent.com/7422055/98805485-e8972780-2417-11eb-9c34-cd4272d83d76.png)


For earlier design decisions see: https://github.com/WordPress/twentytwentyone/pull/513

**Comment by naokomc** [comment]
> However, there is still some debate about how everything should apply in RTL languages, as we may be missing something seeing it in "English-like" text.

I [pinged Arabic/Hebrew/Persian polyglots yesterday](https://wordpress.slack.com/archives/C02RP50LK/p1605063543202000?thread_ts=1605023313.199800&cid=C02RP50LK) but haven't heard back. 

According to https://en.wikipedia.org/wiki/Quotation_mark, `quotation mark pairs with the convexity pointing outward` (“...”) seems to be the most commonly accepted among various languages including Arabic (which lists them as Alternative - Primary).

Some languages including Hebrew & Persian don't have the type of marks listed as Standard or Alternative, but it's possible that they are ok as stylistic representation (for example, Japanese use「...」for native characters, but “...” is also recognized and used when Latin characters appear within the text).

**Comment by farhadsakhaei** [comment]
Hi
I am Locale Manager of Persian language
For Persian and I think for Arabic you can use « and » for quotes
**Example:**
«گیومه»
Here is related documentation: https://fa.wikipedia.org/wiki/%D8%B9%D9%84%D8%A7%D9%85%D8%AA_%DA%AF%D9%81%D8%AA%D8%A7%D9%88%D8%B1%D8%AF
But remember to use Persian texts when you are testing RTL direction, Because sometimes browsers replace some elements when they occur RTL text
So in all test for RTL, use RTL text
You can use this text for testing purposes for Persian (And also Arabic tests):

علامت گفتاورد یا علامت نقل قول انگلیسی نشانه‌ای است که در زبان‌های گوناگون (ولی نه در زبان فارسی) برای نشان دادن گفتاورد به کار برده می‌شود. در زبان فارسی، به جای این نشانه باید از نشانهٔ «گیومه» استفاده کنیم.

Any thing I can do?

**Comment by melchoyce** [comment]
Anything left on this with https://github.com/WordPress/twentytwentyone/pull/832 merged?
