### ISSUE TITLE
Remove period after footer meta categories

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentytwentyone#550]
**Describe the bug**
On archive pages, a there is a period after the category list, but no periods after any other meta content. There aren't any periods in single post meta, so let's remove this one as well.

**Screenshots**

**Before:**
![image](https://user-images.githubusercontent.com/2846578/96281145-ee2f5800-0fa6-11eb-92a3-ebfbe036daef.png)

**After:**
![image](https://user-images.githubusercontent.com/2846578/96282402-b1646080-0fa8-11eb-8631-59e07f7e42f1.png)

**Comment by jordesign** [comment]
I'm happy to lay claim to this one! PR coming...

**Comment by jordesign** [comment]
Interesting point with this one - the rationale seems to be having trailing periods when _both_ category and tag are listed...

![Screen Shot 2020-10-17 at 10 15 41 pm](https://user-images.githubusercontent.com/1842363/96335743-69d3f680-10c6-11eb-8f84-3e15d1ef6763.jpg)

This makes sense when both are showing - but if _only_ categories _or_ tags are showing I feel like dropping it works?

**Comment by jordesign** [comment]
Or we could try something like this?

![Screen Shot 2020-10-17 at 11 04 51 pm](https://user-images.githubusercontent.com/1842363/96336684-33e64080-10cd-11eb-9c89-6fcc0d98a3f9.jpg)

**Comment by carolinan** [comment]
@jordesign If you are able to work on this today, please use the style and instructions in the first comment. :)

**Comment by jordesign** [comment]
Hey @carolinan - are you referring to this?

> this makes sense when both are showing - but if only categories or tags are showing I feel like dropping it works?

**Comment by carolinan** [comment]
No I am reffering to the issue description.

**Comment by jordesign** [comment]
Thank @carolinan -  I understand.

The trouble is that when the period is removed and there are both tags and categories - the two run together like 

`Categorized as Classic, Markup Tagged content, css, formatting`

This makes it really difficult to use/read

**Comment by melchoyce** [comment]
In the mockups, everything had a period, which fixed the inconsistencies:

![image](https://user-images.githubusercontent.com/2846578/96514667-f222da80-1231-11eb-88a0-5bcc3d58cc3f.png)

But at some point I remember saying something about the periods messing things up for translators — is that accurate? If so, we can go with:

![image](https://user-images.githubusercontent.com/2846578/96514945-72494000-1232-11eb-808e-5df0b7acdba1.png)

Whatever's easiest.

**Comment by melchoyce** [comment]
Semi-related: #532

**Comment by jordesign** [comment]
Thanks @carolinan.

![](https://user-images.githubusercontent.com/2846578/96514667-f222da80-1231-11eb-88a0-5bcc3d58cc3f.png)
[link to image](https://user-images.githubusercontent.com/2846578/96514667-f222da80-1231-11eb-88a0-5bcc3d58cc3f.png)

This mockup matches the current behavior of the theme - which is periods after *both* items.

 I still think that makes sense - which would mean we can close this issue?

**Comment by melchoyce** [comment]
No, because there aren't periods after "published" and "edit" in the theme right now:

![image](https://user-images.githubusercontent.com/2846578/96619425-2f3fa900-12d4-11eb-8bd4-3f64b4d51afb.png)

Whatever solution we go with to fix this just needs to be consistent.

**Comment by jordesign** [comment]
Ah gotcha! And on the single view - we don't have periods after _any_ of the meta items. So my proposal would be to go back to the original intent of this issue - and remove the periods.

On single views 'Category' and 'Tag' are on their own lines so we could the same here for consistency?

Single:
![Screen Shot 2020-10-21 at 7 18 23 am](https://user-images.githubusercontent.com/1842363/96639577-a2492e00-136d-11eb-974f-d49f61564b71.jpg)


Archive:
![Screen Shot 2020-10-21 at 7 03 14 am](https://user-images.githubusercontent.com/1842363/96638220-847ac980-136b-11eb-91f8-39cb41f5d830.jpg)
