### ISSUE TITLE
pre tag is not preserving whitespace

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwentyone#553]
The `pre` tag is supposed to preserve whitespace, but it is using 
`pre {white-space: pre-wrap}`
which does not.
The font size should probably be reduced a bit, since it's monospace.

**Screenshots**
It looks like this mess:
![pre-tag](https://user-images.githubusercontent.com/7957680/96286177-9ba16c00-0fa5-11eb-8e84-80e6027deb74.jpg)

If the `pre {white-space: pre-wrap}` rule is disabled, it looks better, but has a scrollbar. So if you use 
`pre {overflow-x: auto}`
it looks like this:
![pre-tag-overflow](https://user-images.githubusercontent.com/7957680/96286314-cf7c9180-0fa5-11eb-9570-8cfd2cf90547.jpg)

**Comment by ryelle** [comment]
It looks like the decision to wrap the text was made in https://github.com/WordPress/twentytwentyone/pull/190, I think to better match the way the preformatted block works in the editor.

**Comment by joyously** [comment]
If the editor changes the definition of the `pre` tag, that doesn't mean that the theme should. That decision affects legacy content that was entered with the definition of `<pre>` meaning *pre*serving whitespace. (See screenshot)

**Comment by carolinan** [comment]
So what needs to be done here is to change it to `pre {overflow-x: auto}` for both the editor and front.
But also to make sure that the font sizes matches in the editor and the front.

For the front, see https://github.com/WordPress/twentytwentyone/blob/trunk/assets/sass/04-elements/misc.scss#L14

**Comment by carolinan** [comment]
Just adding this as a reminder: A ticket needs to be opened for the preformatted block on the Gutenberg repo since the style we need to override is added inline.
