### ISSUE TITLE
Pages widget does not show the nesting of the pages

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwentyone#554]
The Pages widget does not show the nesting of the pages.
I see in the Dev tools that the menu has
`.widget-area ul.sub-menu {margin-left: var(--widget--spacing-menu); }`
which would not apply to the Pages widget.

**Screenshots**
This screenshot shows an ugly search widget, a Navigation widget that shows the nesting, and a Pages widget which does not show the nesting.
![widgets](https://user-images.githubusercontent.com/7957680/96287042-f25b7580-0fa6-11eb-9dc9-6ee9d70d7cbc.jpg)

**Comment by melchoyce** [comment]
Let's nest up to 3 levels here 👍 

The spacing used in the navigation widget is good.
