### ISSUE TITLE
Page title is too large

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwentyone#562]
Even a not very long page title takes up the entire viewport, because the font size is so large and the content width is narrow.
It makes it hard to read.
![Template Password Protected (the password is “enter”) – Local Current WP-33](https://user-images.githubusercontent.com/7957680/96309826-aec73280-0fcb-11eb-91f0-258c01eb5b23.jpg)

**Comment by naokomc** [comment]
I'm testing with Japanese contents, and I agree with this as well.

![image](https://user-images.githubusercontent.com/34067/96398472-eec62980-1206-11eb-86cd-bf1fd8e26821.png)

It's hard to convey with a screenshot but h1 especially seems very large. Please check [this demo site](https://wptestsite.o0o0.jp/2013/01/11/markup-html-tags-and-formatting/) for the actual display.

Japanese and Chinese fonts tend to occupy wider space compared to English ones.
https://www.w3.org/International/articles/article-text-size.en ("次檢視", a 3-letter word in Chinese, is 1.2 times wider than "views", a 5-letter word).

I personally feel 60px or even smaller is a "comfortable" size for Japanese titles.

**Comment by joyously** [comment]
Ooooo, go to that demo site and click on Next Post! What a big title! I have to hit Page Down 3 times to see the actual content. (but that's a long title)

**Comment by naokomc** [comment]
I'm using [a Japanese version](https://github.com/jawordpressorg/theme-test-data-ja/blob/master/wordpress-theme-test-data-ja.xml) of the Theme Unit Test and the post you found is a translation of the "[Post With Long Title](https://codex.wordpress.org/Theme_Unit_Test#Post_With_Long_Title)" :)

**Comment by carolinan** [comment]
What screen resolution is this tested on?

**Comment by naokomc** [comment]
Mine was 2560 x 1440.

**Comment by aristath** [comment]
Added design tags, pinging @melchoyce and @kjellr 

Personally I don't consider this a problem... It's a styling choice and it's one I quite like, but we'll need to wait for feedback before taking any further steps.

**Comment by joyously** [comment]
Mine was on a laptop, window width of 1040px.

**Comment by joyously** [comment]
I just downloaded a new zip of the theme, and the screenshot says it all: it's all title!
![screenshot](https://user-images.githubusercontent.com/7957680/96459599-e7435800-11e7-11eb-925c-8c15f18bb89f.png)

**Comment by melchoyce** [comment]
That's a specific block pattern using an intentionally large font size, even larger than the page/post title. The theme uses big font sizing as an aesthetic choice.
