### ISSUE TITLE
Featured image is assumed to be large

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwentyone#563]
When using a small featured image, the CSS uses 
`min-width: var(--responsive--aligndefault-width)` which makes the image blurry.
The image in this test is 165px wide. 

![blurred-featured-image](https://user-images.githubusercontent.com/7957680/96310251-a28fa500-0fcc-11eb-9a15-aa0ffe46f806.jpg)

Without that one rule, it looks like it should:
![normal-featured-image](https://user-images.githubusercontent.com/7957680/96310331-cb179f00-0fcc-11eb-922d-d1dd08820880.jpg)

**Comment by carolinan** [comment]
The themes post thumbnail size is set to: `set_post_thumbnail_size( 1200, 9999 );`
I am going to label this as low priority because the user can regenerate their thumbnails using a plugin.

**Comment by joyously** [comment]
The user shouldn't have to use a plugin to make their site look right when switching themes.
The image size created is only for new images. The old images should still be shown as the user entered it.
Even if a user regenerated thumbnails, smaller images are not expanded to be larger, and the CSS would still make it blurry. The CSS actually goes against the `srcset` and `sizes` that WP adds.

**Comment by joyously** [comment]
This issue is very noticeable in the Theme Unit Test data, especially on the vertical featured image. It looks blurry at my normal window width of 1040px, but when I use fullscreen of 1908, the image is huge and awful and in the way.
The theme should work with the images as they are, not force them to be wider than intended.

**Comment by aristath** [comment]
No theme will ever work the way everyone wants it for all content. Not all content will show beautifully in all themes, all themes have opinions about how content should be formatted, and some styles will always be a bit opinionated. This is one of those cases. It's not good or bad, it's just how twentytwentyone handles featured images.

Honestly I don't see this as an issue. Does the image look blurry if it's small? It sure does. Would it be better if it was shown at its original size? That's debatable. Some people prefer sharp images, others find a visual layout/width consistency more important. 

Ultimately this is a content issue, not a theme issue. If the featured image is too small, then it won't appear perfectly no matter what we do.

**Comment by joyously** [comment]
Consider this from the perspective of theme authors learning from the default theme. It is better to promote CSS that allows any image size than CSS that forces the browser to upscale small images.

Also consider that the user could have 2000 posts with various images sizes that happened over many years, different authors, and different themes. Just because they switch to a different theme doesn't mean that their featured image should be changed across all those posts.
The theme should be flexible about the user's choices of image size, especially featured images, which there are no settings for.

This adversely affects two situations: one is the small image, but the other is the vertical image. Because the size is controlled by the width, the small image gets blurry and the vertical image gets abnormally tall. This is not a good model for new theme authors.

**Comment by joyously** [comment]
I just want to add that most people try to fix CSS problems that cause distortion or difficulty in reading the user's content, such as white on white text or underlines on titles or illegible fonts. Changing the user chosen size of images, making them blurry or too large, is the exact same thing.

**Comment by aristath** [comment]
fixed in #800
