### ISSUE TITLE
form input styling

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwentyone#565]
The `<fieldset>` element has no padding.
The input boxes have too much padding.
The date input has a different background color.

**Screenshots**
This is on the front end.
![LTR-inputs](https://user-images.githubusercontent.com/7957680/96318240-cd7df700-0fd4-11eb-9ce7-4603bc986098.jpg)

**Comment by carolinan** [comment]
The date input background is always white because there is default text inside it. If the background color was changed, the text color would need to be changed too to maintain the contrast.

**Comment by JustinyAhin** [comment]
What if we make these fields design consistent with the comment form @carolinan?
![Screenshot_2020-10-19 #565 – trunk wordpress test](https://user-images.githubusercontent.com/33403964/96419404-004e0800-11ec-11eb-8f3f-bbfa45d8301d.png)

**Comment by joyously** [comment]
This change was merged, but it is **not** an improvement. The theme will mess up any existing form I might have had laid out. Inputs now take up a LOT more screen space.
Making them all wide doesn't fit each type of input, especially the button type.
And the date type still doesn't make sense to be a different color. The time type also has a placeholder and it isn't white.

![inputs](https://user-images.githubusercontent.com/7957680/96952928-910b3900-14b5-11eb-8cb1-2f476bc31880.jpg)
