### ISSUE TITLE
wrong handling for custom post type

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwentyone#566]
Looking at the single post page for a custom post type, there are no links at the bottom for the other posts, unlike the standard post type.

Also, my custom post type does not support "author", yet it shows the author bio at the bottom.

![my test job – Local Current WP-18](https://user-images.githubusercontent.com/7957680/96319878-78db7b80-0fd6-11eb-8978-495e7c73c82c.jpg)

**Comment by joyously** [comment]
<s>I just thought I'd mention that I saw a standard post without the post navigation links also. But most standard posts have them.</s>
Edit: Don't mind this comment, as it was a Page I saw, not a Post.

**Comment by carolinan** [comment]
I don't think that it is up to the theme to support the navigation of custom post types.
The custom post type will be added by plugins or child themes. They can also add the navigation and or a specific template that shows the content correctly.

The current navigation is placed inside this if statement: `if ( is_singular( 'post' ) ) {`
If the post part of the if statement is removed, the navigation will work, but the text is still going to read **Next Post**.
**Post** may not be correct term for the custom post type, therefor it is better to handle this in the child theme or plugin.

**Comment by joyously** [comment]
I think the theme should provide navigation if its template is loaded. It shouldn't say post though. Using 'Next' and 'Previous' would work fine.
But the author support should be checked before outputting that section.
