### ISSUE TITLE
confusing search results

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwentyone#567]
The search page seems to have a mixture of excerpts and content. Some show featured images, but most do not. (is this due to post formats? --well maybe not since there is a featured image showing on a custom post type)
Also, the "Older Posts" link is on the right, which is opposite how the other pages do it.

![Search Results for “gallery” – Local Current WP-48](https://user-images.githubusercontent.com/7957680/96320383-dae8b080-0fd7-11eb-9a93-bcfd15e434b4.jpg)

![Search Results for “test” – Local Current WP-25](https://user-images.githubusercontent.com/7957680/96320944-73336500-0fd9-11eb-8f03-6abe8d09d549.jpg)

**Comment by carolinan** [comment]
> Also, the "Older Posts" link is on the right, which is opposite how the other pages do it.

When I double check, it is on the right side on all pages. Because the results are presented with the newest first, the link position and text is correct.

**Comment by carolinan** [comment]
Pages with featured images show the image in the search result for me, both newly created pages and the theme unit test, please confirm this.

**Comment by joyously** [comment]
I'm realizing now that this test site didn't have the same featured image as my usual test site. Sorry about that. So, the only difference with the images is that post formats are showing more content in the search than anything else does. Seems like they should show the same as everything else in the search results.

As for the Older posts link, it _was_ opposite of expected. I just downloaded a new zip of the theme, and it does indeed match the category page links. But I still expect Older to be on the left, because when I read a book I turn the page from the right to get the newer pages, and turn the page from the left to read older pages (chapter one is to the left, chapter two is to the right). And reverse that for RTL. Because the posts sort by default as the latest one first, "next page" is older, so it should be on the left, like a book.

**Comment by aristath** [comment]
> But I still expect Older to be on the left, because when I read a book I turn the page from the right to get the newer pages, and turn the page from the left to read older pages

The web is not a book. Recent posts are first and then older posts are last. In book terms, we're starting to read a book from the last page, not the beginning. With that in mind, the current placement of the links makes perfect sense.
