### ISSUE TITLE
Update custom logo settings, including title and tagline

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#57]
In addition to https://github.com/WordPress/twentytwentyone/pull/56/,

- [x] the `unlink-homepage-logo` needs to be added to the theme support for custom logo.
See https://make.wordpress.org/core/2020/07/28/themes-changes-related-to-get_custom_logo-in-wordpress-5-5/

<del>- [ ] Apply the different design and positions of the logo and site title
https://www.figma.com/file/OEtsCj8oD8JPVx4OvsS0U2/Twenty-Twenty-One?node-id=468%3A328
https://www.figma.com/file/OEtsCj8oD8JPVx4OvsS0U2/Twenty-Twenty-One?node-id=487%3A17</del>

- [x] A decision is needed regarding the logo size limit, currently set to 240x240 with no option to change the size.
See https://github.com/WordPress/twentytwentyone/blob/trunk/functions.php#L84
https://github.com/WordPress/twentytwentyone/blob/trunk/assets/sass/01-settings/global.scss#L160

- [x] Add option for retina logo
See https://themes.trac.wordpress.org/browser/twentytwenty/1.5/classes/class-twentytwenty-customize.php#L65
https://themes.trac.wordpress.org/browser/twentytwenty/1.5/functions.php#L66

- [x] Display logo in site footer

- [ ] Adjust footer logo size.

**Comment by carolinan** [comment]
> I'm thinking a max of 300px wide, or 100px tall?

 The option only has one regular size, and one for the retina that we will add. It does not accept min or max size values, but I'll do my best and we can test and alter the values.

**Comment by LittleBigThing** [comment]
Why don't we make the ‘retina logo‘ the default and drop the (theme) option? And simply recommend the higher (‘retina‘) image size. Or am I missing something?

**Comment by briceduclos** [comment]
Currently, the retina option scales the logo to half its uploaded size (x2). However, more and more devices now have higher screen density (x3.5). So a x2 logo would appear blurry and not sharp on them. As it’s not possible to upload svg, a solution might be to replace the “Retina logo” checkbox with a “Logo width” input number.

**Comment by aristath** [comment]
TBH I don't think we even need a retina option... As mentioned above most devices nowadays are hi-res. Additionally, logos are by definition small in size and therefore filesize. Users can upload a 700px-wide logo if they want, and it will be constrained to the dimensions specified. Works perfectly fine for all devices and the worst that can happen is lo-res devices downloading a couple of extra kilobytes.

**Comment by pattonwebz** [comment]
HTML has a method to handle this - via `srcset` - which accounts for images for those who have different pixel densities. If we explicitly add retina logo support in the theme we should use the `srcset` for it. 

If we just implement a method where size is set and we would expect users to upload images that are multiples of the fixed size how and where do we instruct them to do it?

**Comment by aristath** [comment]
> If we just implement a method where size is set and we would expect users to upload images that are multiples of the fixed size how and where do we instruct them to do it?

We don't. Users are not _expected_ to upload a logo multiple times the size used... Whatever they upload will be used :laughing:

**Comment by pattonwebz** [comment]
> We don't. Users are not _expected_ to upload a logo multiple times the size used... Whatever they upload will be used

Is that just not having explicity support for a retina logo then? :laughing: That suit me though :stuck_out_tongue:

**Comment by aristath** [comment]
If by "explicitly support" we mean having a different implementation for retina logos and requiring users to upload 2 logos (one for normal and one for retina) then yes, I'd rather not have it explicit but implicit. Visually indistinguishable result, half the cognitive load for users and lighter implementation for the theme.
The theme does have retina logo support - provided the user uploads a large enough logo. If they upload a 2000px-wide logo it will even work for 8x pixel-density 5 years from now.

**Comment by pattonwebz** [comment]
> half the cognitive load for users and lighter implementation for the theme

:+1: :heart:

**Comment by LittleBigThing** [comment]
We do suggest a logo size (Twenty Nineteen):

<img width="321" alt="Screenshot 2020-10-02 at 16 05 37" src="https://user-images.githubusercontent.com/5901923/94932416-53744b00-04c9-11eb-8b14-70766dfe097d.png">

And the custom logo has support for responsive images. So we could suggest to upload a larger sized images but don't restrict anything size-wise? If it smaller, it is smaller and not that crystal clear on higher density screens.

**Comment by aristath** [comment]
Well, then we can just change the recommended size there and be done with it :+1:

**Comment by LittleBigThing** [comment]
In Twenty Twenty, we adjust the HTML width and height attributes. I'll link the function that was used. But that might not be necessary without having the option.
https://github.com/WordPress/twentytwenty/blob/6d0a5240af108d02f58ec797fd49b32458a4c698/functions.php#L274

**Comment by melchoyce** [comment]
Doesn't WordPress resize the image you choose for a logo to make the size match the specified logo width, though? Even before we added this setting, if I uploaded a 2000px wide image, it still got super crunched and fuzzy.

**Comment by ryelle** [comment]
The `get_custom_logo` function will get the full logo image, but whether it's cropped or not depends on the `flex-*` properties here

https://github.com/WordPress/twentytwentyone/blob/118e3d585da225fe600d2ee6c77bc955a62e42cf/functions.php#L98-L99

With both of those set to `true` (which they are in Twenty Twenty), the image is not strictly cropped to the given size, so you can upload a 2000x2000 image, and if you "skip cropping" it'll use the full image complete with `srcset`. If you don't skip cropping, it actually crops to an aspect ratio, so in TT1 you'd get a 2000x666 image output. Then it's up to the CSS to display it at the correct size.

**Comment by carolinan** [comment]
Who can work on a second pull request to remove the retina logo option and related code?

**Comment by ryelle** [comment]
I've got one in progress, I just got sidelined by some of the responsive code. I can have it up today though :)

**Comment by carolinan** [comment]
Closing this as complete. It is difficult to get an overview of the conversation, a new bug issue has been created instead.
