### ISSUE TITLE
Heading and Paragraph blocks have unwanted side paddings inside the editor

### ISSUE THREAD

**Issue by briceduclos** [WordPress/twentytwentyone#575]
**Describe the bug**
Heading and Paragraph blocks have unwanted side paddings inside the editor when they are placed inside a full-width block.

**To Reproduce**
1. Inside the code editor, paste the following code (a full width group which contains an image, a heading, and a paragraph):

```
<!-- wp:group {"align":"full","backgroundColor":"white"} -->
<div class="wp-block-group alignfull has-white-background-color has-background"><div class="wp-block-group__inner-container"><!-- wp:image {"sizeSlug":"large"} -->
<figure class="wp-block-image size-large"><img src="https://raw.githubusercontent.com/WordPress/twentytwentyone/trunk/assets/images/Reading.jpg" alt=""/></figure>
<!-- /wp:image -->

<!-- wp:heading -->
<h2>Heading</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, commodo erat adipiscing elit. Sed do eiusmod ut tempor incididunt ut labore et dolore.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:group -->
```

2. Observe that the heading and paragraph have side paddings, they aren’t aligned with the image.
3. View the page on the front, observe that the heading and paragraph are correctly aligned with the image.

The padding in the editor is due to the following CSS https://github.com/WordPress/twentytwentyone/blob/f7c3917b5bd473bba344dec69bd4acdf803e0d5f/assets/css/style-editor.css#L656-L665
that was added in https://github.com/WordPress/twentytwentyone/pull/387

**Screenshots**

Editor:
![block-unwanted-padding](https://user-images.githubusercontent.com/56188815/96369543-f6c88f80-115a-11eb-8491-718e101426d0.jpg)

Front
![block-front](https://user-images.githubusercontent.com/56188815/96369544-f7f9bc80-115a-11eb-9787-6d748ee9f9e0.jpg)

**Comment by kjellr** [comment]
Yeah, I think this can be more specific. I suggest adding this padding only for the first and last column, and only for the whichever side is going to bump up against the edge of the screen.

**Comment by carolinan** [comment]
All sides and columns bumps up against the edge for columns on small screens. Since the columns turn vertical.

**Comment by kjellr** [comment]
Yes, that's right. So they should have margins on small screens, but we can (at least try out) more selective margins on larger screens.

**Comment by carolinan** [comment]
Looking at the history, I believe this CSS was only meant to affect the columns block.

Fixed with https://github.com/WordPress/twentytwentyone/commit/47b7ac4dc1f412bc48d996ba683f3d8b0b0c7948 (Yes I forgot to make branch and PR first ;) )
