### ISSUE TITLE
Minor Translation Improvments

### ISSUE THREAD

**Issue by desrosj** [WordPress/twentytwentyone#602]
**Describe the bug**
While reviewing the theme for Core commit, I noticed a few small things related to translations and/or translation comments that would be nice to fix.

- There are several translation strings that include a trailing space. These strings are accompanied by a translator comment, it would probably be better to move the space outside of the translation string and concatenate after (all but one occurrence has additional text added after anyway). This would also allow us to remove the translator comments here.
- There are [some one or two letter strings](https://github.com/WordPress/twentytwentyone/blob/7f8be7628814b1d969b1b0b205ea3d56c235c1a4/functions.php#L148) that don't have context for translators. It's clear with the context of the code that they represent sizes, but it may not be clear elsewhere.
- Also wanted to confirm that [this string](https://github.com/WordPress/twentytwentyone/blob/7f8be7628814b1d969b1b0b205ea3d56c235c1a4/functions.php#L160) is supposed to be `M` and not `N`.
- `This theme requires at least WordPress version 5.3.` reads a bit weird for me. `This theme requires WordPress 5.3 or newer.` feels a bit smoother instead?
- There are some occurrences of "we" and "our" within the inline documentation. These should be avoided as much as possible for clarity.
- There are a few variables that are not set ([$post](https://github.com/WordPress/twentytwentyone/blob/trunk/image.php#L55) and [$wp_query](https://github.com/WordPress/twentytwentyone/blob/trunk/search.php#L36)). Just wanted to call this out to double check in testing that these are not problematic. For `$post`, `get_post()` could be used instead, perhaps?

**Comment by aristath** [comment]
> There are several translation strings that include a trailing space. These strings are accompanied by a translator comment, it would probably be better to move the space outside of the translation string and concatenate after (all but one occurrence has additional text added after anyway). This would also allow us to remove the translator comments here.

Most were already removed in https://github.com/WordPress/twentytwentyone/commit/4811e90977f1de81bafe447c1f854a0abae318c6

There are now only 2 remaining, and they are there to make RTL translations easier:

https://github.com/WordPress/twentytwentyone/blob/a1f5991d0f7941171585de22a14af4163e0bb304/comments.php#L63
https://github.com/WordPress/twentytwentyone/blob/a1f5991d0f7941171585de22a14af4163e0bb304/inc/template-tags.php#L219

> There are some one or two letter strings that don't have context for translators. It's clear with the context of the code that they represent sizes, but it may not be clear elsewhere.

Good point. PR: https://github.com/WordPress/twentytwentyone/pull/604

> Also wanted to confirm that this string is supposed to be M and not N.

Took me a minute too, but I believe that is correct. Following the small/large etc pattern, M looks correct as medium - just like XXXL is used for Gigantic instead of G :+1: 

> `This theme requires at least WordPress version 5.3.` reads a bit weird for me. `This theme requires WordPress 5.3 or newer.` feels a bit smoother instead?

Agreed. PR: #605 

> There are some occurrences of "we" and "our" within the inline documentation. These should be avoided as much as possible for clarity.

PR: #606

**Comment by aristath** [comment]
> There are a few variables that are not set ([$post](https://github.com/WordPress/twentytwentyone/blob/trunk/image.php#L55) and [$wp_query](https://github.com/WordPress/twentytwentyone/blob/trunk/search.php#L36)). Just wanted to call this out to double check in testing that these are not problematic. For `$post`, `get_post()` could be used instead, perhaps?

I created a new issue for that: https://github.com/WordPress/twentytwentyone/issues/609

Since all other issues mentioned here have been fixed and all related PRs merged, I'll go ahead and close this one :+1:

**Comment by desrosj** [comment]
Thank you, @aristath!

> Took me a minute too, but I believe that is correct. Following the small/large etc pattern, M looks correct as medium - just like XXXL is used for Gigantic instead of G 👍

Got it! My brain immediately thought N for Normal with the pattern before it XS (extra small), S (small), and L (large) right after it,
