### ISSUE TITLE
Avoid using possibly-unset global vars $post and $wp_query

### ISSUE THREAD

**Issue by aristath** [WordPress/twentytwentyone#609]
Came up in #602:

> There are a few variables that are not set ([$post](https://github.com/WordPress/twentytwentyone/blob/trunk/image.php#L55) and [$wp_query](https://github.com/WordPress/twentytwentyone/blob/trunk/search.php#L36)). Just wanted to call this out to double check in testing that these are not problematic. For `$post`, `get_post()` could be used instead, perhaps?

**Comment by Abdujabbar** [comment]
@carolinan I see still exists $post variables(for example: image.php), we will replace it with `get_post()` method or we leave them?

**Comment by aristath** [comment]
These globals are only used in the `image.php` template. That template is only used when displaying an attachment - in which case the `$post` and `$wp_query` globals are **always** set.
Closing this one since after further examination it's not an issue.
