### ISSUE TITLE
Add notice to colorpicker when entering the customizer with dark mode enabled

### ISSUE THREAD

**Issue by aristath** [WordPress/twentytwentyone#614]
If we enter the customizer from a device that has dark-mode enabled, the preview shows dark-mode but the colorpicker shows a different color. The selected color is then only previewed when the user changes the background-color:

![Screenshot_2020-10-20 Customize My Blog](https://user-images.githubusercontent.com/588688/96580632-3de08d00-12e1-11eb-8211-fc1880e97d36.png)

That can be confusing, so a notice that would explain what goes on should be added to the customizer setting.
This way, when the user goes to the "colors" section they will see the colorpicker, below that the notice that explains what they see, and as soon as they change the color the notice goes away.

**Comment by melchoyce** [comment]
Is it technically possible to ignore dark mode while in the Customizer?

**Comment by aristath** [comment]
> Is it technically possible to ignore dark mode while in the Customizer?

Sure is... I can add a check and only add the HTML class if not in the customizer.
