### ISSUE TITLE
Dark Mode: Reduce image brightness & contrast

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentytwentyone#618]
**Describe the bug**
In dark mode, images appear brighter because they're against a dark background, which can cause eye strain. What if we reduced the brightness and contrast to make images easier on the eyes?

**Screenshots**

Before | After
------------ | -------------
![image](https://user-images.githubusercontent.com/2846578/96638530-45f2f980-12ee-11eb-8ee4-12ae17a4d9a5.png) | ![image](https://user-images.githubusercontent.com/2846578/96638616-691da900-12ee-11eb-8522-53b6ceee0d3d.png)

This uses:

`filter: brightness(.85) contrast(1.1);`

**Additional context**
This is a suggestion in https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/.

**Comment by carolinan** [comment]
I am not a dark mode user, but I would not expect this.
If I wanted a filter over my images, I would want to decide that myself, and I would use a cover block.

**Comment by hedgefield** [comment]
I've seen this method used more often in dark mode themes yeah, also by reducing saturation a little bit. I don't find it such a bad idea, I have certainly had my eyes hurt from bright colorful images during a dark mode situation. But I can imagine if images are super important on your site, or you already authored them to look good in a dark mode theme, you'd be peeved that there's something in the theme that messes with them. It's probably not trivial to put this behind a theme option toggle huh? I like the feature, but feels like something that each theme user should be able to opt into or out of.

**Comment by ryelle** [comment]
There are other discussions ongoing in other issues, but there already is a theme option that site owners can use to turn off `prefers-color-scheme` support. So if the design/images are very important, they can turn it off.

**Comment by hedgefield** [comment]
Wouldn't that disable dark mode entirely?

**Comment by aristath** [comment]
yes, it would.

**Comment by aristath** [comment]
During Friday's meeting it was decided to remove everything related to dark-mode and instead put that feature in a plugin as a safety precaution. dark-mode was removed in https://github.com/WordPress/twentytwentyone/pull/690 and moved in a plugin, with the hope that it can be re-integrated in the theme if we're satisfied with its implementation.
Closing this issue.

**Comment by carolinan** [comment]
This is already included, closing.
