### ISSUE TITLE
Dark Mode: Should we reduce the opacity of borders, dividers, and separators?

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentytwentyone#620]
**Describe the bug**
Slightly darker borders would help reduce eye strain from too much contrast, and would also blend in better with the dark color scheme.

**Screenshots**

Before | After
----- | -----
![image](https://user-images.githubusercontent.com/2846578/96639828-455b6280-12f0-11eb-9bd0-a478283bdd06.png) | ![image](https://user-images.githubusercontent.com/2846578/96639906-602dd700-12f0-11eb-900c-d0485475b891.png)

Before | After
----- | -----
![image](https://user-images.githubusercontent.com/2846578/96640036-953a2980-12f0-11eb-88f8-6fd66ec977f3.png) | ![image](https://user-images.githubusercontent.com/2846578/96640022-8eabb200-12f0-11eb-8af1-bb65f9ddb3e2.png)

**Additional context**
This idea comes from https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/.

**Comment by melchoyce** [comment]
I used 30% opacity in the above "after" screenshots, but we'd want to use an opacity that still lets us meet 4.5:1 contrast — maybe 55%?

**Comment by carolinan** [comment]
This was already tested once and not implemented.

**Comment by hedgefield** [comment]
I agree this looks better, puts more visual emphasis on what's actually important on the page. I think @carolinan was referring to https://github.com/WordPress/twentytwentyone/pull/155, I asked her about it and she's in favor of doing this, so yay 🎉  The AAA contrast ratio is important still yeah, so if 55% works for that, great 👍

**Comment by carolinan** [comment]
It was decided to not include this without the (device) dark mode support.

**Comment by carolinan** [comment]
Changing the input fields background color would also mean that we had to adjust the text, and it would be confusing to have different colors here depending on if the field is empty, has content, or is being edited.

The current color for inputs when the dark backgrounds are used is somewhat darker than the full white, and keeps the contrast ratio with the text color.
--global--color-white-90: rgba(255, 255, 255, 0.9);
