### ISSUE TITLE
Dark Mode: Should we turn it off in the admin?

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentytwentyone#621]
**Describe the bug**
It can be confusing for your site to appear in dark mode while you're editing it in the admin, either in the editor, or in the Customizer. This is made extra confusing, IMO, because wp-admin itself doesn't support dark mode yet. Would it be less confusing if we didn't support dark mode within the editor and Customizer?

**To Reproduce**
1. Turn on dark mode in your OS or browser.
2. Visit your site's admin.
3. Either enter the editor or the Customizer.
4. You see the dark mode version of your site.

**Expected behavior**
When I'm editing my site, I expect to see the "canonical" version of it.

**Comment by carolinan** [comment]
Even if we had user testing to learn what the majority wants, that would still be the majority.

That is why the option to turn it on and off is better.

**Comment by asathoor** [comment]
Sometimes a uger might want to use WordPress in Dark Mode and your OS in another contrasting mode. That's why I'd like to have a button somewhere where it's easy to find.

**Comment by carolinan** [comment]
If dark mode is off on the OS, a dark color option can still be chosen in the customizer.

**Comment by hedgefield** [comment]
Perfect. I made a dark mode for my site recently, and in doing so I read a lot that it's good practice to offer a way for someone to toggle it on and off regardless of system setting. Especially if you want to author the dark theme during the day or vice versa, having a manual toggle right in WP seems ideal to me.

**Comment by aristath** [comment]
During Friday's meeting it was decided to remove everything related to dark-mode and instead put that feature in a plugin as a safety precaution. dark-mode was removed in https://github.com/WordPress/twentytwentyone/pull/690 and moved in a plugin, with the hope that it can be re-integrated in the theme if we're satisfied with its implementation.
Closing this issue.
