### ISSUE TITLE
Update License URI

### ISSUE THREAD

**Issue by mukeshpanchal27** [WordPress/twentytwentyone#626]
We should add License URI in style.css and ie.css

License URI: LICENSE
Replace to
License URI: http://www.gnu.org/licenses/gpl-2.0.html

**Comment by carolinan** [comment]
(This is because default themes does not include a separate license file.)

**Comment by carolinan** [comment]
Oops, correction, since we are using sass, the correct file to make the change in is https://github.com/WordPress/twentytwentyone/blob/trunk/assets/sass/01-settings/file-header.scss

**Comment by carolinan** [comment]
Solved, closing this issue.
