### ISSUE TITLE
RC 2 priorities (December 1)

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#627]
These are our priorities until first of  December 2020.

2. Open issues that are [labeled high priority](https://github.com/WordPress/twentytwentyone/issues?q=is%3Aissue+is%3Aopen+label%3A%22High+priority%22)
3. [Accessibility issues](https://github.com/WordPress/twentytwentyone/labels/Accessibility%20%28a11y%29)
4. Testing 5.6 beta for theme related bugs
5. Open issues labeled bug but not labeled as a "low priority"

Please note that we are in string freeze and text changes must be avoided.

**Comment by sarahricker** [comment]
Noting that Beta 4 was moved to Nov 12 2020, so we have a few more days! 🙏
