### ISSUE TITLE
Task: The WordPress.org theme support page.

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#631]
Copied from the initial document where the responsibilities for our "theme squad" is listed:
_Document the theme features and behavior, for the support page on WordPress.org._

The deadline for this is RC1.

Example page:
https://wordpress.org/support/article/twenty-twenty/

**Comment by melchoyce** [comment]
What was the process of writing this like for Twenty Twenty? Should I start in a Google doc and then ping the Docs team?

**Comment by carolinan** [comment]
I did not participate in writing the page then.

Do you and @luminuu  have access to /support/ ?
Because it would be easier to create but not publish a page there. 

If it was written in google docs then it would need to be convert to blocks.

**Comment by pattonwebz** [comment]
I have access there to edit/create pages but ideally it would be created in blocks from the start since this helphub site uses the block editor

**Comment by pattonwebz** [comment]
Seems like the content for the twenty twenty page is just `h2` healdines and paragraph, image and list blocks - the navigation the the left is hardcoded to the template and the navigation to the right is generated from the page headers. 

It could be converted from a google doc easily. I created a draft `article` (which is the name of the post type used for these pages) that can be edited whenever the content is ready.

Let me know if you need someone to input the content and send around a preview link for it once it's ready.

**Comment by melchoyce** [comment]
Thanks @pattonwebz! I'll see if I can get @luminuu and I edit access, and if not, I'll get you a doc to convert.

**Comment by melchoyce** [comment]
Started outlining the doc: https://wordpress.org/support/?p=13563362&post_type=helphub_article&preview=1&_ppp=2cf59eb54c
