### ISSUE TITLE
Internet Explorer 11: navigation sub-menus not visible

### ISSUE THREAD

**Issue by afercia** [WordPress/twentytwentyone#636]
**Describe the bug**
With Internet Explorer 11, the navigation menu sub-menus aren't visible.  

**To Reproduce**
- set as primary menu a menu that does have sub-menus
- use Internet Explorer 11
- on the front end, either hover a top level menu item with sub-menus or click on it
- the sub-menu doesn't get visible
- in some cases, the following top-level items disappear (layout issue)

Animated GIF to better illustrate:

![ie menu](https://user-images.githubusercontent.com/1682452/96729692-b749af80-13b5-11eb-8462-cd95fe9cb3da.gif)

While layout quirks are allowed to happen in IE, I guess the theme should ensure the navigation menu is still usable.

Not sure if there are specific reasons for the following `overflow` CSS properties, but seems they're the culprit and maybe they should be removed:

https://github.com/WordPress/twentytwentyone/blob/4337f375aaf679ac4471cb01a236eb08eff6d92e/assets/css/ie.css#L5703-L5704

**Comment by ryelle** [comment]
Those overflow styles are used for the menu on smaller screens (mobile), so they can _probably_ be moved to behind a media query.
