### ISSUE TITLE
Revise add_theme_support

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#639]
Remove the `add_theme_support( 'custom-units' ); ` since this is no longer needed, it is enabled by default.

Gutenberg only theme support:
It would be great if someone can do a sanity check to confirm this:

`add_theme_support( 'experimental-custom-spacing' );` is used in the theme, but 
`add_theme_support('custom-spacing');` is the name in the documentation: 
https://developer.wordpress.org/block-editor/developers/themes/theme-support/#cover-block-padding 
And, with or without Gutenberg installed, neither of them adds padding settings to the cover block. 

This is the announcement, but it is not what I am seeing in the editor:
https://make.wordpress.org/core/2020/06/11/whats-new-in-gutenberg-11-june/

**Comment by aristath** [comment]
Is it not needed for previous versions of WP?

**Comment by carolinan** [comment]
It was added in 5.5, so if we want to support one release, then yes it is needed.

I don't feel strongly either way, it is generally an exception for theme supports to change this way.

**Comment by kjellr** [comment]
Hmm. Yeah, I guess we might as well leave it in if it'll keep support in 5.5 then. Might make sense to add a code comment to explain that.

**Comment by carolinan** [comment]
Related:
https://github.com/WordPress/gutenberg/issues/26662

**Comment by carolinan** [comment]
Reopened this because we need to rename the theme support for the custom spacing.

**Comment by carolinan** [comment]
With https://github.com/WordPress/gutenberg/pull/27045 merged and the theme support renamed to 	`add_theme_support( 'custom-spacing' )`;, I have tested the custom spacing for the cover block without issues.
