### ISSUE TITLE
Search block alignment is not the same in the editor and front

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#641]
**Describe the bug**
The centered search block does not look the same in the editor and the front.

In the editor, the label is left aligned. On the front, the label is centered.
There is no difference between the default block, and the centered block, except for the label.
When the label is turned off, there is no visible difference between the two.

**To Reproduce**
1. Add a search block.
2. Duplicate the block and change the alignment to center.
3. View the editor and front to see the difference.

**Expected behavior**
The editor and front should match.

**Screenshots**
Left: Editor. Right: Front.

![searchblock-alignments](https://user-images.githubusercontent.com/7422055/96826086-f407bc00-1432-11eb-8779-de2152c69967.png)

And with the "button only" setting enabled:
Left: Editor. Right: Front.
![searchblock-buttononly](https://user-images.githubusercontent.com/7422055/96826960-d2a7cf80-1434-11eb-9c98-1263d0320cf6.png)

**Editor version (please complete the following information):**
- WordPress version: 5.6-beta1-49267

**Comment by JustinyAhin** [comment]
@carolinan I think some of the issues here have been solved in #645 

Like the centered issue

Editor
![Screenshot_2020-10-23 Add New Post ‹ two wordpress test — WordPress](https://user-images.githubusercontent.com/33403964/97014366-20f6c480-1542-11eb-8b64-81b877e9853d.png)

Frontend
![Screenshot_2020-10-23 #641 – two wordpress test](https://user-images.githubusercontent.com/33403964/97014379-25bb7880-1542-11eb-8372-914fd5662cab.png)
