### ISSUE TITLE
Search block with button icon does not look the same in the editor and front

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#643]
**Describe the bug**
When a search block has the option "use button with icon" enabled, the editor and front does not match.

The colors when the button is hovered are also different.

**To Reproduce**
1. Add a search block.
2. Enabled the option to display the button icon
3. Compare the editor and front

Next, repeat this in combination with the other settings: Button inside, button only.

**Expected behavior**
The editor and front should match.

**Screenshots**
Left: Editor. Right: Front.

Button only:
![searchblock-buttononly-icon](https://user-images.githubusercontent.com/7422055/96827512-0a634700-1436-11eb-8e7a-09dbc4db3824.png)

Button inside:
![searchblock-buttoninside-icon](https://user-images.githubusercontent.com/7422055/96827663-5910e100-1436-11eb-9360-72639c3bfae2.png)

Button outside:
![searchblock-buttonoutside-icon](https://user-images.githubusercontent.com/7422055/96827845-befd6880-1436-11eb-8d17-25e4c5d06867.png)

**Editor version (please complete the following information):**
5.6-beta1-49267

**Comment by aristath** [comment]
Moved to the RC1 milestone
