### ISSUE TITLE
Build tools in the WordPress world

### ISSUE THREAD

**Issue by kimmenbert** [WordPress/twentytwentyone#654]
Hey. I’m curious as to why @wordpress/scripts has not been chosen as a build tool for twentytwentyone?

I think it would be a good thing to use internally in “all things” WordPress. As it would provide a good possibility to keep developing the tool and make it into a build tool that can be used by everyone. In plugins, building gutenberg blocks and in themes.

Currently it is a bit weird about css/scss in that it also creates .js files etc. when compiling css, and that is some of the things I don’t think will be handled properly without wider usage of the tool.

Gutenberg is a big part of WordPress now, and I think modifying Gutenberg trough block filters using es6 will be a regular thing people do.

Helping developers around the world by providing a proper do-it-all tool could be a nice thing to do. And a good start to that would be to start using it more within WordPress teams :)

**Comment by carolinan** [comment]
Because originally it was not needed.  The theme only had a very small amount of JavaScript.

wpscript and wpenv are very large and they can actually make development slower. The time it takes to run npm install is not isignificant.

**Comment by ryelle** [comment]
wordpress/scripts (the build & start scripts specifically) is a [webpack](https://webpack.js.org/) tool, so it's designed for javascript code. The CSS part only works for CSS called from a source javascript file (as you've noticed, you get an extra JS file if you try to use it on just CSS).

The other scripts _could_ be useful, especially as more JS has been added to the theme, but as @carolinan mentioned, it's a trade-off for the best tool for the job. We can stick with using `node-sass` directly and avoid any extra webpack configuration.

> Gutenberg is a big part of WordPress now, and I think modifying Gutenberg trough block filters using es6 will be a regular thing people do.

Very true, but a theme shouldn't really be modifying much of Gutenberg. If you're looking for the best way to work with Gutenberg as a plugin, I'd recommend [checking out `@wordpress/create-block`.](https://developer.wordpress.org/block-editor/packages/packages-create-block/) It can create a plugin with all the build tools set up and ready to go.

**Comment by kimmenbert** [comment]
> Very true, but a theme shouldn't really be modifying much of Gutenberg.

Yes, I agree. Although TwentyTwentyone theme modifies gutenberg already. (Removing block styles etc)

We should not facilitate for developers doing even more in the themes instead of in a plugin though.

Just to note, I was thinking of things like this:
https://developer.wordpress.org/block-editor/developers/filters/block-filters/#editor-blockedit

What I’m advocating for is basically: use @wordpress/scripts in TwentyTwentyone to reveal what it lacks to be a full-blown tool like Laravel-mix etc.

**Comment by carolinan** [comment]
It has been discussed earlier, and was decided against at that point as well.

There is no benefit of making this change especially not at this stage when we are focusing on finding and resolving bugs.
