### ISSUE TITLE
Where is the search box?

### ISSUE THREAD

**Issue by t-pabla** [WordPress/twentytwentyone#655]
This may not be a bug.

For testing purposes I installed twenty twenty-one them and I don't see search box anywhere. What's the trick to make it appear?

**Comment by carolinan** [comment]
You can add a search with a widget or a search block.

**Comment by t-pabla** [comment]
Thanks for the quick reply,  Carolinan !

Why make it so difficult?

It should appear by default, generally in the header. Not everybody using WP is a programmer, designer, or a software engineer!

`add a search with a widget or a search block`

How would you display it on the right side of the header?

P.S: I find this theme load faster than twentytwenty!

**Comment by carolinan** [comment]
You would not be able to place it in the right side of the header without a plugin, it is not a feature that is offered with this theme.

**Comment by t-pabla** [comment]
Thanks Carolinan for your time and help.

**Comment by melchoyce** [comment]
Thanks @t-pabla! Going to close this issue. Please let us know if you have any other questions.
