### ISSUE TITLE
posts pagination links on various screen widths

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwentyone#659]
On an archive with multiple pages, the links at the bottom can be difficult to discern, depending on the screen width, because they are much longer now that each has "Page" in front of the number.  And at every width, there is a large white space below the links, which could be used.
(And I wonder if it's a worse problem in a language that has a longer word for "Page".)

On the narrowest width, (this one is 562px), the Page links are not visible at all, so the user has fewer navigation options.
![Post Formats – Page 2 – Local Current WP-45](https://user-images.githubusercontent.com/7957680/96949193-ef7fe980-14ac-11eb-8aed-a918f57118cc.jpg)

When the screen is wide enough for the links to appear, they are sort of jumbled together with the other links. (this one is 598px)
![Post Formats – Page 2 – Local Current WP-04](https://user-images.githubusercontent.com/7957680/96949272-248c3c00-14ad-11eb-94e2-26b3e7a2df29.jpg)

As the screen gets wider, the links look more like a sentence, which is quite confusing. (this one is 735px)
![Post Formats – Page 2 – Local Current WP-18](https://user-images.githubusercontent.com/7957680/96949350-500f2680-14ad-11eb-9cbb-94b04e7f020b.jpg)

It is similar at 834px.
![Post Formats – Page 2 – Local Current WP-33](https://user-images.githubusercontent.com/7957680/96949409-6cab5e80-14ad-11eb-9d7c-cb2a754b8c24.jpg)

This one is 1008px, where it is finally wide enough to have the Page links separate from the other links.
![Post Formats – Page 2 – Local Current WP-48](https://user-images.githubusercontent.com/7957680/96949473-92386800-14ad-11eb-94c1-693e841a01be.jpg)

**Comment by melchoyce** [comment]
What's the feasibility of moving the pagination and the newer/older post links into two separate containers, so we can do something more like this?

![image](https://user-images.githubusercontent.com/2846578/97326137-11c98c80-184a-11eb-9876-9d2b88577730.png)

Would this even make sense?

**Comment by pattonwebz** [comment]
2 containers would probably mean positioning would be eaiser to handle and less likely to result in unusual wrapping at certain screen sizes :smile:

**Comment by pattonwebz** [comment]
Sorry, hit the wrong button and closed by mistake.

**Comment by joyously** [comment]
Can you show what it would look like on a narrow screen?

**Comment by aristath** [comment]
I don't consider this an issue... Users can navigate pages no matter what device they are on. If they are on a larger screen they have more options but that's natural and a progressive enhancement depending on the viewport.

> What's the feasibility of moving the pagination and the newer/older post links into two separate containers

Everything is possible... it wouldn't be as simple as changing a single line, we'd probably need to rewrite the `navigation_markup_template` via a filter and it would probably lead to a11y issues since we'd need to split the `<nav>` element. If you strongly feel that this is an essential improvement it can be done, but (personal opinion) I'd rather we don't do it... It's a lot more visually balanced the way it is now.

**Comment by pattonwebz** [comment]
@aristath are you saying that the numbered pages and the previous/next links are all handed via the same function call?

**Comment by melchoyce** [comment]
> Everything is possible... it wouldn't be as simple as changing a single line, we'd probably need to rewrite the `navigation_markup_template` via a filter and it would probably lead to a11y issues since we'd need to split the `<nav>` element.

IMO that level of effort doesn't sound worth it at this point in the release.

**Comment by aristath** [comment]
> @aristath are you saying that the numbered pages and the previous/next links are all handed via the same function call?

Unless I'm mistaken yes, isn't it all in the `the_posts_pagination` function?
https://github.com/WordPress/twentytwentyone/blob/5759e9692dd57f93e98ec5de299b70891c777771/inc/template-tags.php#L220-L236
From what I can see, it's all in there.
The [`the_posts_pagination`](https://developer.wordpress.org/reference/functions/the_posts_pagination/) function then echoes [`get_the_posts_pagination`](https://developer.wordpress.org/reference/functions/get_the_posts_pagination/) which calls [`_navigation_markup`](https://developer.wordpress.org/reference/functions/_navigation_markup/) and that in turn adds the [`navigation_markup_template`](https://developer.wordpress.org/reference/hooks/navigation_markup_template/) filter that we can potentially use to change the markup.

**Comment by pattonwebz** [comment]
> Unless I'm mistaken yes, isn't it all in the `the_posts_pagination` function?

Yup, you're right. I didn't look before commenting. I just assumed it was 2 functions because the consideration to split it between containers was mentioned (should have checked :) )

**Comment by joyously** [comment]
You _could_ hide the Newer and Older on middle width screens, or on all widths.
It doesn't have to have both. 
I was trying it out on an archive with a lot of pages and it still only shows 3 Page links, but it occurred to me that changing the default text from Previous and Next to Newer and Older would be a problem for those that use a plugin to sort by title or some other thing. And calling them posts when it might be a custom post type is not really that great either. (I did a client site where posts were Movie Reviews sorted by movie title, and this would have been an issue to fix there.)

**Comment by carolinan** [comment]
I propose that we add some vertical spacing for when the navigation wraps:

![96949272-248c3c00-14ad-11eb-94e2-26b3e7a2df29](https://user-images.githubusercontent.com/7422055/97425336-486ada00-1912-11eb-8841-f722540b6c61.jpg)

**Comment by joyously** [comment]
@carolinan I think that would actually implement Mel's mockup. Give the Newer and Older some top margin, which could be smaller on the smallest window where the middle part is hidden.
