### ISSUE TITLE
Improve menu visibility

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwentyone#660]
The menu can be difficult to use since there is little indication of change on hover and the text looks the same as the rest of the page. I get lost.
Can you tell there is a menu open here?
![menu](https://user-images.githubusercontent.com/7957680/96950580-3c18f400-14b0-11eb-9b5e-0d9a25d3bd10.jpg)

What if there were some box-shadow or something to distinguish the menu from the other parts of the page? Or it could be the border that is used for keyboard navigation.
![menu-with-shadow](https://user-images.githubusercontent.com/7957680/96950751-a336a880-14b0-11eb-944d-68c07b326638.jpg)

**Comment by afercia** [comment]
While the contrast ratio is okay, this behavior may trigger readability problems especially when a long menu is displayed over other text. See screenshot below:

![menu over content](https://user-images.githubusercontent.com/1682452/96990847-ef70ff80-1527-11eb-9226-722007292dc5.png)

**Comment by melchoyce** [comment]
Would a 1px solid border help?

![image](https://user-images.githubusercontent.com/2846578/97030176-7031fa80-152c-11eb-8307-a85072601dc0.png)
![image](https://user-images.githubusercontent.com/2846578/97030428-c1da8500-152c-11eb-8001-6353ec9943d7.png)
