### ISSUE TITLE
Change comment area heading text from "Reply" to "Comment"

### ISSUE THREAD

**Issue by aristath** [WordPress/twentytwentyone#672]
Came up on Slack: https://wordpress.slack.com/archives/C02RP4Y3K/p1603455047138300

> Just want to check something. I'm busy translating Twenty Twenty-One. I see the context for `%s Reply` is "comments title". Should the string not say `% Comment`? "Reply" is generally used for replies on forums. So, it can get really confusing really quickly.

For reference, this is the line with that string: https://github.com/WordPress/twentytwentyone/blob/a58f3e5b785be4c1ed97e06cf07094dd3a10caad/comments.php#L40

**Comment by jdevalk** [comment]
Yeah it bothered me too that it says “Leave a reply”, when that’s not what you’re doing, you’re leaving a comment. Reply only makes sense in the context of replying to someone else’s comment.

**Comment by melchoyce** [comment]
I see it as replying to the post with a comment, but I also don't feel strongly either way. I'm fine with changing it.
