### ISSUE TITLE
Position of the HTML block content

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#674]
**Question**

The HTML block in the editor is in the middle, below the title.
On the front, the block content is all the way to the left.

Should this content be in the middle also on the front?
Or should the author position their HTML with, well, HTML?

**Comment by melchoyce** [comment]
Here's what I'm seeing on WordPress 5.5.1 and Gutenberg 9.2.1:

**Editor:**

![image](https://user-images.githubusercontent.com/2846578/97049880-67e8b800-154a-11eb-94d8-103cd72da188.png)

**Front-end:**

![image](https://user-images.githubusercontent.com/2846578/97050009-9d8da100-154a-11eb-9079-47025da7683d.png)

This might only be an issue on WordPress trunk (5.6 Beta 1).

Either way, I expect the HTML block to be contained within the content width on both the front-end and in the editor (so, how it looks in my screenshots).

**Comment by carolinan** [comment]
It is in the middle again, tested with 5.6-beta1-49308

**Comment by carolinan** [comment]
Actually it's not fixed. It only looked like it was fixed because I was using a paragraph tag -
HTML tags are included in the content styles, so if tags are used, the content is positioned correctly.
If someone just enters plain text, the text will be on the left.
This can not be solved without a wrapper around the "block", so I will keep this closed.
