### ISSUE TITLE
Navigation Block: Style submenus

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentytwentyone#680]
**Describe the bug**
The submenu styling for the Navigation Block inherits core Gutenberg styles, which don't match the aesthetics of the theme.

**To Reproduce**
1. Create a new page or post.
2. Add a navigation block and select a menu that contains a submenu.
3. Hover over the submenu.
4. See the drop-shadow on the submenu.

**Expected behavior**
The submenu styling should match the design of the header navigation.

**Screenshots**
![image](https://user-images.githubusercontent.com/2846578/97048339-42f34580-1548-11eb-8098-c96be17ed4cc.png)
![image](https://user-images.githubusercontent.com/2846578/97048369-4d154400-1548-11eb-96d8-c961fbcfb2af.png)

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Gutenberg version: 9.2.1

**Desktop (please complete the following information):**
 - OS: macOS 10.15.6
- Browser: Chrome 86.0.4240.80 (Official Build) (x86_64)

**Additional context**
See also #660 for a discussion on submenu styling.

**Comment by carolinan** [comment]
Do we also want to change the styling in the editor or will this affect the editing experience / usability when setting up the menu?

**Comment by JustinyAhin** [comment]
> Do we also want to change the styling in the editor or will this affect the editing experience / usability when setting up the menu?

I don't believe we should do that. For the navigation block, the way it works in the editor is slightly different. For instance for with menu item that has a submenu, you need to click on the submenu `<ul>` item to add other sub submenus.

**Comment by JustinyAhin** [comment]
Closing this as it was fixed in #695
