### ISSUE TITLE
Vertical navigation blocks should expand submenus instead of using dropdowns

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentytwentyone#681]
Vertical Navigation Blocks that contain submenus look like this:

![image](https://user-images.githubusercontent.com/2846578/97048502-80f06980-1548-11eb-8e19-02fcd879cc89.png)

Should they look like this instead?

![image](https://user-images.githubusercontent.com/2846578/97048982-eba1a500-1548-11eb-81ed-19e9b6b9020e.png)

**Comment by carolinan** [comment]
I think the current menu works, the menus are similar and the design is recognizable.  It is up to you how badly you want it :)

**Comment by melchoyce** [comment]
Making it low priority. If someone gets to it, they get to it, if they don't, they don't.
