### ISSUE TITLE
Overlapping Columns: Paragraphs should inherit container background

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentytwentyone#682]
**Describe the bug**
When you create an overlapping columns block, and add a paragraph to the column that is overlapping, it includes a background color so the text can always be read:

![image](https://user-images.githubusercontent.com/2846578/97049215-505cff80-1549-11eb-8b16-341c53560afc.png)

**To Reproduce**
1. Create a new post or page.
2. Add a cover block, and select a background color that isn't green.
2. Add a columns block inside of the cover block, and select the "overlapping" block style.
3. Add something like an image to the left column, and a paragraph to the right column.
4. See that the paragraph's background color is green, not the color you chose for your cover block.

**Expected behavior**
I think we should inherit that color from the container's background, instead of always using green.

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Gutenberg version: 9.2.1

**Desktop (please complete the following information):**
- OS: macOS 10.15.6
- Browser: Chrome 86.0.4240.80 (Official Build) (x86_64)

**Comment by carolinan** [comment]
The cover block and group block does not have the same CSS classes to identify the background color, so this needs careful testing.
https://github.com/WordPress/gutenberg/issues/21439

**Comment by carolinan** [comment]
Because the blocks are nested in several levels, this is only possible if the outer block has a palette color, not a custom color.
I'm not sure it is worth the extra CSS, but will do a PR.

**Comment by melchoyce** [comment]
Since this seems to be more of a hassle than it's worth, and folks can change the background color manually, I'm going to close this issue.
