### ISSUE TITLE
Custom HTML Block (Using Instagram's embed code)

### ISSUE THREAD

**Issue by bph** [WordPress/twentytwentyone#683]
- When using the Custom HTML Block on a dark background, the block HTML is white with white text. 
- It also is huge text so the box expands over the full screen and longer. 
- In Preview mode of the Custom HTML is shows on the right a small stripe of original teal color 
- On frontend the block is all the way to the left of the screen.
- On frontend the size of the Instagram embed is considerably smaller than displayed in the editor screen. 
 
### Expected behaviour

Does the editor and front match?  No 

Is there text that wraps or cuts off unexpectedly? No 

Does the block look as expected on different screen sizes? Only tested on desktop, sorry. 

### Color options

The site uses #303030 as background color. 

###

Doesn't offer transform to group block. 

### Screenshots
Here is a video: https://recordit.co/YQBur2cZp8
Editor version (please complete the following information):
WordPress version: WordPress 5.6-beta1-49262 
Gutenberg version: build from master 2020-10-23

What was used to test:
OS: OSX 10.15.7
Browser: Google Chrome 86.0.4240.80

**Comment by carolinan** [comment]
Another weird thing is that if one just types in random HTML, it works well. Seems related to copy pasting.
For example, I copy pasted [a gist that I use to test HTML form elements](https://gist.github.com/carolinan/53cf8c92b77c8ad6babd3b38d0a07530), and that text was also white on white.

The preview does show the original mint background color for me even though the body background setting is actually black. But the content in the preview is correct, it is not narrow or on the right.

Will test with some different themes.
