### ISSUE TITLE
Continue reading Link needs dotted line, too

### ISSUE THREAD

**Issue by bph** [WordPress/twentytwentyone#686]
**Describe the bug**
Tested link outline on blog page with menu/child menu items, blog post title and "Continue Reading" 

**To Reproduce**
1. Create at least one blog post
2. Got to category or blog page
3. Hover over Continue Reading 

**Expected behavior**
Expected the link on Continue Reading follow the overall site's styling for links. 

**Screenshots**
short screencast: https://recordit.co/hv0s21DrAX

**Editor version **
- WordPress version: trunk
- Gutenberg zip from Master (10/23/2020 after 9.2.1)

**Laptop:**
 - OS: OSX 10.14.6
 - Browser: Google Chrome
 - Version 86.0.4240.80

**Comment by carolinan** [comment]
Hi,
This was supposedly fixed yesterday, but it is in the GitHub version of the theme, not in WordPress 5.6 beta yet.

**Comment by bph** [comment]
Yep, that is fixed in trunk of this morning.
