### ISSUE TITLE
Change archive titles

### ISSUE THREAD

**Issue by aristath** [WordPress/twentytwentyone#705]
Came up in https://github.com/WordPress/twentytwentyone/pull/697#issuecomment-716856341 and #688 

@melchoyce 
> Aside, any way to drop the "Category Archives:" part of the heading? It always feels so unnecessarily meta to me.

@bph 

> One of the first things, we do with every theme is to remove the words "Categories" or "Archive" from the category or tag pages, and add the display of the descriptions field.
> 
> For SEO purposes there is no value to have those words on the page (it might hurt the page rankings) but it definitely would help if there is a way to add additional text to the category pages in the description field.

Suggestions:

| Context | Current | Suggestion |
| ----- | ----- | ----- |
| Category | `Category Archives: %s` | `Category: %s` |
| Tag | `Tag Archives: %s` | `Tag: %s` |
| Author | `Author Archives: %s` | `Author: %s` |
| Year | `Yearly Archives: %s` | `Year: %s` |
| Month | `Monthly Archives: %s` | `Month: %s` |
| Day | `Daily Archives: %s` | `Day: %s` |
| Post Archive | `%s Archives` (post-type, singular_name) | `%s` (post-type, plural name) |
| Taxonomy | `%s Archives` (singular name) | `%s` (plural name) |

**Comment by carolinan** [comment]
Should the author archive include the author biography + avatar in place of the description?

**Comment by aristath** [comment]
> Should the author archive include the author biography + avatar in place of the description?

We can definitely do that... 
```php
add_filter( 'get_the_archive_description', function( $description ) {
	if ( is_author() ) {
		// Do stuff.
	}
	return $description;
} );
```

But I think it would be best to have a separate ticket for the author description so we can make a decision about the titles in this issue faster 😉

**Comment by melchoyce** [comment]
Do we need a prefix? Does it matter what kind of taxonomy something is?

**Comment by bph** [comment]
Thank you, @aristath for picking up this discussion. 

@melchoyce 
>Do we need a prefix? Does it matter what kind of taxonomy something is? 

Such a great question. We don't need it. _(strong opinion, loosely held)_

**Comment by aristath** [comment]
Actually I think it would be best to just remove the theme's customizations here...
WP Core already does out of the box most of the things suggested here. 
If there's something that needs fixed, it should be fixed in core instead of patched in a plugin via filters. Core already does a pretty good job with these titles, and the existing filters allow plugin authors to further customize titles for their own post-types and taxonomies.

In the past we've used the filter to change the archive titles and customize them in default themes, but I see no good reason why this should be the case here.

**Comment by carolinan** [comment]
As in removing this code: https://github.com/WordPress/twentytwentyone/blob/trunk/inc/template-functions.php#L103

**Comment by aristath** [comment]
Yep, we can remove this part https://github.com/WordPress/twentytwentyone/blob/bb30a036598c259766e1cbf734f021179d6ee12f/inc/template-functions.php#L96-L170
