### ISSUE TITLE
Add author biography + avatar to author archives

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#712]
**Describe the bug**
As we are rewording the archive titles and adding the archive description, 
should we also add the author biography  (if there is one) to the author archives?

**Comment by Abdujabbar** [comment]
I think yes if exists biography of author it will be good to see on information about author on archive page for example on sidebar. it's just my opinion

**Comment by melchoyce** [comment]
Yeah, IMO this would be a great enhancement.

**Comment by melchoyce** [comment]
Quick in-browser mockup:
![image](https://user-images.githubusercontent.com/2846578/97325284-2e18f980-1849-11eb-8998-d799a4b9177e.png)

**Comment by Abdujabbar** [comment]
@carolinan  can I take this task for development?

**Comment by carolinan** [comment]
@Abdujabbar Yes :)

**Comment by carolinan** [comment]
@Abdujabbar Hi, are you still working on this issue?

**Comment by JustinyAhin** [comment]
Was there already a PR @carolinan? I can pick up if not.

**Comment by JustinyAhin** [comment]
Looking now, the biography is already added when it exists (https://github.com/WordPress/twentytwentyone/blob/trunk/archive.php#L22). Excepts that it's very big. I think it'll make more sense to reduce it a lil bit.

![Screenshot_2020-10-30 segbedji – two wordpress test](https://user-images.githubusercontent.com/33403964/97696424-dd520c80-1aa5-11eb-9c6c-26c9e09ef2c0.png)

**Comment by Abdujabbar** [comment]
> @Abdujabbar Hi, are you still working on this issue?

@carolinan No I haven't started yet

**Comment by Abdujabbar** [comment]
Do we need **Author**  word in template @carolinan ?

**Comment by Abdujabbar** [comment]
@JustinyAhin it's not exists PR for now if you want you can get it, because I am not good at CSS, and PHP side is already exists :)

**Comment by melchoyce** [comment]
Per https://github.com/WordPress/twentytwentyone/pull/697, the author bio should be using the XL text size.

**Comment by carolinan** [comment]
Huh, I did not know that the author bio was included in  `get_the_archive_description`

**Comment by JustinyAhin** [comment]
> Per #697, the author bio should be using the XL text size.

Then it's correct. It is using the right font size. I was confused when I saw your browser mockup.

Closing the issue then.
