### ISSUE TITLE
Block editor: Separator is full width inside the editor while it’s centered on the front

### ISSUE THREAD

**Issue by briceduclos** [WordPress/twentytwentyone#714]
**Describe the bug**
When you insert a separator block inside the editor, it appears full width. On the front, it appears centered.

**To Reproduce**
Inside the code editor, insert a separator block or paste the following code:

```
<!-- wp:separator -->
<hr class="wp-block-separator"/>
<!-- /wp:separator -->
```

**Screenshots**

| Editor  | Front |
| ------------- | ------------- |
| ![separator-editor](https://user-images.githubusercontent.com/56188815/97373212-baf99c80-18b5-11eb-842c-6608b54b4210.PNG) | ![separator-front](https://user-images.githubusercontent.com/56188815/97373211-ba610600-18b5-11eb-9fbd-a2e32ec138d5.PNG) |

**Comment by carolinan** [comment]
Just a note that when solving this, we also need to add the full width alignment to the separators in the portfolio list block pattern.

**Comment by JustinyAhin** [comment]
> Just a note that when solving this, we also need to add the full width alignment to the separators in the portfolio list block pattern.

Looking at the block pattern, there's a full width setting in the editor. Or I'm not correctly understanding what you mean @carolinan?

**Comment by carolinan** [comment]
The separator in this block pattern are using the default width for the separators. I thought they were meant to use the full width
https://github.com/WordPress/twentytwentyone/blob/trunk/inc/block-patterns.php#L107

But looking at the https://github.com/WordPress/twentytwentyone/pull/299 they are not full width.

**Comment by kjellr** [comment]
> The separator in this block pattern are using the default width for the separators. I thought they were meant to use the full width

The original mockup had the whole thing designed to be wide width. Since wide-width separators weren't possible at the time we built #299, we settled for default width. I'll open a PR to change to wide with now that wide-width separators are possible.
