### ISSUE TITLE
Block editor: Last image of a gallery inside a group isn’t correctly aligned

### ISSUE THREAD

**Issue by briceduclos** [WordPress/twentytwentyone#715]
**Describe the bug**
When a gallery is placed inside a group, the gallery's last image isn't aligned with the others. This is due to the following CSS that removes the last image's margin.
https://github.com/WordPress/twentytwentyone/blob/trunk/assets/css/style-editor.css#L742-L744

**To Reproduce**

Inside the code editor, paste the following code:

```
<!-- wp:group {"align":"full"} -->
<div class="wp-block-group alignfull"><div class="wp-block-group__inner-container"><!-- wp:gallery {"ids":[null,null,null,null],"columns":2,"imageCrop":false,"linkTo":"none"} -->
<figure class="wp-block-gallery columns-2"><ul class="blocks-gallery-grid"><li class="blocks-gallery-item"><figure><img src="https://raw.githubusercontent.com/WordPress/twentytwentyone/trunk/assets/images/Reading.jpg" alt="" data-id=""/></figure></li><li class="blocks-gallery-item"><figure><img src="https://raw.githubusercontent.com/WordPress/twentytwentyone/trunk/assets/images/Reading.jpg" alt="" data-id=""/></figure></li><li class="blocks-gallery-item"><figure><img src="https://raw.githubusercontent.com/WordPress/twentytwentyone/trunk/assets/images/Reading.jpg" alt="" data-id=""/></figure></li><li class="blocks-gallery-item"><figure><img src="https://raw.githubusercontent.com/WordPress/twentytwentyone/trunk/assets/images/Reading.jpg" alt="" data-id=""/></figure></li></ul></figure>
<!-- /wp:gallery --></div></div>
<!-- /wp:group -->
```
**Screenshots**
![gallery-inside-block](https://user-images.githubusercontent.com/56188815/97373642-b5e91d00-18b6-11eb-890f-f0916f8dcbc4.PNG)

**Comment by melchoyce** [comment]
Thanks for reporting @briceduclos, I really appreciate all your testing 🙏

**Comment by carolinan** [comment]
We do need some clearing for the last item otherwise the floated blocks floats outside the group.
But in this case, the entire gallery block should be the last item, not the last image inside the block.
