### ISSUE TITLE
Linked images in the media and text block has no visible focus style

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#728]
**Describe the bug**
When an image is added to the Media part of the media and text block, and a link is added,
the linked image has no visible indicator that shows when the link is in focus.

**To Reproduce**
1. Add a media & text block with an image.
2. Add a link to the image, using the toolbar option.
3. Save and view the front
4. Move focus to the link, for example using tab.
5. See that the image has no visible focus indicator.

**Expected behavior**
There needs to be a visible focus indicator.

WordPress version: 5.6-beta2-49352
Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? "default"

**Comment by melchoyce** [comment]
Can we use the same dotted outline we're using for form elements?

**Comment by carolinan** [comment]
Tested the gallery, same result, there is no visible focus indicator for linked images.

-When the caption is linked, the default focus style for links is used, and with the background color, this is more visible than before :)
