### ISSUE TITLE
Placing a cover or columns block after an aligned block misplaces the second block

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#735]
**Describe the bug**
When placing a default cover block or a columns after a block that is aligned left or right,
the second block is misplaced, both in the editor on front.

In comparison, the default group block is positioned below the aligned block.

**To Reproduce**
1. Add a block with an alignment setting for example a cover block or image.
2. Align this block to the left
3. Add a default width cover block after the first block
3. Add a default width columns block after the first block

**Expected behavior**
The blocks should below the aligned block, in order to fit inside the editor 
and within the chosen width of the content on the front.

**Screenshots**

![coverblock-left-combo](https://user-images.githubusercontent.com/7422055/97552827-05be0600-19d5-11eb-870c-117970608d17.png)

**Editor version (please complete the following information):**
- WordPress version: 5.6-beta2-49360
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? 
"default"

**Comment by JustinyAhin** [comment]
I think this is more a Gutenberg issue than a theme one.
I noticed the same behavior in all the default themes from 2010 to 2019.
