### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#741]
The goal is to test, [continue the discussion](https://make.wordpress.org/core/2020/10/22/twenty-twenty-one-dark-mode-discussion/), and once feedback has been received, make a final decision whether to keep the dark mode functionality in the theme.

**Please open a new issue in this repository if you find problems with the dark mode functionality.**

[Issues with the dark mode label ](https://github.com/WordPress/twentytwentyone/labels/%5BComponent%5D%20Dark%20Mode)

**Comment by adamsilverstein** [comment]
I created this [issue](https://github.com/WordPress/twentytwentyone/issues/833) but don't have capability to add the dark mode tag.
