### ISSUE TITLE
Filters to remove 

### ISSUE THREAD

**Issue by t-pabla** [WordPress/twentytwentyone#744]
I have created a Child Theme to play with this new twentytwentyone them. I find it faster than 2020 theme.

What code should I use in functions.php of my Child Theme to filter (i.e., Remove) the followings so that I don't have to mess with the files in the Parent Theme:
(1) Posted on date from posts everywhere.
(2) Author title and Bio
(3) Date and time from all comments.

Thanks.

**Comment by carolinan** [comment]
Hi!

For 1), post date, you would override the function `twenty_twenty_one_posted_on` in your child theme.
2),  you would override the function `twenty_twenty_one_posted_by`
The bio is only visible when one has been entered in the user admin area. To remove it you would need to override the template.
`twentytwentyone\template-parts\post\author-bio.php`

3) You would probably find it easiest to hide it with CSS. Otherwise you would need a custom menu walker in your child theme.

**Comment by t-pabla** [comment]
Thank you  carolinan  for your reply. Appreciate it very much.

> 1), post date, you would override the function twenty_twenty_one_posted_on in your child theme.
I tried two, for example `add_filter('twenty_twenty_one_posted_on', '__return_empty_array');` AND `add_filter('twenty_twenty_one_posted_on', '__return_false');`
But did not work. Perhaps you can suggest me something that will work.

> 2), you would override the function twenty_twenty_one_posted_by
Can you please suggest me a filter? Thanks.

> The bio is only visible when one has been entered in the user admin area. To remove it you would need to override the template.
> twentytwentyone\template-parts\post\author-bio.php
> 

I (@t-p) also volunteer as MOD at WP.org support forum 
. And we always tell users not to modify the parent themes files, because these modifications get overwritten when you next update the parent theme.
So,  can you please suggest a filter? Thanks.

> 3. You would probably find it easiest to hide it with CSS. Otherwise you would need a custom menu walker in your child theme.
Off course I can use CSS to hide the date and time from the comments. 
But. I prefer using a filter instead.
So,  can you please suggest a filter? Thanks.

**Comment by carolinan** [comment]
We do not intend to add more filters.
You would not be changing the parent file, but overriding it by replacing it in the child theme.

**Comment by carolinan** [comment]
The theme uses the default function for displaying the comments.
I have not tried it and can't recommend it but you could possibly use https://developer.wordpress.org/reference/functions/get_comment_date/
