### ISSUE TITLE
Editor: Font size large, huge, giant, custom cannot properly be selected

### ISSUE THREAD

**Issue by ingereck** [WordPress/twentytwentyone#753]
**Describe the bug**
The larger font sized cannot properly be selected. They are overlapping (see screenshot).

**To Reproduce**
1. Go to a paragraph block or a text within another block where the font size is selectable and click the font size select button. 

**Expected behavior**
The different font sizes should be accessible and easy to select. 

**Screenshots**
![Screenshot 2020-10-25 at 02 37 11](https://user-images.githubusercontent.com/25270846/97112962-8a640800-16e7-11eb-9a77-366b206f9853.jpg)

**Editor version (please complete the following information):**
- WordPress version: **5.6-beta2-49392**
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? **Gutenberg Plugin**
- If the Gutenberg plugin is installed, which version is it? **9.2.2** 
- Official AMP Plugin installed - Mode: transitional Version 2.0.5

**Desktop (please complete the following information):**
 - OS: 10.15.7 
 - Browser: **Chrome**
 - Version Version: **86.0.4240.111**
 - Browser: **Firefox**
 - Version Version: **82.0 (64-bit)**
 - Browser: **Safari** 
- Version Version: 14.0

**Comment by carolinan** [comment]
Hi, this is known issue with the block editor and it is reported here:
https://github.com/WordPress/gutenberg/issues/25862

Because this has already been reported upstream, I will close this issue.
