### ISSUE TITLE
Calendar overlaps when it's in 3 columns 

### ISSUE THREAD

**Issue by TeBenachi** [WordPress/twentytwentyone#756]
**Describe the bug**
When adding the calendar block within the 3 columns, the calendar width doesn’t seem to reflect the column width. It overlaps the next column. 

**To Reproduce**
1. Add the columns block in the editor and select 3 columns
2. Add the calendar block in one of the columns

<img width="984" alt="Screen Shot 2020-10-30 at 9 25 57 AM" src="https://user-images.githubusercontent.com/30734209/97714664-cf958a80-1a97-11eb-830b-0902d38c8faf.png">

**Comment by pattonwebz** [comment]
The calender is quite pecualiar and (in my personal oppinion) a bit painful to try and restyle to make it totally responsive. I don't think we can solve this easily and I would be ok knowing this is a use case we didn't solve for.

**Comment by carolinan** [comment]
Yeah I think the best solution here is for the user to manually change the width of the column, because having the column expand to the width of the calendar may also be problematic 🤔

**Comment by carolinan** [comment]
When comparing this to the table block, the table has ` overflow-x: auto;` which gives the block a horizontal scroll in the editor, preventing the overlap.
This might make the calendar easier to work with in the editor, but it does not make it more _responsive._

Removing the min width for the table (used both by the calendar and table block) did not improve the overlap.

Comparing the calendar with the table in the editor:
![table-column](https://user-images.githubusercontent.com/7422055/97872986-3b395b00-1d17-11eb-82dc-bae676b8903c.png)

**Comment by aristath** [comment]
I think this one is safe to close.
If the site-owner adds a calendar, then they should make sure they have the room for it.
Adding a calendar to a 3-column layout and expecting it to fit in a tiny space while still being readable & usable is not a realistic expectation.

**Comment by carolinan** [comment]
I agree, I feel that I have done all the testing that I could come up with and no solution was found.
