### ISSUE TITLE
remove duplicate image

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#758]
**Describe the bug**
The assets/images/roses-tremieres-hollyhocks.jpg and assets/images/roses-tremieres-hollyhocks-1884.jpg
are duplicates, and the first one can be removed.

The image is used in the starter content, where the path to the image needs to be updated.
`/assets/images/roses-tremieres-hollyhocks.jpg` would be /assets/images/roses-tremieres-hollyhocks-1884.jpg

**Comment by pattonwebz** [comment]
I'll take care of this soon :)

**Comment by felipeelia** [comment]
@pattonwebz I'm trying to get familiarized with the theme code, so I'm trying to pick some low-hanging fruits here while I'm on it. I hope you don't mind :)

**Comment by pattonwebz** [comment]
@felipeelia I don't mind at all. Thank you for taking care of it :)
