### ISSUE TITLE
Latest Posts Block

### ISSUE THREAD

**Issue by luminuu** [WordPress/twentytwentyone#76]
There's a design for the latest posts block, the first one: https://www.figma.com/file/OEtsCj8oD8JPVx4OvsS0U2/Twenty-Twenty-One?node-id=7%3A33

Todos:
- [ ] Make the list view match the given design.
- [ ] Check how other features the latest posts block offers can be integrated in the minimalistic design.
- [ ] Decide how the grid view the block offers should look like (@melchoyce ?)

**Comment by melchoyce** [comment]
Let me mock up the default states for the Latest Posts block 👍

**Comment by melchoyce** [comment]
## List Mockups

Default settings, with author and date, and then with author, date, and excerpt.

![image](https://user-images.githubusercontent.com/2846578/94212867-5658b580-fea3-11ea-8311-1f8cdeae4574.png)

## Grid Mockups

![image](https://user-images.githubusercontent.com/2846578/94212878-5f498700-fea3-11ea-84ec-6261329f67c3.png)

Default settings, with author and date, and then with author, date, and excerpt. (I mocked up the last one as wide-width for my pride, okay?)

## Theme-Included Block Styles

![image](https://user-images.githubusercontent.com/2846578/94213650-62457700-fea5-11ea-9918-e054cb9455bb.png)

Alternate style concepts for the list and grid view we could include with the theme.

**Comment by kjellr** [comment]
What should we call the theme-included block style?

**Comment by melchoyce** [comment]
I'm terrible at naming things, so I'd love suggestions from more folks here. My first instinct is "fancy stuff" 😂

**Comment by kjellr** [comment]
😄 Yeah, it's kind of like "Posts with Dividers/Borders"

**Comment by melchoyce** [comment]
Maybe we could get away with "Posts with Borders"

**Comment by kjellr** [comment]
@melchoyce it struck me that the grid version that has the divider line on top, and the list version that has the divider lines are both pretty similar. I wonder if those and up being a "Posts with Dividers" version, and then we have another "Boxed" style? 

Here's how that would look: 

## Default

List|Grid
---|---
![Latest Posts (List, author and date)](https://user-images.githubusercontent.com/1202812/94297875-37a1ff80-ff33-11ea-99f9-498a654225e7.png)|![Latest Posts (Grid, wide-width, author, date, and excerpt)-1](https://user-images.githubusercontent.com/1202812/94297891-3c66b380-ff33-11ea-94c2-6a8a267bf826.png)

## Dividers

List|Grid
---|---
![Latest Posts (List block style)](https://user-images.githubusercontent.com/1202812/94297925-4983a280-ff33-11ea-8d40-f638b0bb6ada.png)|![Latest Posts (Grid, wide-width, author, date, and excerpt)](https://user-images.githubusercontent.com/1202812/94297927-4a1c3900-ff33-11ea-92f9-5caff52314a8.png)

## Borders

List|Grid
---|---
![Latest Posts (List block style)-1](https://user-images.githubusercontent.com/1202812/94298020-6f10ac00-ff33-11ea-8180-086bf531acac.png)|![Latest Posts (Grid block style)](https://user-images.githubusercontent.com/1202812/94298023-6fa94280-ff33-11ea-8fb6-de323222ad55.png)

**Comment by melchoyce** [comment]
Ah yeah, good call — that makes sense 👍
