### ISSUE TITLE
my site logo is stretched

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwentyone#760]
My logo looked fine the other day when I added it, but something changed since then (I just downloaded today's version of the theme zip).
The PNG file is 160px by 142px, no cropping done.

![stretched-logo](https://user-images.githubusercontent.com/7957680/97764753-a992d900-1add-11eb-99bf-84657352c3a9.jpg)

In the Customizer, it looks fine when the logo is by itself.
![stretched-logo](https://user-images.githubusercontent.com/7957680/97764756-aef02380-1add-11eb-879d-2ce12d0acb8e.gif)

**Comment by carolinan** [comment]
The `twenty_twenty_one_get_attachment_image_attributes` is unintentionally affecting the custom logo functionality, which uses this filter.
