### ISSUE TITLE
navigation links for custom post types

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwentyone#761]
I think the theme should provide navigation if its template is loaded. It shouldn't say post though. Using 'Next' and 'Previous' would work fine.

_Originally posted by @joyously in https://github.com/WordPress/twentytwentyone/issues/566#issuecomment-710735196_

The user shouldn't have to have a custom template to show custom post types.
I tested removing the `if ( is_singular( 'post' ) ) ` from single.php and it works fine on posts, pages, attachments, and custom post types. The only thing needed is to remove the word Post from the Next and Previous texts.

**Comment by carolinan** [comment]
It is not common for a user to add their own custom post types. If an advanced user is capable of adding custom post types they are also capable of adding the templates. 

 It is up to the plugin that adds the post type to provide the templates.

The design is set here, and this issue has already been replied to.

**Comment by joyously** [comment]
That is not my experience at all.
If the template is loaded, which it will be for those that make simple custom post types with simple plugins like Custom Post Type UI, then it should faithfully show the navigation of the Next and Previous, instead of nothing.

**Comment by abuyoyo** [comment]
> It is up to the plugin that adds the post type to provide the templates.

Core does not provide a way for a plugin to hook into the templates. So the solution proposed - adding a custom post type in a plugin _and then_ adding a child theme to add a template for that custom post type - seems a bit much.
Either way this solution would require two separate installs - a plugin and a child-theme.

Not really sure why a theme would limit the navigation only to post and pages. This seems like a reasonable expectation - to support all post-types the same _unless_ a specific template was added in a theme. Not sure why this was closed. I read the other ticket too.

**Comment by carolinan** [comment]
Reopened, but I don’t agree with the assumption that a custom post type even has next and previous navigation.

**Comment by pattonwebz** [comment]
I think wrapping the noun used in the text with a filter might be sufficient to allow customization for different post types? If not a 'post' post_type the it could grab the post type label or something?

It might be over the top to add a filter to modify this? Do you think using a filter is something an average user that has extra post types might be able to do?

**Comment by joyously** [comment]
I looked at the labels available when registering a post type. They don't include "Next Item" and "Previous Item", and you can't really just stick two words together, since translations don't work that way. 
That's why it seems easiest to simply remove the "Post" part and just have "Next" and "Previous".
