### ISSUE TITLE
Quote block: bold looks less bold than non-bold

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwentyone#762]
I don't think this is an editor problem, but the default style, because it works correctly in my theme.
I made a word in a quote block bold, but that word looks normal and the rest looks bold.

**To Reproduce**
1. Go to the block editor.
2. Add a quote block and type some text.
3. Select a word and click on the Bold icon to make it bold.
4. See that it looks non-bold and the rest of the text looks bold.

**Expected behavior**
The bold text should look bolder than the non-bold text.

**Screenshots**
Front end with one bold word in two quote blocks.
![Block Quote – Local Current WP-31](https://user-images.githubusercontent.com/7957680/97767383-c503e100-1ae9-11eb-9866-b9cdd3d0cfef.jpg)

Editor, showing the B indicator is on when on the bold word.
![bold-quotes](https://user-images.githubusercontent.com/7957680/97767415-e49b0980-1ae9-11eb-91df-30af44f74f34.gif)

**Editor version (please complete the following information):**
- WordPress version: 5.5.3
- no Gutenberg plugin

**Desktop (please complete the following information):**
 - OS: Ubuntu Studio 20.04
 - Browser Firefox 82.0

**Comment by felipeelia** [comment]
Hi @joyously ,

I was giving a look into the issue and it seems it looks like that intentionally:

https://github.com/WordPress/twentytwentyone/blob/trunk/assets/sass/04-elements/blockquote.scss#L54
```
	strong {
		// "Bold" text is intentionally unbolded to differentiate from the rest of the quote.
		font-weight: var(--quote--font-weight);
	}
```

I'm trying to get familiarized with the theme, so I'll be happy to create a Pull Request if it needs to be reverted.

**Comment by joyously** [comment]
Ah, so it's intentional to confuse the user? (making `strong` not strong)
The editor experience is not good, and existing content is contrary to what is intended by the user.

**Comment by kjellr** [comment]
This is a common problem with any theme text that is bold by default.

In the near term, I believe the only solution we have (other than keeping things the way they are) would be to switch to using `bolder` here. Though I'm not positive that all typefaces in the stack will have a bolder equivalent available.

**Comment by joyously** [comment]
It sounds like bold is not a good default.

**Comment by melchoyce** [comment]
We could make the quotations themselves semibold instead of bold, perhaps, if it's a problem?

**Comment by kjellr** [comment]
I think it's ok the way it is — any system that doesn't have a weight bolder than bold is also unlikely to have a semi-bold weight available too. But anyway, I did some testing in the PR and it seemed like this works fine in Windows, Android, Mac, and iOS. So that's pretty good.
