### ISSUE TITLE
Testing and adjusting footer widget area

### ISSUE THREAD

**Issue by luminuu** [WordPress/twentytwentyone#77]
There's only one widget area given in Twenty Twenty One and each widget is added to the next available spot. It consists of three columns on wide screens.

As the new block based widget screen got out of experimental status in Gutenberg 8.9.0, it's most likely to land in 5.6, so we need to have this area working for both the old-school widgets and the blocks.

In my recent test the social icons block did not align right due to the given setup (float is added but as it's a flex item float doesn't work, it needs to be justify-content: flex-end). It's also not possible to style the icons with the dark grey color unless you add additional CSS via the customizer.

**Comment by melchoyce** [comment]
How's this?

![image](https://user-images.githubusercontent.com/2846578/94291601-d590cc80-ff29-11ea-9528-e73b8253b749.png)

[Mockup in Figma](https://www.figma.com/file/OEtsCj8oD8JPVx4OvsS0U2/Twenty-Twenty-One?node-id=1046%3A561)

**Comment by carolinan** [comment]
There are problems with several of the links in the footer and widget area, and to move forward we need the link styles to be merged asap.
