### ISSUE TITLE
Primary navigation: Style the page menu

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#770]
**Describe the bug**
If a site has a fall back page menu, and then switches to Twenty Twenty-One, the page menu is still in use.
Because of this, the theme needs to style the page menu even though it can't be activated when using the theme.

Currently the responsive menu is broken and there is a JavaScript error:
```
primary-navigation.js?ver=1.0.0:44 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
    at twentytwentyoneSubmenuPosition (primary-navigation.js?ver=1.0.0:44)
    at twentytwentyoneToggleAriaExpanded (primary-navigation.js?ver=1.0.0:17)
    at HTMLButtonElement.mobileButton.onclick (primary-navigation.js?ver=1.0.0:96)
```

And the wide menu is displayed vertically instead of horizontally.

**To Reproduce**
1. Activate a different theme 
2. Make sure that no menu is set to the menu locations.
3. Switch to Twenty Twenty-One

**Expected behavior**
The fallback page menu should have the same style as the selected menu.

**Screenshots**
![pagemenu](https://user-images.githubusercontent.com/7422055/97839577-bb919900-1ce2-11eb-9c51-ade252ecdc87.png)

**Comment by carolinan** [comment]
After testing, this is easier solved by adding `'fallback_cb'     => 'false',` to `wp_nav_menu`.
Not supporting the page menu is more in line with what was initially decided.

**Comment by aristath** [comment]
> After testing, this is easier solved by adding `'fallback_cb'     => 'false',` to `wp_nav_menu`.
Not supporting the page menu is more in line with what was initially decided.

Makes perfect sense :+1:
