### ISSUE TITLE
Sticky-post notice is unreadable

### ISSUE THREAD

**Issue by aristath** [WordPress/twentytwentyone#806]
![Screenshot_2020-11-06 Template Sticky – My Blog](https://user-images.githubusercontent.com/588688/98378155-54f7dc80-204e-11eb-8f71-6c91315de626.png)

**Comment by carolinan** [comment]
What are the steps to reproduce this?
To me it looks like a regular paragraph with a text color and background color?

**Comment by aristath** [comment]
My bad, invalid issue
