### ISSUE TITLE
Accessibility: WCAG 2.4.10 Section Headings Level AAA

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#81]
Section headings are used to organize the content.
Note 1: "Heading" is used in its general sense and includes titles and other ways to add a heading to different types of content.

Reference:
https://www.w3.org/WAI/WCAG21/Understanding/section-headings.html

Question, do we need a visually hidden heading for the footer, or is the HTML5 footer element and content info ARIA role enough for this section? 
The aria role does not help users that wishes to navigate using headings, but for others the information would be repeated?

https://github.com/WordPress/twentytwentyone/blob/trunk/footer.php#L19

**Comment by samikeijonen** [comment]
I'd also vote no for this. For the same logic we'd need to add heading in the `<header>` also.
