### ISSUE TITLE
Responsive menu is cut off on mobile

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#821]
**Describe the bug**
In Edge, Chrome, and Firefox, the last menu item of the responsive menu is not visible, depending on the menu size.

It is not possible to scroll down far enough for all menu items to show when using the theme unit test menus
"All Pages" or "Testing menu" in the primary location.

No issues in Opera mini.

**To Reproduce**
1. Create a menu with many items, or use the menus in the theme unit test mentioned above.
2. View the page on mobile
3. Toggle the responsive menu.
4. Scroll as far down as possible. See that the menu item or menu description at the bottom is cut off or not visible.

**Expected behavior**
All items need to be visible and reachable.

**Screenshots**
![thumbnail_Screenshot_20201109_154155_com android chrome](https://user-images.githubusercontent.com/7422055/98555692-8832a980-22a2-11eb-95c7-3a8554c648da.jpg)

**Smartphone (please complete the following information):**
 - Device: Huawei P20 (Android)
 - Browser: Edge, Chrome, Firefox

**Comment by allancole** [comment]
Yup, I can confirm this is in issue on Chrome and iOS 14. Here’s a screencap of it: 

![RPReplay_Final1604933420](https://user-images.githubusercontent.com/709581/98557885-c1532580-2272-11eb-904f-b0b3f56f824c.gif)

I have to sort of over-scroll to get the **Page A** and **Page B** menu-items in view, but as soon release the scroll, those two links fall back below the bottom of the viewport and I can’t tap them.
