### ISSUE TITLE
Dark Mode Docs

### ISSUE THREAD

**Issue by aristath** [WordPress/twentytwentyone#828]
Suggested text for the HelpHub page for the Twenty Twenty-One theme:
---------------

## Dark Mode Support

One of the accessibility features of the Twenty Twenty-One theme is support for the visitor's color scheme preferences in their operating system or browser's settings. The feature is opt-in and supported in most operating systems, including [Android](https://support.google.com/chrome/answer/9275525?co=GENIE.Platform=Android&hl=en), [iOS](https://support.apple.com/en-us/HT210332), [OSX](https://support.apple.com/en-us/HT208976), [Windows 10](https://support.microsoft.com/en-us/windows/change-desktop-background-and-colors-176702ca-8e24-393b-15f2-b15b38f69de6), as well as most Linux distributions.

If you have Dark Mode enabled, your site will be shown to visitors using a light or dark color scheme, respecting their operating system's preferences. Depending on their lighting conditions or personal preferences they may choose to switch color schemes using a dedicated button on the bottom-right of their screen (or bottom-left for RTL languages).

### Enabling Dark Mode from the Customizer

To activate Dark Mode Support, you can go to the `Colors & Dark Mode` section in your Customizer. If you have a light color selected for the site's background, you will be able to see and activate the `Dark Mode Support` setting. The background color you select will be applied to light mode, while Dark Mode colors are optimized automatically. You can use the `Dark Mode On/Off` button at the bottom of the preview screen to toggle between dark & light schemes in your preview.

### Dark Mode in the Editor

The editor will by default respect your operating system's color scheme settings. If on the frontend of your site you have chosen a different scheme (using the `Dark Mode On/Off` button), then the editor will use the preferred scheme.

**Comment by melchoyce** [comment]
Looks good, thanks for writing this up 👍 

One quick note: "color scheme" and "background color" (outside of CSS) shouldn't be hyphenated. I also noticed one use of "dark-mode," which should probably be capitalized (Dark Mode) like the other instances.

**Comment by aristath** [comment]
Thank you, updated :+1:

**Comment by aristath** [comment]
Cleaning up the repo so I'll go ahead and close this one. Text was copied to the doc, further edits can be made there if needed.
