### ISSUE TITLE
Background image in combination with dark mode

### ISSUE THREAD

**Issue by LittleBigThing** [WordPress/twentytwentyone#829]
Just a thought, not as much a bug as a possible usability/accessibility concern: how about using the custom background image feature (in the Customizer) in combination with dark mode? This can give surprising results.

For example, if dark mode is on and a background image is selected with an overall light background color during the day (with device settings set to automatic or to light mode), the light text color that appears by night becomes unreadable on the light background of the image (on another device). There is of course the front-end toggle to solve this but still weird, isn't it?

Although having a background image can give usability and accessibility issues even without using dark mode, the results can be more unexpected because they might not be tested with dark mode on. We have handled possible accessibility issues as a results of the custom background feature differently in the past. It was left out of Twenty Nineteen for that reason, but remained in Twenty Twenty.

The choice is really between making it possible having subtle background images/patterns (even in combination with dark mode) and giving the user freedom (and trust ;-)), or leaving the background feature out to avoid possible concerns.

**Comment by aristath** [comment]
Dark Mode is opt-in. If the user chooses to add a background-image then they should not enable Dark Mode Support. If they do, then well.. poor choices lead to poor results and we can't stop people from making poor choices.
It's possible (unlikely but not impossible) that they actually use a transparent pattern that just adds a slight embossed/paper feel and it would work well both with light and dark mode. But that's up to the user and not something we can (or should) enforce.

**Comment by carolinan** [comment]
Unfortunately the background image and background color are tied together in the same `custom-background` theme support. So the theme can not easily disable the background image feature.
https://core.trac.wordpress.org/ticket/48241

**Comment by LittleBigThing** [comment]
@aristath I mostly agree. I mention it because this was handled differently in the past (in Twenty Nineteen), trying to limit the possibility for making poor choices.

@carolinan Oh, yeah, true. That leaves us with less choices for now. :-)

**Comment by aristath** [comment]
Closing this one since it's not something actionable.
