### ISSUE TITLE
Inform user when Dark Mode feature unavailable because site background color is dark.

### ISSUE THREAD

**Issue by adamsilverstein** [WordPress/twentytwentyone#833]
**Describe the bug**
When testing the Dark Mode feature I noticed that if I set my theme's background color to a dark color, the option to enable the dark mode feature disappears:
 
While this makes sense functionally, I found it confusing as a user. I wanted to enable dark mode, after I set the background color. When I chose a dark color, then discovered the Dark Mode option was gone, I was confused.

**To Reproduce**
1. Test a dark background color.

**Expected behavior**
Perhaps when the background is too dark we can grey out/disable the Dark Mode feature? Or perhaps display a notice to the user "Choose a lighter background color to enable the Dark Mode feature"?

**Screenshots**
[Screencast](https://user-images.githubusercontent.com/2676022/98832250-d4dcc880-23f9-11eb-961b-ff5c18344c5c.gif)

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.5.1]
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"]
- If the Gutenberg plugin is installed, which version is it? [e.g., 8.9]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by melchoyce** [comment]
FWIW, I think it would be more straightforward to remove this conditional and not worry about someone's chosen background color.

**Comment by carolinan** [comment]
There is already a description above the option that says that you need to select a light color to access the Dark Mode settings.

I am OK with the solution Mel suggested if it can be done easilly.

**Comment by carolinan** [comment]
@adamsilverstein I see the confusion now that I am more awake (good morning) The screencast is using an older version of the theme. 
Please test the current trunk version from this GitHub repository, or see https://make.wordpress.org/core/2020/11/10/twenty-twenty-one-dark-mode-update/

This is what the customizer option looks like currently:
![TT1-customizer-2](https://user-images.githubusercontent.com/7422055/98910665-c529b680-24c3-11eb-909f-000eded490ef.png)

**Comment by aristath** [comment]
> I think it would be more straightforward to remove this conditional and not worry about someone's chosen background color.

Hmmm then what happens if I select a dark background-color and then enable the dak-mode checkbox? If I make a change to a control I expect to see a change in the preview, and in this case nothing would happen (assuming of course the selected background-color is dark)
If we do show the dark-mode control at all times, then perhaps we should disable the checkbox if the background-color is dark? This way it would be visible but greyed-out 🤔

**Comment by carolinan** [comment]
Thinking...
When the checkbox is checked, the background color does not need to change if it is already dark, but what changes is:
Device setting support
Toggle button visibility

**Comment by carolinan** [comment]
_If we do show the dark-mode control at all times, then perhaps we should disable the checkbox if the background-color is dark? This way it would be visible but greyed-out 🤔_

This has been suggested a few times during the tests. I think this solution would be less confusing for people, than completely hiding it.

**Comment by aristath** [comment]
See PR on #838 for an implementation of the checkbox-disabling without the control dependency.
