### ISSUE TITLE
Pull quote has the wrong default color on the front

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#837]
**Describe the bug**
On the front, the pull quote block is inheriting the color `#555` from the block files.
In the editor, the color is the dark grey  `#28303D`.

The _solid style_ pull quote has the correct color.

**To Reproduce**
1. Add a pull quote block.
2. Compare the colors in the editor and front.

**Expected behavior**
I expect the color in the editor and front to match.

**Screenshot**

![wrong-color](https://user-images.githubusercontent.com/7422055/98908968-767b1d00-24c1-11eb-9528-e5b6d8bcc7ea.png)

**Comment by JustinyAhin** [comment]
Looking at the figma files, the color normal color should be gray #39414D 
https://www.figma.com/file/OEtsCj8oD8JPVx4OvsS0U2/Twenty-Twenty-One?node-id=1254%3A64

**Comment by JustinyAhin** [comment]
What could be done is to add the `color: var(--global--color-gray);` to the `wp-block-pullquote` class both in frontend and in editor files.

**Comment by carolinan** [comment]
If we use this color and not the secondary or primary CSS variables, won't it affect the text color when the background is changed to dark?

I believe it is meant to have the same color as the body text?

**Comment by JustinyAhin** [comment]
I just tested. When a custom color is selected for the quote, it overwrites the color set in the css.
Lemme send a PR for testing.
