### ISSUE TITLE
Desktop Layout on Firefox 71 (Linux) is to wide

### ISSUE THREAD

**Issue by transl8or** [WordPress/twentytwentyone#843]
The desktop layout of the new default theme Twenty Twenty-One is much to wide on Firefox 71.
It reaches until the edge of 1920 px screen or bigger.

Firefox 71 from Dez. 2019 is the default browser currently delivered with Linux Mint 19.3 Mate or Cinnamon (LTS until April 2023).

The Issue does not appear when switching to the Twenty Twenty theme. This theme handles the older browser quite well.
The Issue is also gone when updating Firefox to a newer version on the above named operating system.

I add some screenshots.

**Twenty Twenty-One with WordPress 5.6 Beta 3**
![WP56beta3-2021-Theme-on1920pxDesktop-FireFox71](https://user-images.githubusercontent.com/23237850/98970859-b9b0ac80-2510-11eb-955e-31fc0d481833.jpg)

**Twenty Twenty with WordPress 5.6 Beta 3**
![WP56beta3-2020-Theme-on1920pxDesktop-FireFox71](https://user-images.githubusercontent.com/23237850/98970915-ca612280-2510-11eb-9482-f4d2f743cce6.jpg)

**Comment by carolinan** [comment]
Hi
This is also the situation for older browsers like Internet Explorer 11.
We will not be making any changes in support of this browser version.

The content can still be read and accessed even if the layout is not the same as in newer browser version.

From the screenshot, it looks like the themes CSS variables are not being used, but as far as I know, this browser version should support them.
