### ISSUE TITLE
Renaming of the text strings for the colors to more appropriate names

### ISSUE THREAD

**Issue by transl8or** [WordPress/twentytwentyone#844]
Not sure if this is an (urgent) issue but I would like to suggest to rename the text strings for the colors in the theme so that they express the beautiful choosen color palette in a more specific way.

As so many others I really like the muted, pastell colors for the new theme when it was introduced by @melchoyce on the w.org blog.

So I translated the given color strings with a bit more specific, but not unreal names. 
(Though it did not resonate quite well with some male fellows, but I believe also that for the case of accessibility and/or color blindness a renaming is helpful to be able to "imagine" the look and feel of the theme design.)

By the way, the names of the colors are really used in the area of interior design like kitchen fronts or wall paint or in automobile design.

green  -> (in german: Salbeigrün) ==> sagegreen
blue   -> (in german: Platinblau) ==> platinium blue
purple -> (in german: Flieder/fliederfarben) ==> lilac (like a syringa)
red    -> (in german: Altrosa) ==> antique pink
yellow -> (in german: Vanille) ==> vanilla
orange -> (in german: Beige)   ==> beige

If this names seem to extravagant we could also rename the colors to pastell colors, like:

pastell green, pastell blue, lilac, pastell red, pastell yellow and beige.

For me these sound more descriptive and give the special color palette of the new themes its deserved appreciation.

What do you think @melchoyce @ellenbauer @luminuu @carolinan @ryelle?

**Comment by carolinan** [comment]
Hi
We do not intend to rename the colors.

Beta 4 of WordPress is released today and it means that we can no longer change the text strings. This is to allow the translators enough time to translate the theme before the release of WordPress 5.6.
