### ISSUE TITLE
Use correct word for update

### ISSUE THREAD

**Issue by knutsp** [WordPress/twentytwentyone#853]
"This theme requires WordPress 5.3 or newer. You are running version %s. Please upgrade." should be
"This theme requires WordPress 5.3 or newer. You are running version %s. Please update."

**Comment by aristath** [comment]
If they are on a WP version older than 5.3, than I think that updating to the latest version of WP would definitely qualify as an upgrade and not an update... The way I understand it is that the difference between update & upgrade lies in the amount and severity of changes. So 5.2 to 5.2.1 would be an update, but 5.2.x to 5.6 (or any other major release) would be an upgrade.

**Comment by knutsp** [comment]
My understanding of wording used by WordPress comunity is that the word "upgrade" mean to change from a free/community version to a pro/paid/exteneded version, another more feature rich product. Analogy; You "upgrade" from 2nd class to 1st class seating, but you update your seating to just change position and such.

You **update** WordPress to get a newer version, regardless to the version difference. Maybe "upgrade" to WP mulitiste. Maybe upgrade to another plan at WordPress.com og Jetpack.

Can you point to any official and current statement about "upgrading" core WordPress?

**Comment by aristath** [comment]
> Can you point to any official and current statement about "upgrading" core WordPress?

No, there is none. Just like I'm sure you can't point to any official and current statement to the contrary.
WordPress uses the words update & upgrade inconsistently and on the same page you can find multiple occurrences of both terms with the same meaning.
Searching for "update vs upgrade" though I find people saying both things. To some an upgrade means they pay for it. To others, an upgrade is a large update. A patch version is an update while a major version is an upgrade. :shrug:

**Comment by carolinan** [comment]
Hi!
This was not chosen by chance, "upgrade" is the word used in the other default themes.

If you feel strongly about this, you can open a WordPress Core Trac issue to change the word in all of them so that it is consistent.

The release is in string freeze, which means we can not make changes to the text (only when obvious typos are reported),
because of this, I am closing the issue.
