### ISSUE TITLE
Form inputs look different between the editor and the frontend

### ISSUE THREAD

**Issue by Aljullu** [WordPress/twentytwentyone#862]
**To Reproduce**
1. Create a post and add an HTML block with these contents:
```HTML
<input type="range" min="0" max="100" />
<input type="checkbox" />
<input type="radio" />
<input type="text" />
```
2. In the editor, click on the 'Preview' option of the HTML block toolbar.
3. Now, save the post and preview it in the frontend.
4. Notice the input elements have different styles in the editor than in the frontend.

**Expected behavior**
I expected input styles to be loaded in the editor too.

**Screenshots**
_Editor:_
![imatge](https://user-images.githubusercontent.com/3616980/99797778-2be84900-2b30-11eb-99af-c22607bfb596.png)

_Frontend:_
![imatge](https://user-images.githubusercontent.com/3616980/99797807-373b7480-2b30-11eb-95ec-b3faf3f23cf1.png)

**Editor version (please complete the following information):**
- WordPress version: 5.6-beta4
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? "default"

**Comment by carolinan** [comment]
Do you have any examples of themes that styles the HTML preview? Because the preview is inside an iframe.

**Comment by carolinan** [comment]
Hi
This is an issue with the block editor, https://github.com/WordPress/gutenberg/issues/9129.
It affects all themes, and it needs to be solved in Gutenberg first.

If we tried to solve this in the theme it would require additional JavaScript "hacks" and it would be less than ideal.
Because of this, I am closing this issue.

**Comment by Aljullu** [comment]
@carolinan, thanks for looking into this and linking to the issue in Gutenberg, I wasn't aware of it.

Even though I wrote the testing steps using the HTML block as an example, the issue affects any other block that renders a form element in the editor/frontend. I discovered it while working on WooCommerce Blocks, but I'm pretty sure there will be other plugins/blocks affected by this.

As an example, imagine a block like this:

```JSX
registerBlockType( 'my-plugin/form-inputs-block', {
	title: __( 'Form inputs block', 'my-plugin' ),
	category: 'my-plugin',
	edit() {
		return (
			<div>
				<input type="range" min="0" max="100" />
				<input type="checkbox" checked />
				<input type="radio" checked />
				<input type="text" placeholder="Lorem Ipsum" />
			</div>
		);
	},
	save() {
		return (
			<div>
				<input type="range" min="0" max="100" />
				<input type="checkbox" checked />
				<input type="radio" checked />
				<input type="text" placeholder="Lorem Ipsum" />
			</div>
		);
	},
} );
```

This is how it renders with Twenty Twenty One:

| Editor | Frontend |
| :---: | :---: |
| ![imatge](https://user-images.githubusercontent.com/3616980/100460473-83099300-30c7-11eb-9ac9-1f9eb718819d.png) | ![imatge](https://user-images.githubusercontent.com/3616980/100460493-8b61ce00-30c7-11eb-8d4b-0651c65b9ebb.png) |

I see the SCSS file for forms included in `style.scss` and `style-editor.scss` is different. I wonder if that's intentional and, if that's the case, whether you have any advice for plugins/blocks that use form elements on how we can achieve a closer look frontend/editor for our blocks with Twenty Twenty One.

Thanks in advance!

**Comment by carolinan** [comment]
@Aljullu The only way to assure that any element is styled is to style it in the plugin because there will always be themes that are not styled.
WooCommerce already styles their forms and buttons but you need to use the CSS classes.
