### ISSUE TITLE
Bug: Cursor is not visible when inserting a new button.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/twentytwentyone#878]
**NB! Please skip straight to this comment:** 
https://github.com/WordPress/twentytwentyone/issues/878#issuecomment-732961808

------------------

**Describe the bug**
Using the Buttons block it looks like this in the backend:
![Screen Shot 2020-11-24 at 11 38 14](https://user-images.githubusercontent.com/5323259/100083315-91e31200-2e49-11eb-94c4-195f7f16576f.png)

In comparison with theme Twenty Twenty.

![Screen Shot 2020-11-24 at 11 29 22](https://user-images.githubusercontent.com/5323259/100083213-6c560880-2e49-11eb-82ac-d2c1d6fa2aad.png)

**To Reproduce**
1. Add a Buttons block.
2. Add a few buttons.
3. Notice the difference between button one and button two.

**Expected behavior**
All buttons in one nice row.

**Editor version (please complete the following information):**
- WordPress version: 5.5.3
- Gutenberg version: 9.4.1

No other plugin is activated.

Running locally through Desktop Server. 
Browser: Chrome
Macbook Pro: OSX 10.15.7

**Comment by carolinan** [comment]
Related to https://github.com/WordPress/twentytwentyone/pull/859

Do you see the same problem without Gutenberg 9.4.1? Or with 5.6 RC?

**Comment by paaljoachim** [comment]
That is interesting!
Turning off the Gutenberg plugin 9.4.1. The buttons show in a nice row as they should.
(No plugins are activated.)

![Screen Shot 2020-11-24 at 12 26 58](https://user-images.githubusercontent.com/5323259/100088440-631c6a00-2e50-11eb-9359-19d4b5221f53.png)

**Comment by carolinan** [comment]
So we need to both work on the open pull request, and narrow down what changed between <del>RC1</del> and 9.4.1. 🤔 

Right so the number of updates between 5.5.3 and 9.4.1 are significant, this also needs to be tested on 5.6 RC.

**Comment by paaljoachim** [comment]
**NB! A correction!**
I downloaded the newest version of Twenty Twenty One. As I had an earlier version installed for the above testing.
**I am sorry about that.** 

Made a new page and added the Buttons block.
No plugin activated.

![Twenty-Twenty-One-Buttons-block](https://user-images.githubusercontent.com/5323259/100097994-a7facd80-2e5d-11eb-8c18-b01f7ea97362.gif)


I expected a blinking cursor inside when a buttons block is selected.

Activated Gutenberg plugin 9.4.1.

![Twenty-Twenty-One-Buttons-Block-With-Gutenberg-plugin](https://user-images.githubusercontent.com/5323259/100098295-26576f80-2e5e-11eb-8299-ff55fc3431bf.gif)

I am thinking either we can look at the missing blinking cursor inside the selected buttons block or we can close the issue.

**Comment by carolinan** [comment]
I see the problem, and first I thought it was because the cursor was the same color as the text, which is the background color, but even if I change its color, it does not show up when the button is added, only when you start typing.
