### ISSUE TITLE
Use :focus-visible instead of :focus to remove undesirable focus styles for mouse clicking

### ISSUE THREAD

**Issue by marctison75** [WordPress/twentytwentyone#895]
Currently, there’s a difference of focus behavior between Safari and the other browsers. With Safari, the focus styles appear only when tabbing. With the other browsers (Chrome, Firefox, Edge), the focus styles also appear when mouse clicking.

“Focus styles can often be undesirable when they are applied as a result of a mouse/pointer interaction” — [Paciello Group](https://developer.paciellogroup.com/blog/2018/03/focus-visible-and-backwards-compatibility/).

According to W3C https://css-tricks.com/keyboard-only-focus-styles/, it’s advised to use `:focus-visible` instead of `:focus`. 
“Also, the W3C proposal mentions that `:focus-visible` should be preferred over `:focus` except on elements that expect a keyboard input (e.g. text field, contenteditable).”

Firefox, Chrome, Edge support this feature. For other browsers, including Safari, we can use a polyfill or define regular focus styles for non-supporting browsers and then overwrite them for browsers that support `:focus-visible`. https://developer.paciellogroup.com/blog/2018/03/focus-visible-and-backwards-compatibility/

**Comment by carolinan** [comment]
Hi
Realistically the main obstacle for this change is that we are not able to redo the focus styles this late in the release cycle and development.

I have not heard of `:focus-visible` before or that this :focus style is undesired or a nuisance. I would need to research it.

@audrasjb @sarahricker 
If the WordPress accessibility team believes that this is something that **must** be fixed during the RC, we can try to find the resources but we are also in the middle of a holiday so the regular contributors are not available.

**Comment by carolinan** [comment]
This was discussed during the accessibility teams weekly bug scrub, and they were not sure that using focus-visible would be an accessibility improvement. 
Considering that and the short time we have to test and implement it I don't think we will be able to change it.
