### ISSUE TITLE
Code quality: Add Github actions for pull requests

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#9]
Each pull request should be checked for PHP compatibility and to ensure that coding standards are followed.

**Comment by melchoyce** [comment]
What's still needed here?

**Comment by jeffikus** [comment]
@dingo-d thanks for #62 :) the main reason for merging #60 first was to get something in before the repo went public, but I'm glad your better one is in!

@aristath @dingo-d do we need to do anything more for:

- [x] CSS
- [ ] JS
- [x] PHP

**Comment by dingo-d** [comment]
There is a stylelint action (CSS), I think we can add ESLint one as well

**Comment by aristath** [comment]
PHP & CSS are already covered, for JS (eslint) I think we can open a new ticket and get those linted as well. We may not have a lot of JS right now, but we still have a long way to go before the theme is ready and more JS may be added :+1:
